# Generated by Django 5.0.14 on 2026-06-20 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('partner_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CORPORATE', 'Corporate')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('PENDING_DOCUMENTS', 'Pending Documents'), ('COMPLIANCE_CHECK', 'Compliance Check'), ('APPROVED', 'Approved'), ('CONVERTED', 'Converted to Partner'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='DRAFT', max_length=30)),
                ('identification_type', models.CharField(blank=True, choices=[('NIN', 'National Identification Number'), ('ZAN_ID', 'Zanzibar ID'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('TIN', 'Tax Identification Number'), ('VOTER_ID', 'Voter ID'), ('RESIDENT_PERMIT', 'Resident Permit'), ('MILITARY_ID', 'Military ID')], max_length=30)),
                ('identification_number', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Hon', 'Hon'), ('Eng', 'Eng'), ('Rev', 'Rev')], max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('other_name', models.CharField(blank=True, max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Separated')], max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('nationality', models.CharField(blank=True, choices=[('Tanzanian', 'Tanzanian'), ('Kenyan', 'Kenyan'), ('Ugandan', 'Ugandan'), ('Rwandan', 'Rwandan'), ('Burundian', 'Burundian'), ('Congolese', 'Congolese'), ('South African', 'South African'), ('Nigerian', 'Nigerian'), ('Ghanaian', 'Ghanaian'), ('Ethiopian', 'Ethiopian'), ('Somali', 'Somali'), ('Mozambican', 'Mozambican'), ('Malawian', 'Malawian'), ('Zambian', 'Zambian'), ('Zimbabwean', 'Zimbabwean'), ('Indian', 'Indian'), ('Chinese', 'Chinese'), ('British', 'British'), ('American', 'American'), ('Other', 'Other')], max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('tin_number', models.CharField(blank=True, max_length=50)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, choices=[('TECHNOLOGY', 'Technology'), ('HEALTHCARE', 'Healthcare & Pharmaceuticals'), ('FINANCIAL_SERVICES', 'Financial Services & Banking'), ('CONSUMER_GOODS', 'Consumer Goods & Retail'), ('ENERGY', 'Energy & Utilities'), ('MANUFACTURING', 'Manufacturing & Industrial'), ('TELECOMMUNICATIONS', 'Telecommunications'), ('TRANSPORTATION', 'Transportation & Logistics'), ('REAL_ESTATE', 'Real Estate & Construction'), ('MEDIA', 'Media & Entertainment'), ('AEROSPACE', 'Aerospace & Defense'), ('AUTOMOTIVE', 'Automotive'), ('AGRICULTURE', 'Agriculture & Food Production'), ('HOSPITALITY', 'Hospitality & Tourism'), ('EDUCATION', 'Education & Training'), ('PROFESSIONAL_SERVICES', 'Professional Services & Consulting'), ('INSURANCE', 'Insurance'), ('MINING', 'Mining & Metals'), ('CHEMICALS', 'Chemicals'), ('TEXTILES', 'Textiles & Apparel'), ('ENVIRONMENTAL', 'Environmental Services'), ('BIOTECHNOLOGY', 'Biotechnology'), ('E_COMMERCE', 'E-commerce'), ('RENEWABLE_ENERGY', 'Renewable Energy'), ('CYBERSECURITY', 'Cybersecurity'), ('AI_ML', 'AI & Machine Learning'), ('FINTECH', 'Fintech'), ('LIFE_SCIENCES', 'Life Sciences'), ('OIL_GAS', 'Oil & Gas'), ('CONSUMER_ELECTRONICS', 'Consumer Electronics')], max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_person_phone', models.CharField(blank=True, max_length=20)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254)),
                ('physical_address', models.TextField(blank=True)),
                ('postal_address', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone_number', models.CharField(blank=True, max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('political_risk', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('PEP', 'Politically Exposed Person')], default='LOW', max_length=20)),
                ('aml_risk', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('compliance_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Application',
                'verbose_name_plural': 'Partner Applications',
                'db_table': 'onboarding_partner_application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('NID', 'National ID'), ('PASSPORT', 'Passport'), ('ZAN_ID', 'Zanzibar ID'), ('DRIVING_LICENSE', 'Driving License'), ('TIN_CERTIFICATE', 'TIN Certificate'), ('VOTER_ID', 'Voter ID'), ('RESIDENT_PERMIT', 'Resident Permit'), ('MILITARY_ID', 'Military ID'), ('INCORPORATION_CERT', 'Certificate of Incorporation'), ('MEMORANDUM', 'Memorandum of Association'), ('BOARD_RESOLUTION', 'Board Resolution'), ('OTHER', 'Other')], max_length=50)),
                ('document_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='partner_documents/%Y/%m/')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='partner_onboarding.partnerapplication')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Document',
                'verbose_name_plural': 'Application Documents',
                'db_table': 'onboarding_partner_application_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerApplicationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('DOCUMENT_REQUEST', 'Document Request'), ('COMPLIANCE_CHECK', 'Compliance Check'), ('REVIEW', 'Review'), ('APPROVAL', 'Approval'), ('OTHER', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='partner_onboarding.partnerapplication')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_onboarding_tasks', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_onboarding_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Task',
                'verbose_name_plural': 'Application Tasks',
                'db_table': 'onboarding_partner_application_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='partnerapplication',
            index=models.Index(fields=['application_number'], name='onboarding__applica_93a5f7_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerapplication',
            index=models.Index(fields=['status'], name='onboarding__status_84187c_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerapplication',
            index=models.Index(fields=['partner_type', 'status'], name='onboarding__partner_e7d8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerapplication',
            index=models.Index(fields=['submitted_by', 'status'], name='onboarding__submitt_194d58_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerapplication',
            index=models.Index(fields=['email'], name='onboarding__email_c0749e_idx'),
        ),
        migrations.AddConstraint(
            model_name='partnerapplication',
            constraint=models.CheckConstraint(check=models.Q(('partner_type', 'INDIVIDUAL'), ('partner_type', 'CORPORATE'), _connector='OR'), name='valid_partner_type'),
        ),
    ]
