# Generated by Django 5.0.14 on 2026-06-25 05:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_onboarding', '0003_seed_partner_types_and_branches'),
        ('partners', '0010_partnertypedocumentrequirement_allow_multiple_uploads_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='partner_onboarding.partnerapplication')),
                ('field_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_field_values', to='partners.partnertypefieldconfiguration')),
            ],
            options={
                'verbose_name': 'Application Field Value',
                'verbose_name_plural': 'Application Field Values',
                'db_table': 'onboarding_application_field_value',
                'ordering': ['field_config__display_order', 'field_config__field_code'],
                'unique_together': {('application', 'field_config')},
            },
        ),
    ]
