# Generated by Django 5.0.14 on 2026-06-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_onboarding', '0006_seed_choice_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerapplication',
            name='company_incorporation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
