# Generated by Django 5.0.14 on 2026-06-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_onboarding', '0009_fix_unified_view_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedOnboardingRecord',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('record_type', models.CharField(max_length=20)),
                ('application_id', models.UUIDField(null=True)),
                ('partner_id', models.UUIDField(null=True)),
                ('reference_number', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=255)),
                ('partner_type', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=50)),
                ('application_status', models.CharField(max_length=50, null=True)),
                ('kyc_status', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Unified Onboarding Record',
                'verbose_name_plural': 'Unified Onboarding Records',
                'db_table': 'onboarding_unified_record',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='partnerapplication',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('MODIFIED', 'Modified'), ('ACTIVE', 'Active'), ('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('PENDING_DOCUMENTS', 'Pending Documents'), ('COMPLIANCE_CHECK', 'Compliance Check'), ('APPROVED', 'Approved'), ('CONVERTED', 'Converted to Partner'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='CREATED', max_length=30),
        ),
    ]
