# Generated by Django 5.0.14 on 2026-06-28 04:44

from django.db import migrations, models


UNIFIED_VIEW_SQL = """
DROP VIEW IF EXISTS onboarding_unified_record;
CREATE VIEW onboarding_unified_record AS
SELECT
    a.id as id,
    'APPLICATION' as record_type,
    a.id as application_id,
    p.id as partner_id,
    a.application_number as reference_number,
    COALESCE(NULLIF(TRIM(a.company_name), ''), NULLIF(TRIM(a.first_name || ' ' || COALESCE(a.surname, '')), ''), a.email) as display_name,
    a.partner_type as partner_type,
    a.email as email,
    a.mobile_number as mobile_number,
    a.status as application_status,
    k.kyc_status as kyc_status,
    a.created_at as created_at
FROM onboarding_partner_application a
LEFT JOIN partner_partner p ON p.created_from_application_id = a.id
LEFT JOIN (
    SELECT partner_id, kyc_status
    FROM (
        SELECT ta.partner_id, kp.kyc_status,
               ROW_NUMBER() OVER(PARTITION BY ta.partner_id ORDER BY kp.created_at DESC) as rn
        FROM partner_kyc_profile kp
        JOIN partner_type_assignment ta ON kp.assignment_id = ta.id
    ) sub
    WHERE rn = 1
) k ON k.partner_id = p.id
WHERE a.status != 'CONVERTED'

UNION ALL

SELECT
    p.id as id,
    'PARTNER' as record_type,
    p.created_from_application_id as application_id,
    p.id as partner_id,
    p.partner_number as reference_number,
    CASE
        WHEN COALESCE(NULLIF(TRIM(p.partner_category), ''), p.partner_type) = 'INDIVIDUAL'
        THEN TRIM(COALESCE(p.title || ' ', '') || COALESCE(p.first_name || ' ', '') || COALESCE(p.other_name || ' ', '') || COALESCE(p.surname, ''))
        ELSE p.company_name
    END as display_name,
    p.partner_type as partner_type,
    p.email as email,
    p.mobile_number as mobile_number,
    'CONVERTED' as application_status,
    k.kyc_status as kyc_status,
    p.created_at as created_at
FROM partner_partner p
LEFT JOIN (
    SELECT partner_id, kyc_status
    FROM (
        SELECT ta.partner_id, kp.kyc_status,
               ROW_NUMBER() OVER(PARTITION BY ta.partner_id ORDER BY kp.created_at DESC) as rn
        FROM partner_kyc_profile kp
        JOIN partner_type_assignment ta ON kp.assignment_id = ta.id
    ) sub
    WHERE rn = 1
) k ON k.partner_id = p.id;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('partner_onboarding', '0009_fix_unified_view_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedOnboardingRecord',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('record_type', models.CharField(max_length=20)),
                ('application_id', models.UUIDField(null=True)),
                ('partner_id', models.UUIDField(null=True)),
                ('reference_number', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=255)),
                ('partner_type', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=50)),
                ('application_status', models.CharField(max_length=50, null=True)),
                ('kyc_status', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Unified Onboarding Record',
                'verbose_name_plural': 'Unified Onboarding Records',
                'db_table': 'onboarding_unified_record',
                'managed': False,
            },
        ),
        # SQLite rebuilds this table for the status-field alteration. The
        # unmanaged unified view references the table being rebuilt, so it must
        # be removed temporarily and recreated after the table operation.
        migrations.RunSQL(
            sql="DROP VIEW IF EXISTS onboarding_unified_record;",
            reverse_sql=UNIFIED_VIEW_SQL,
        ),
        migrations.AlterField(
            model_name='partnerapplication',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('MODIFIED', 'Modified'), ('ACTIVE', 'Active'), ('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('PENDING_DOCUMENTS', 'Pending Documents'), ('COMPLIANCE_CHECK', 'Compliance Check'), ('APPROVED', 'Approved'), ('CONVERTED', 'Converted to Partner'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='CREATED', max_length=30),
        ),
        migrations.RunSQL(
            sql=UNIFIED_VIEW_SQL,
            reverse_sql="DROP VIEW IF EXISTS onboarding_unified_record;",
        ),
    ]
