# Generated by Django 5.0.14 on 2026-06-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_onboarding', '0010_unifiedonboardingrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationpartnertype',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='partnerapplication',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('PENDING_DOCUMENTS', 'Pending Documents'), ('COMPLIANCE_CHECK', 'Compliance Check'), ('APPROVED', 'Approved'), ('CONVERTED', 'Converted to Partner'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=30),
        ),
    ]
