# Generated by Django 5.0.14 on 2026-08-14 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_onboarding', '0011_add_region_to_partner_type'),
        ('partners', '0010_partnertypedocumentrequirement_allow_multiple_uploads_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApplicationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SUBMITTED', 'Submitted'), ('REVIEW_STARTED', 'Review Started'), ('DOCUMENTS_REQUESTED', 'Documents Requested'), ('SENT_TO_COMPLIANCE', 'Sent to Compliance'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('RESUMED', 'Resumed'), ('CONVERTED', 'Converted'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_VERIFIED', 'Document Verified'), ('TASK_CREATED', 'Task Created'), ('TASK_COMPLETED', 'Task Completed')], db_index=True, max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'onboarding_partner_application_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='applicationfieldvalue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='applicationbankaccount',
            name='application_partner_type',
            field=models.ForeignKey(blank=True, help_text='Optional assignment scope; null means shared application bank account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='partner_onboarding.applicationpartnertype'),
        ),
        migrations.AddField(
            model_name='applicationcontact',
            name='application_partner_type',
            field=models.ForeignKey(blank=True, help_text='Optional assignment scope; null means shared application contact.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='partner_onboarding.applicationpartnertype'),
        ),
        migrations.AddField(
            model_name='applicationfieldvalue',
            name='application_partner_type',
            field=models.ForeignKey(blank=True, help_text='Optional assignment scope for this dynamic value.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='partner_onboarding.applicationpartnertype'),
        ),
        migrations.AddField(
            model_name='partnerapplicationdocument',
            name='application_partner_type',
            field=models.ForeignKey(blank=True, help_text='Optional assignment scope; null means shared application evidence.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='partner_onboarding.applicationpartnertype'),
        ),
        migrations.AddConstraint(
            model_name='applicationbankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('application',), name='uniq_onboarding_primary_bank'),
        ),
        migrations.AddConstraint(
            model_name='applicationcontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('application',), name='uniq_onboarding_primary_contact'),
        ),
        migrations.AddConstraint(
            model_name='applicationfieldvalue',
            constraint=models.UniqueConstraint(fields=('application', 'application_partner_type', 'field_config'), name='uniq_onboarding_field_value_scope'),
        ),
        migrations.AddField(
            model_name='partnerapplicationevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerapplicationevent',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='partner_onboarding.partnerapplication'),
        ),
        migrations.AddIndex(
            model_name='partnerapplicationevent',
            index=models.Index(fields=['application', '-created_at'], name='onboarding__applica_b8d213_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerapplicationevent',
            index=models.Index(fields=['event_type', '-created_at'], name='onboarding__event_t_5dd6a2_idx'),
        ),
    ]
