# Generated by Django 5.0.14 on 2026-08-16 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_onboarding', '0012_partnerapplicationevent_and_more'),
        ('partners', '0011_partner_created_by_partner_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationbankaccount',
            name='bank_requirement',
            field=models.ForeignKey(blank=True, help_text='Configured bank requirement fulfilled by this account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_bank_accounts', to='partners.partnertypebankrequirement'),
        ),
        migrations.AddField(
            model_name='applicationcontact',
            name='contact_requirement',
            field=models.ForeignKey(blank=True, help_text='Configured contact requirement fulfilled by this contact.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_contacts', to='partners.partnertypecontactrequirement'),
        ),
    ]
