# Generated by Django 5.0.14 on 2026-08-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_onboarding', '0013_applicationbankaccount_bank_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationpartnertype',
            name='kyc_status',
            field=models.CharField(choices=[('NOT_SET', 'Not Set'), ('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='NOT_SET', max_length=30),
        ),
    ]
