import { Download, FileText, Printer } from "lucide-react"
import type { MIPlanDetail, MIPlanDocument } from "../../lib/maturityInstallments"
import type { MIPrintKind } from "./MIPrintPreviewModal"

function formatDate(value: string): string {
  if (!value) return "—"
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? value : date.toLocaleString()
}

function documentLabel(documentType: string): string {
  if (documentType === "OL_MATURITY_SCHEDULE") return "Maturity Schedule"
  if (documentType === "OL_MATURITY_STATEMENT") return "Payment Statement"
  return documentType.toLowerCase().replace(/_/g, " ")
}

function documentUrl(document: MIPlanDocument): string | null {
  return document.signedDownloadUrl ?? document.previewUrl ?? document.downloadUrl ?? null
}

export function MIPlanDocumentsPanel({ plan, canPrint, onPrint, onPreview }: { plan: MIPlanDetail; canPrint: boolean; onPrint: (kind: MIPrintKind) => void; onPreview: (document: MIPlanDocument) => void }) {
  const allowedToPrint = canPrint && (plan.allowedActions ?? []).map((value) => value.toLowerCase()).includes("print")

  const download = (document: MIPlanDocument) => {
    const url = documentUrl(document)
    if (url) window.open(url, "_blank", "noopener,noreferrer")
  }

  return <section className="surface-card overflow-hidden" aria-labelledby="mi-documents-heading" data-testid="mi-documents-panel">
    <header className="flex flex-wrap items-start justify-between gap-3 border-b px-5 py-4">
      <div>
        <h2 id="mi-documents-heading" className="flex items-center gap-2 text-base font-bold"><FileText size={18} aria-hidden="true" />Documents</h2>
        <p className="mt-1 text-sm text-[var(--muted-foreground)]">Maturity schedules and payment statements generated through the document engine, retained against this plan.</p>
      </div>
      {allowedToPrint && <div className="flex flex-wrap gap-2">
        <button type="button" className="button-secondary inline-flex items-center gap-2" onClick={() => onPrint("schedule")}><Printer size={15} aria-hidden="true" />Print Schedule</button>
        <button type="button" className="button-secondary inline-flex items-center gap-2" onClick={() => onPrint("statement")}><Printer size={15} aria-hidden="true" />Print Statement</button>
      </div>}
    </header>
    <div className="p-5">
      {plan.documents.length === 0 ? <p className="py-8 text-sm text-[var(--muted-foreground)]">No generated documents yet. Use Print Schedule or Print Statement to create one.</p> : <div className="overflow-x-auto">
        <table className="w-full min-w-[820px] text-left text-sm"><caption className="sr-only">Generated maturity installment documents</caption>
          <thead><tr className="border-b text-xs uppercase tracking-wide text-[var(--muted-foreground)]"><th className="px-3 py-3">Document</th><th className="px-3 py-3">Template</th><th className="px-3 py-3">Version</th><th className="px-3 py-3">Generated by</th><th className="px-3 py-3">Generated at</th><th className="px-3 py-3">Pages</th><th className="px-3 py-3 text-right">Actions</th></tr></thead>
          <tbody>{plan.documents.map((document) => <tr key={document.id} className="border-b last:border-0 hover:bg-[var(--muted)]/35"><td className="px-3 py-3 font-semibold">{documentLabel(document.documentType)}</td><td className="px-3 py-3">{document.templateName}</td><td className="px-3 py-3">v{document.templateVersion}</td><td className="px-3 py-3">{document.generatedByDisplay}</td><td className="px-3 py-3">{formatDate(document.generatedAt)}</td><td className="px-3 py-3">{document.pageCount}</td><td className="px-3 py-3"><div className="flex flex-wrap justify-end gap-2"><button type="button" className="button-secondary inline-flex items-center gap-1" onClick={() => onPreview(document)}>Preview</button><button type="button" className="button-secondary inline-flex items-center gap-1" onClick={() => download(document)}><Download size={13} aria-hidden="true" />Download</button></div></td></tr>)}</tbody>
        </table>
      </div>}
    </div>
  </section>
}
