# Generated by Django 5.0.14 on 2026-06-30 02:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_life', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glclaiminstallment',
            name='status',
            field=models.CharField(default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='glhealthquestion',
            name='category',
            field=models.CharField(default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='glhealthquestion',
            name='question_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='glmedicalcase',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='glmedicalfacility',
            name='facility_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='glmedicalhistory',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='glmedicalhistory',
            name='risk_impact',
            field=models.CharField(default='LOW', max_length=10),
        ),
        migrations.AlterField(
            model_name='glmedicalinvoice',
            name='status',
            field=models.CharField(default='SUBMITTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='glpersonalhabit',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='glpersonalhabit',
            name='risk_level',
            field=models.CharField(default='LOW', max_length=10),
        ),
        migrations.AlterField(
            model_name='glquotation',
            name='status',
            field=models.CharField(default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='glrider',
            name='rider_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='glriderrate',
            name='gender',
            field=models.CharField(default='UNISEX', max_length=10),
        ),
        migrations.AlterField(
            model_name='glschememember',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='glschememember',
            name='uw_status',
            field=models.CharField(default='NOT_REQUIRED', max_length=20),
        ),
        migrations.AlterField(
            model_name='glschemememberdependent',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='glschemememberdependent',
            name='relationship',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='glschemepremiumrate',
            name='gender',
            field=models.CharField(default='UNISEX', max_length=10),
        ),
        migrations.AlterField(
            model_name='glschemepremiumrate',
            name='rate_type',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='GLLookupValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gl_lookup_value',
                'ordering': ['category', 'sort_order', 'label'],
                'unique_together': {('category', 'value')},
            },
        ),
    ]
