# Generated by Django 5.0.14 on 2026-06-30 02:49

import uuid
from django.db import migrations


def populate_gl_lookups(apps, schema_editor):
    GLLookupValue = apps.get_model("group_life", "GLLookupValue")

    # Hardcoded choices previously in the system
    seed_data = {
        "RATE_TYPE": [
            ("AGE_BAND", "Age Banded"),
            ("FLAT_AMOUNT", "Flat Amount"),
            ("OCCUPATION_CLASS", "Occupation Class"),
        ],
        "GENDER": [
            ("M", "Male"),
            ("F", "Female"),
            ("UNISEX", "Unisex"),
        ],
        "QUESTION_TYPE": [
            ("BOOLEAN", "Yes/No Question"),
            ("TEXT", "Free Text"),
            ("NUMBER", "Numeric Value"),
            ("MULTIPLE_CHOICE", "Multiple Choice"),
        ],
        "HEALTH_QUESTION_CATEGORY": [
            ("GENERAL", "General Health"),
            ("MEDICAL", "Medical History"),
            ("LIFESTYLE", "Lifestyle & Habits"),
            ("FAMILY", "Family History"),
        ],
        "RIDER_TYPE": [
            ("PTD", "Permanent Total Disability"),
            ("PPD", "Permanent Partial Disability"),
            ("ADD", "Accidental Death & Dismemberment"),
            ("TTD", "Temporary Total Disability"),
            ("WOP", "Waiver of Premium"),
            ("FUNERAL", "Funeral / Last Expense"),
            ("CRITICAL_ILLNESS", "Critical Illness"),
            ("RETRENCHMENT", "Retrenchment"),
        ],
        "STATUS": [
            ("DRAFT", "Draft"),
            ("ACTIVE", "Active"),
            ("EXPIRED", "Expired"),
            ("LAPSED", "Lapsed"),
            ("CANCELLED", "Cancelled"),
            ("SUSPENDED", "Suspended"),
        ],
        "UW_STATUS": [
            ("NOT_REQUIRED", "Not Required (Below FCL)"),
            ("PENDING", "Pending Requirements"),
            ("REVIEW", "Under Review"),
            ("ACCEPTED_STANDARD", "Accepted - Standard"),
            ("ACCEPTED_LOADED", "Accepted - Loaded"),
            ("DECLINED", "Declined"),
            ("POSTPONED", "Postponed"),
        ],
        "RELATIONSHIP": [
            ("SPOUSE", "Spouse"),
            ("CHILD", "Child"),
            ("PARENT", "Parent"),
            ("SIBLING", "Sibling"),
            ("OTHER", "Other"),
        ],
        "PERSONAL_HABIT_CATEGORY": [
            ("SMOKING", "Smoking"),
            ("ALCOHOL", "Alcohol Consumption"),
            ("SUBSTANCE", "Substance Use"),
            ("OTHER", "Other"),
        ],
        "RISK_LEVEL": [
            ("LOW", "Low Risk"),
            ("MEDIUM", "Medium Risk"),
            ("HIGH", "High Risk"),
            ("EXTREME", "Extreme Risk"),
        ],
        "MEDICAL_HISTORY_CATEGORY": [
            ("CARDIOVASCULAR", "Cardiovascular"),
            ("RESPIRATORY", "Respiratory"),
            ("GASTROINTESTINAL", "Gastrointestinal"),
            ("NEUROLOGICAL", "Neurological"),
            ("ENDOCRINE", "Endocrine / Metabolic"),
            ("ONCOLOGY", "Cancer / Tumors"),
            ("MUSCULOSKELETAL", "Musculoskeletal"),
            ("INFECTIOUS", "Infectious Diseases"),
            ("OTHER", "Other"),
        ],
        "RISK_IMPACT": [
            ("NONE", "No Impact"),
            ("LOW", "Low (+0-25%)"),
            ("MEDIUM", "Medium (+26-50%)"),
            ("HIGH", "High (+51-100%)"),
            ("DECLINE", "Uninsurable"),
        ],
        "FACILITY_TYPE": [
            ("HOSPITAL", "Hospital"),
            ("CLINIC", "Clinic"),
            ("LABORATORY", "Diagnostic Laboratory"),
            ("PHARMACY", "Pharmacy"),
            ("SPECIALIST", "Specialist Center"),
        ],
        "MEDICAL_CASE_STATUS": [
            ("PENDING", "Pending Action"),
            ("AWAITING_RECORDS", "Awaiting Medical Records"),
            ("AWAITING_EXAM", "Awaiting Examination"),
            ("IN_REVIEW", "In Medical Review"),
            ("REFERRED", "Referred to CMO"),
            ("DECIDED", "Decision Reached"),
            ("CLOSED", "Closed"),
        ],
        "CLAIM_INSTALLMENT_STATUS": [
            ("SCHEDULED", "Scheduled"),
            ("PROCESSING", "Processing"),
            ("PAID", "Paid"),
            ("CANCELLED", "Cancelled"),
            ("FAILED", "Failed"),
        ],
        "INVOICE_STATUS": [
            ("SUBMITTED", "Submitted"),
            ("UNDER_REVIEW", "Under Review"),
            ("APPROVED", "Approved"),
            ("REJECTED", "Rejected"),
            ("PAID", "Paid"),
        ],
    }

    instances = []
    for category, choices in seed_data.items():
        for idx, (val, lbl) in enumerate(choices):
            instances.append(
                GLLookupValue(
                    id=uuid.uuid4(),
                    category=category,
                    value=val,
                    label=lbl,
                    sort_order=idx * 10,
                    is_active=True,
                )
            )

    GLLookupValue.objects.bulk_create(instances)


class Migration(migrations.Migration):
    dependencies = [
        ("group_life", "0002_alter_glclaiminstallment_status_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_gl_lookups, reverse_code=migrations.RunPython.noop),
    ]
