# Generated by Django 5.0.14 on 2026-06-30 02:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcclaiminstallment',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='gchealthquestion',
            name='category',
            field=models.CharField(default='GENERAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='gchealthquestion',
            name='question_type',
            field=models.CharField(default='YES_NO', max_length=20),
        ),
        migrations.AlterField(
            model_name='gcmedicalcase',
            name='status',
            field=models.CharField(default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='gcmedicalfacility',
            name='facility_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gcmedicalhistory',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gcmedicalhistory',
            name='risk_impact',
            field=models.CharField(default='LOW', max_length=20),
        ),
        migrations.AlterField(
            model_name='gcmedicalinvoice',
            name='status',
            field=models.CharField(default='RECEIVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='gcpersonalhabit',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gcpersonalhabit',
            name='risk_level',
            field=models.CharField(default='LOW', max_length=20),
        ),
        migrations.AlterField(
            model_name='gcquotation',
            name='status',
            field=models.CharField(default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='gcrider',
            name='rider_type',
            field=models.CharField(default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='gcriderrate',
            name='gender',
            field=models.CharField(default='U', max_length=10),
        ),
        migrations.AlterField(
            model_name='gcschememember',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gcschememember',
            name='uw_status',
            field=models.CharField(default='NOT_REQUIRED', max_length=20),
        ),
        migrations.AlterField(
            model_name='gcschemememberdependent',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gcschemememberdependent',
            name='relationship',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gcschemepremiumrate',
            name='gender',
            field=models.CharField(default='U', max_length=10),
        ),
        migrations.AlterField(
            model_name='gcschemepremiumrate',
            name='rate_type',
            field=models.CharField(default='BASE', max_length=20),
        ),
        migrations.CreateModel(
            name='GCLookupValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, help_text='Grouping key, e.g. RATE_TYPE, GENDER', max_length=50)),
                ('value', models.CharField(help_text='Stored value / code', max_length=50)),
                ('label', models.CharField(help_text='Human-readable display label', max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'GC Lookup Values',
                'db_table': 'gc_lookup_value',
                'ordering': ['category', 'sort_order', 'label'],
                'unique_together': {('category', 'value')},
            },
        ),
    ]
