# Generated by Django 5.0.14 on 2026-06-30 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_credit', '0002_alter_gcclaiminstallment_status_and_more'),
    ]

def seed_lookup_values(apps, schema_editor):
    GCLookupValue = apps.get_model("group_credit", "GCLookupValue")
    data = {
        "RATE_TYPE": [("BASE", "Base Rate"), ("LOADING", "Loading"), ("DISCOUNT", "Discount")],
        "GENDER": [("M", "Male"), ("F", "Female"), ("U", "Unisex")],
        "QUESTION_TYPE": [("YES_NO", "Yes / No"), ("TEXT", "Text Input"), ("CHOICE", "Multiple Choice")],
        "HEALTH_QUESTION_CATEGORY": [("GENERAL", "General Health"), ("LIFESTYLE", "Lifestyle & Habits"), ("FAMILY", "Family History"), ("SPECIFIC", "Specific Conditions")],
        "RIDER_TYPE": [("PTD", "Permanent Total Disability"), ("PPD", "Permanent Partial Disability"), ("CI", "Critical Illness"), ("FE", "Funeral Expense"), ("RET", "Retrenchment"), ("OTHER", "Other")],
        "STATUS": [("DRAFT", "Draft"), ("SUBMITTED", "Submitted"), ("UNDER_REVIEW", "Under Review"), ("APPROVED", "Approved"), ("DECLINED", "Declined"), ("CONVERTED", "Converted to Scheme"), ("EXPIRED", "Expired"), ("OPEN", "Open"), ("IN_PROGRESS", "In Progress"), ("COMPLETED", "Completed"), ("CANCELLED", "Cancelled"), ("PENDING", "Pending"), ("RECEIVED", "Received")],
        "UW_STATUS": [("NOT_REQUIRED", "Not Required"), ("PENDING", "Pending UW"), ("STANDARD", "Standard"), ("LOADED", "Loaded"), ("EXCLUDED", "Exclusion"), ("DECLINED", "Declined")],
        "RELATIONSHIP": [("SPOUSE", "Spouse"), ("CHILD", "Child"), ("PARENT", "Parent"), ("OTHER", "Other")],
        "PERSONAL_HABIT_CATEGORY": [("SMOKING", "Smoking"), ("ALCOHOL", "Alcohol Consumption"), ("DRUGS", "Drug Use"), ("SPORTS", "Hazardous Sports"), ("OTHER", "Other")],
        "RISK_LEVEL": [("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
        "MEDICAL_HISTORY_CATEGORY": [("CARDIOVASCULAR", "Cardiovascular"), ("RESPIRATORY", "Respiratory"), ("NEUROLOGICAL", "Neurological"), ("ONCOLOGY", "Oncology"), ("METABOLIC", "Metabolic"), ("OTHER", "Other")],
        "RISK_IMPACT": [("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"), ("DECLINE", "Decline")],
        "FACILITY_TYPE": [("HOSPITAL", "Hospital"), ("CLINIC", "Clinic"), ("LABORATORY", "Laboratory"), ("SPECIALIST", "Specialist Center")],
    }
    
    for category, items in data.items():
        for i, (val, label) in enumerate(items):
            GCLookupValue.objects.get_or_create(
                category=category,
                value=val,
                defaults={"label": label, "sort_order": i * 10}
            )

class Migration(migrations.Migration):

    dependencies = [
        ('group_credit', '0002_alter_gcclaiminstallment_status_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_lookup_values, reverse_code=migrations.RunPython.noop),
    ]
