# Generated by Django 5.0.14 on 2026-09-01 15:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_credit', '0003_populate_gc_lookups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcschemememberstatus',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'GC Scheme Member Statuses'},
        ),
        migrations.AlterModelOptions(
            name='gcschemerenewalstatus',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'GC Scheme Renewal Statuses'},
        ),
        migrations.AlterModelOptions(
            name='gcschemestatus',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'GC Scheme Statuses'},
        ),
        migrations.AddField(
            model_name='gchealthquestion',
            name='answer_type',
            field=models.CharField(choices=[('BOOLEAN', 'Boolean'), ('TEXT', 'Text'), ('CHOICE', 'Choice')], default='BOOLEAN', max_length=20),
        ),
        migrations.AddField(
            model_name='gchealthquestion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gchealthquestion',
            name='required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gchealthquestion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gchealthquestionnaire',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gchealthquestionnaire',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gchealthquestionnaire',
            name='scheme_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questionnaires', to='group_credit.gcschemetype'),
        ),
        migrations.AddField(
            model_name='gchealthquestionnaire',
            name='threshold_trigger_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='gchealthquestionnaire',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcschemememberstatus',
            name='allows_claims',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gcschemememberstatus',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcschemememberstatus',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gcschemememberstatus',
            name='is_terminal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gcschemememberstatus',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcschemepremiumrate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcschemepremiumrate',
            name='currency',
            field=models.CharField(default='TZS', max_length=3),
        ),
        migrations.AddField(
            model_name='gcschemepremiumrate',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gcschemepremiumrate',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gcschemepremiumrate',
            name='product_ref',
            field=models.ForeignKey(blank=True, help_text='Optional product the rate is scoped to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='premium_rates', to='group_credit.gcproduct'),
        ),
        migrations.AddField(
            model_name='gcschemepremiumrate',
            name='rate_value',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='gcschemepremiumrate',
            name='scheme_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='premium_rates', to='group_credit.gcschemetype'),
        ),
        migrations.AddField(
            model_name='gcschemepremiumrate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcschemerenewalstatus',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcschemerenewalstatus',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gcschemerenewalstatus',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcschemestatus',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcschemestatus',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gcschemestatus',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcschemetype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcschemetype',
            name='partner_type_restriction',
            field=models.CharField(choices=[('BANK', 'Bank only'), ('CORPORATE', 'Corporate only'), ('BANK_AND_CORPORATE', 'Bank and corporate'), ('ANY', 'Any partner type')], default='ANY', help_text='Restrict the scheme type to a partner category (e.g. BANK only).', max_length=40),
        ),
        migrations.AddField(
            model_name='gcschemetype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gchealthquestionnaire',
            name='effective_date',
            field=models.DateField(help_text='Legacy effective date retained for compatibility.'),
        ),
        migrations.AlterField(
            model_name='gcschemepremiumrate',
            name='effective_date',
            field=models.DateField(help_text='Legacy effective date retained for compatibility.'),
        ),
        migrations.AlterField(
            model_name='gcschemepremiumrate',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Legacy expiry date retained for compatibility.', null=True),
        ),
        migrations.AlterField(
            model_name='gcschemepremiumrate',
            name='rate_type',
            field=models.CharField(default='UNIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='gcschemestatus',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Legacy ordering field retained for compatibility.'),
        ),
        migrations.AddIndex(
            model_name='gcschemepremiumrate',
            index=models.Index(fields=['scheme_type', 'rate_type', 'is_active'], name='gc_premium_rate_scheme_idx'),
        ),
    ]
