# Generated by Django 5.0.14 on 2026-09-01 15:27

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_credit', '0004_alter_gcschemememberstatus_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcsubproduct',
            options={'ordering': ['name'], 'verbose_name_plural': 'GC Sub Products'},
        ),
        migrations.AddField(
            model_name='gcproduct',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcproduct',
            name='insurance_class',
            field=models.CharField(choices=[('CREDIT_LIFE', 'Credit Life'), ('GROUP_LIFE', 'Group Life'), ('GROUP_CREDIT', 'Group Credit'), ('MEDICAL', 'Medical'), ('ASSET', 'Asset / Loan Protection'), ('OTHER', 'Other')], default='CREDIT_LIFE', max_length=30),
        ),
        migrations.AddField(
            model_name='gcproduct',
            name='max_loan_term',
            field=models.IntegerField(default=360, help_text='Maximum loan term in months.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='gcproduct',
            name='min_loan_term',
            field=models.IntegerField(default=1, help_text='Minimum loan term in months.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='gcproduct',
            name='premium_basis',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('LEVEL', 'Level')], default='SINGLE', help_text='Whether premium is collected as a single amount or as level instalments.', max_length=10),
        ),
        migrations.AddField(
            model_name='gcproduct',
            name='requires_medical',
            field=models.BooleanField(default=False, help_text='Whether medical underwriting is required for this product.'),
        ),
        migrations.AddField(
            model_name='gcproduct',
            name='scheme_type_ref',
            field=models.ForeignKey(blank=True, help_text='The scheme type this product is offered under; required at the validation layer.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='group_credit.gcschemetype'),
        ),
        migrations.AddField(
            model_name='gcproduct',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcrider',
            name='benefit_type',
            field=models.CharField(choices=[('FIXED', 'Fixed amount'), ('PERCENTAGE', 'Percentage of sum assured')], default='FIXED', max_length=12),
        ),
        migrations.AddField(
            model_name='gcrider',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcrider',
            name='requires_underwriting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gcrider',
            name='rider_category',
            field=models.CharField(choices=[('DISABILITY', 'Disability'), ('ACCIDENTAL_DEATH', 'Accidental Death'), ('CRITICAL_ILLNESS', 'Critical Illness'), ('FUNERAL', 'Funeral Expense'), ('RETRENCHMENT', 'Retrenchment'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='gcrider',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcriderrate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcriderrate',
            name='currency',
            field=models.CharField(default='TZS', max_length=10),
        ),
        migrations.AddField(
            model_name='gcriderrate',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gcriderrate',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gcriderrate',
            name='product_ref',
            field=models.ForeignKey(blank=True, help_text='Optional product scope; blank means the rider rate applies across products.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rider_rates', to='group_credit.gcproduct'),
        ),
        migrations.AddField(
            model_name='gcriderrate',
            name='rate_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage of sum assured'), ('FIXED', 'Fixed amount')], default='FIXED', max_length=12),
        ),
        migrations.AddField(
            model_name='gcriderrate',
            name='rate_value',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Canonical rate value: a percentage of sum assured, or a fixed amount.', max_digits=18),
        ),
        migrations.AddField(
            model_name='gcriderrate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcsubproduct',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcsubproduct',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gcriderrate',
            name='effective_date',
            field=models.DateField(help_text='Legacy effective date retained for compatibility.'),
        ),
        migrations.AlterField(
            model_name='gcriderrate',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Legacy expiry date retained for compatibility.', null=True),
        ),
        migrations.AlterField(
            model_name='gcriderrate',
            name='flat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Legacy flat amount retained for compatibility.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='gcriderrate',
            name='rate_per_mille',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Legacy per-mille rate retained for compatibility.', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='gcriderrate',
            index=models.Index(fields=['rider', 'product_ref'], name='gc_rider_rate_scope_idx'),
        ),
    ]
