# Generated by Django 5.0.14 on 2026-09-01 16:07

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_credit', '0005_alter_gcsubproduct_options_gcproduct_created_by_and_more'),
        ('partners', '0011_partner_created_by_partner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcclaimstatus',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'GC Claim Statuses'},
        ),
        migrations.AlterModelOptions(
            name='gcmedicalhistory',
            options={'ordering': ['condition_category', 'name'], 'verbose_name_plural': 'GC Medical Histories'},
        ),
        migrations.AlterModelOptions(
            name='gcmedicallimit',
            options={'ordering': ['scheme_type_ref', 'age_min', 'age_max']},
        ),
        migrations.AlterModelOptions(
            name='gcpersonalhabit',
            options={'ordering': ['habit_category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='gcunderwritingdecision',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='gcclaimreason',
            name='category',
            field=models.CharField(choices=[('ACCIDENT', 'Accident'), ('ILLNESS', 'Illness'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='gcclaimreason',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcclaimreason',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcclaimstatus',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcclaimstatus',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gcclaimstatus',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcclaimtype',
            name='calculation_basis',
            field=models.CharField(choices=[('SUM_ASSURED', 'Sum Assured'), ('PERCENTAGE_OF_SUM_ASSURED', 'Percentage of Sum Assured'), ('FIXED', 'Fixed Amount'), ('OTHER', 'Other')], default='SUM_ASSURED', max_length=40),
        ),
        migrations.AddField(
            model_name='gcclaimtype',
            name='category',
            field=models.CharField(choices=[('DEATH', 'Death'), ('CRITICAL_ILLNESS', 'Critical Illness'), ('PERMANENT_DISABILITY', 'Permanent Disability'), ('TEMPORARY_DISABILITY', 'Temporary Disability'), ('OTHER', 'Other')], default='DEATH', max_length=30),
        ),
        migrations.AddField(
            model_name='gcclaimtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcclaimtype',
            name='requires_document_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gcclaimtype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gccorrespondenttype',
            name='category',
            field=models.CharField(choices=[('PARTNER', 'Partner'), ('MEMBER', 'Member'), ('FAMILY', 'Family'), ('LEGAL', 'Legal Representative'), ('MEDICAL', 'Medical'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='gccorrespondenttype',
            name='communication_channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('MAIL', 'Postal Mail'), ('PHONE', 'Phone'), ('OTHER', 'Other')], default='EMAIL', max_length=20),
        ),
        migrations.AddField(
            model_name='gccorrespondenttype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gccorrespondenttype',
            name='purpose',
            field=models.CharField(choices=[('CLAIM_NOTIFICATION', 'Claim Notification'), ('DOCUMENT_REQUEST', 'Document Request'), ('PAYMENT_NOTICE', 'Payment Notice'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='gccorrespondenttype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcdischargetype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcdischargetype',
            name='template_code',
            field=models.CharField(default='DISCHARGE_DEFAULT', help_text='Document template code used to render this discharge letter.', max_length=100),
        ),
        migrations.AddField(
            model_name='gcdischargetype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcdischargetype',
            name='variables',
            field=models.JSONField(blank=True, default=dict, help_text='Template variables available for rendering.'),
        ),
        migrations.AddField(
            model_name='gcmedicalcode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcmedicalcode',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcmedicalfacility',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='gcmedicalfacility',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcmedicalfacility',
            name='partner_ref',
            field=models.ForeignKey(blank=True, help_text='Partner (bank/corporate) this facility belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gc_medical_facilities', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='gcmedicalfacility',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcmedicalhistory',
            name='condition_category',
            field=models.CharField(choices=[('CARDIOVASCULAR', 'Cardiovascular'), ('RESPIRATORY', 'Respiratory'), ('NEUROLOGICAL', 'Neurological'), ('ONCOLOGY', 'Oncology'), ('METABOLIC', 'Metabolic'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='gcmedicalhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcmedicalhistory',
            name='exclusion_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gcmedicalhistory',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='gcmedicalhistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcmedicalhistory',
            name='waiting_period_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gcmedicallimit',
            name='age_max',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='gcmedicallimit',
            name='age_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gcmedicallimit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcmedicallimit',
            name='limit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum limit amount for the condition/benefit.', max_digits=18),
        ),
        migrations.AddField(
            model_name='gcmedicallimit',
            name='medical_code_ref',
            field=models.ForeignKey(blank=True, help_text='Medical condition code this limit applies to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_limits', to='group_credit.gcmedicalcode'),
        ),
        migrations.AddField(
            model_name='gcmedicallimit',
            name='scheme_type_ref',
            field=models.ForeignKey(blank=True, help_text='Scheme context for this medical limit.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_limits', to='group_credit.gcschemetype'),
        ),
        migrations.AddField(
            model_name='gcmedicallimit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcmedicalpractitioner',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='gcmedicalpractitioner',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcmedicalpractitioner',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gcmedicalpractitioner',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gcmedicalpractitioner',
            name='partner_ref',
            field=models.ForeignKey(blank=True, help_text='Partner (bank/corporate) this practitioner is linked to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gc_medical_practitioners', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='gcmedicalpractitioner',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcpersonalhabit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcpersonalhabit',
            name='habit_category',
            field=models.CharField(choices=[('SMOKING', 'Smoking'), ('ALCOHOL', 'Alcohol Consumption'), ('DRUGS', 'Drug Use'), ('SPORTS', 'Hazardous Sports'), ('OCCUPATION', 'Occupation'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='gcpersonalhabit',
            name='underwriting_impact',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='gcpersonalhabit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcunderwritingdecision',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gcunderwritingdecision',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gcunderwritingdecision',
            name='requires_review',
            field=models.BooleanField(default=False, help_text='Whether the decision must be reviewed by senior underwriting.'),
        ),
        migrations.AddField(
            model_name='gcunderwritingdecision',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gcclaimstatus',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Legacy ordering field retained for compatibility.'),
        ),
        migrations.AlterField(
            model_name='gcclaimtype',
            name='requires_medical_report',
            field=models.BooleanField(default=False, help_text='Legacy flag retained for compatibility.'),
        ),
        migrations.AlterField(
            model_name='gcmedicalcode',
            name='category',
            field=models.CharField(choices=[('ICD_10', 'ICD-10'), ('INTERNAL', 'Internal code'), ('OTHER', 'Other')], default='ICD_10', max_length=30),
        ),
        migrations.AlterField(
            model_name='gcmedicalcode',
            name='icd10_code',
            field=models.CharField(blank=True, help_text='Legacy ICD-10 field retained for compatibility.', max_length=50),
        ),
        migrations.AlterField(
            model_name='gcmedicalfacility',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gcmedicalfacility',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gcmedicalfacility',
            name='code',
            field=models.CharField(help_text='Facility code.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gcmedicalfacility',
            name='facility_type',
            field=models.CharField(choices=[('HOSPITAL', 'Hospital'), ('CLINIC', 'Clinic'), ('LABORATORY', 'Laboratory'), ('SPECIALIST', 'Specialist Center')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gcmedicalfacility',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Legacy approval flag retained for compatibility.'),
        ),
        migrations.AlterField(
            model_name='gcmedicalhistory',
            name='category',
            field=models.CharField(blank=True, help_text='Legacy category field retained for compatibility.', max_length=50),
        ),
        migrations.AlterField(
            model_name='gcmedicalhistory',
            name='risk_impact',
            field=models.CharField(default='LOW', help_text='Legacy risk-impact field retained for compatibility.', max_length=20),
        ),
        migrations.AlterField(
            model_name='gcmedicallimit',
            name='age_from',
            field=models.IntegerField(default=0, help_text='Legacy age-from retained for compatibility.'),
        ),
        migrations.AlterField(
            model_name='gcmedicallimit',
            name='age_to',
            field=models.IntegerField(default=120, help_text='Legacy age-to retained for compatibility.'),
        ),
        migrations.AlterField(
            model_name='gcmedicallimit',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Legacy product scope retained for compatibility.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_limits', to='group_credit.gcproduct'),
        ),
        migrations.AlterField(
            model_name='gcmedicallimit',
            name='required_tests',
            field=models.JSONField(blank=True, default=list, help_text='List of required medical test codes'),
        ),
        migrations.AlterField(
            model_name='gcmedicallimit',
            name='sum_assured_from',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Legacy sum-assured bound retained for compatibility.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='gcmedicallimit',
            name='sum_assured_to',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Legacy sum-assured bound retained for compatibility.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='gcmedicalpractitioner',
            name='code',
            field=models.CharField(help_text='Practitioner code.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gcmedicalpractitioner',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Legacy approval flag retained for compatibility.'),
        ),
        migrations.AlterField(
            model_name='gcmedicalpractitioner',
            name='license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gcmedicalpractitioner',
            name='name',
            field=models.CharField(blank=True, help_text='Full name retained for compatibility.', max_length=200),
        ),
        migrations.AlterField(
            model_name='gcmedicalpractitioner',
            name='specialization',
            field=models.CharField(blank=True, help_text='Medical specialty.', max_length=100),
        ),
        migrations.AlterField(
            model_name='gcpersonalhabit',
            name='category',
            field=models.CharField(blank=True, help_text='Legacy category field retained for compatibility.', max_length=50),
        ),
        migrations.AlterField(
            model_name='gcpersonalhabit',
            name='risk_level',
            field=models.CharField(default='LOW', help_text='Legacy risk-level field retained for compatibility.', max_length=20),
        ),
        migrations.AlterField(
            model_name='gcunderwritingdecision',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Legacy ordering field retained for compatibility.'),
        ),
    ]
