# Generated by Django 5.0.14 on 2026-08-31 20:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('front_office', '0010_receipt_receipt_payment_mode_date_idx'),
        ('ol_policies', '0011_policyrider_exhausted_at_policyrider_status_and_more'),
        ('partners', '0011_partner_created_by_partner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLMaturityInstallmentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_number', models.CharField(blank=True, db_index=True, max_length=45, unique=True)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('total_maturity_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_payable_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('installment_count', models.PositiveIntegerField()),
                ('frequency', models.CharField(choices=[('SINGLE', 'Single'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half yearly'), ('ANNUAL', 'Annual')], db_index=True, default='MONTHLY', max_length=20)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated')], db_index=True, default='CREATED', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('parameter_snapshot', models.JSONField(blank=True, default=dict)),
                ('source_channel', models.CharField(choices=[('API', 'API'), ('WEB', 'Web'), ('PORTAL', 'Portal'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('BATCH', 'Batch')], db_index=True, default='API', max_length=20)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_maturity_installment_plans_activated', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_maturity_installment_plans_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('maturity_claim_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_maturity_installment_plans', to='ol_policies.maturityclaim')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ol_maturity_installment_plans', to='partners.partner')),
                ('policy_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ol_maturity_installment_plans', to='ol_policies.policy')),
                ('terminated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_maturity_installment_plans_terminated', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_maturity_installments_plan',
                'ordering': ['-created_at', 'plan_number'],
            },
        ),
        migrations.CreateModel(
            name='OLMaturityInstallmentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculation_basis', models.CharField(blank=True, default='', max_length=60)),
                ('installment_rate_snapshot', models.JSONField(blank=True, default=dict)),
                ('paid_up_rate_snapshot', models.JSONField(blank=True, default=dict)),
                ('installment_charge_snapshot', models.JSONField(blank=True, default=dict)),
                ('parameters_used', models.JSONField(blank=True, default=list)),
                ('assumptions', models.JSONField(blank=True, default=dict)),
                ('configured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_maturity_installment_configs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('plan_ref', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='config', to='ol_maturity_installments.olmaturityinstallmentplan')),
            ],
            options={
                'db_table': 'ol_maturity_installments_config',
                'ordering': ['-configured_at'],
            },
        ),
        migrations.CreateModel(
            name='OLInstallmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PAYMENT_PENDING', 'Payment pending'), ('PAID', 'Paid'), ('MISSED', 'Missed'), ('WAIVED', 'Waived')], db_index=True, default='SCHEDULED', max_length=20)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=160)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('missed_date', models.DateField(blank=True, null=True)),
                ('waived_date', models.DateField(blank=True, null=True)),
                ('narration', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_maturity_installment_items_paid', to=settings.AUTH_USER_MODEL)),
                ('payment_requisition_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_maturity_installment_items', to='front_office.forequisition')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('plan_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ol_maturity_installments.olmaturityinstallmentplan')),
            ],
            options={
                'db_table': 'ol_maturity_installments_item',
                'ordering': ['plan_ref', 'installment_number'],
            },
        ),
        migrations.AddIndex(
            model_name='olmaturityinstallmentplan',
            index=models.Index(fields=['policy_ref', 'status'], name='ol_mip_policy_status_idx'),
        ),
        migrations.AddIndex(
            model_name='olmaturityinstallmentplan',
            index=models.Index(fields=['status', 'start_date'], name='ol_mip_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='olmaturityinstallmentplan',
            index=models.Index(fields=['maturity_claim_ref'], name='ol_mip_maturity_claim_idx'),
        ),
        migrations.AddIndex(
            model_name='olmaturityinstallmentconfig',
            index=models.Index(fields=['calculation_basis'], name='ol_mip_config_basis_idx'),
        ),
        migrations.AddIndex(
            model_name='olinstallmentitem',
            index=models.Index(fields=['plan_ref', 'status'], name='ol_mip_item_plan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='olinstallmentitem',
            index=models.Index(fields=['due_date', 'status'], name='ol_mip_item_due_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='olinstallmentitem',
            constraint=models.UniqueConstraint(fields=('plan_ref', 'installment_number'), name='ol_mip_item_plan_number_uq'),
        ),
    ]
