# Generated by Django 5.0.14 on 2026-08-31 20:29

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_maturity_installments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olmaturityinstallmentplan',
            name='idempotency_fingerprint',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='olmaturityinstallmentplan',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='olmaturityinstallmentconfig',
            name='assumptions',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='olmaturityinstallmentconfig',
            name='installment_charge_snapshot',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='olmaturityinstallmentconfig',
            name='installment_rate_snapshot',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='olmaturityinstallmentconfig',
            name='paid_up_rate_snapshot',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='olmaturityinstallmentconfig',
            name='parameters_used',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='olmaturityinstallmentplan',
            name='parameter_snapshot',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
