# Generated by Django 5.0.14 on 2026-08-31 21:28

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_maturity_installments', '0002_olmaturityinstallmentplan_idempotency_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olinstallmentitem',
            name='payment_bank_details',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
