# Generated by Django 5.0.14 on 2026-09-01 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_maturity_installments', '0003_olinstallmentitem_payment_bank_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='olmaturityinstallmentplan',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olmaturityinstallmentplan',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_maturity_installment_plans_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='olmaturityinstallmentplan',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated'), ('CANCELLED', 'Cancelled')], db_index=True, default='CREATED', max_length=20),
        ),
    ]
