# Generated by Django 5.0.14 on 2026-06-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
            ],
            options={
                'verbose_name': 'Two Factor Auth',
                'verbose_name_plural': 'Two Factor Auths',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.twofactorauth',),
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
            ],
            options={
                'verbose_name': 'User OTP',
                'verbose_name_plural': 'User OTPs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.userotp',),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.usersession',),
        ),
    ]
