# Generated by Django 5.0.14 on 2026-08-22 17:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ol_parameters', '0017_olclaimtype_olclaimreason_olcorrespondenttype_and_more'),
        ('ordinary_life', '0007_oldocumentrecord_idempotency_key_and_more'),
        ('partners', '0011_partner_created_by_partner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLCommitment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commitment_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('source_type', models.CharField(choices=[('PROPOSAL', 'Proposal'), ('POLICY', 'Policy'), ('MANUAL', 'Manual')], db_index=True, max_length=20)),
                ('source_object_id', models.CharField(blank=True, default='', max_length=120)),
                ('source_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('partner_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('product_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('plan_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('premium_frequency', models.CharField(blank=True, default='', max_length=30)),
                ('installment_number', models.PositiveIntegerField(default=1)),
                ('installment_count', models.PositiveIntegerField(default=1)),
                ('due_date', models.DateField(db_index=True)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('amount_waived', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('balance', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(db_index=True, default='', max_length=60)),
                ('grace_date', models.DateField(blank=True, null=True)),
                ('warning_date', models.DateField(blank=True, null=True)),
                ('pre_lapse_date', models.DateField(blank=True, null=True)),
                ('lapse_date', models.DateField(blank=True, null=True)),
                ('approval_required', models.BooleanField(default=False)),
                ('reason_code', models.CharField(blank=True, default='', max_length=60)),
                ('reason_text', models.TextField(blank=True, default='')),
                ('source_channel', models.CharField(choices=[('WEB', 'Web'), ('API', 'API'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('IMPORT', 'Import'), ('PORTAL', 'Portal'), ('BATCH', 'Batch'), ('MANUAL', 'Manual'), ('QUICK_CREATE', 'Quick create')], default='SYSTEM', max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_commitments', to='partners.partner')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_commitments', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_commitments', to='ol_parameters.olproduct')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OL Commitment',
                'verbose_name_plural': 'OL Commitments',
                'db_table': 'ol_commitments_commitment',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OLCommitmentAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_reference', models.CharField(db_index=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_mode', models.CharField(blank=True, default='', max_length=60)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=12)),
                ('reason', models.TextField(blank=True, default='')),
                ('allocated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_channel', models.CharField(choices=[('WEB', 'Web'), ('API', 'API'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('IMPORT', 'Import'), ('PORTAL', 'Portal'), ('BATCH', 'Batch'), ('MANUAL', 'Manual'), ('QUICK_CREATE', 'Quick create')], default='SYSTEM', max_length=30)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_ol_commitments', to=settings.AUTH_USER_MODEL)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='ol_commitments.olcommitment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_allocations', to='ol_commitments.olcommitmentallocation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OL Commitment Allocation',
                'verbose_name_plural': 'OL Commitment Allocations',
                'db_table': 'ol_commitments_allocation',
                'ordering': ['-allocated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OLCommitmentNotificationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('PREMIUM_DUE', 'Premium due'), ('GRACE_START', 'Grace start'), ('GRACE_WARNING', 'Grace warning'), ('PRE_LAPSE', 'Pre-lapse'), ('LAPSE', 'Lapse')], db_index=True, max_length=30)),
                ('dispatch_on', models.DateField(db_index=True)),
                ('notification_channel', models.CharField(choices=[('SYSTEM', 'System'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PORTAL', 'Portal'), ('OTHER', 'Other')], default='SYSTEM', max_length=20)),
                ('recipient_type', models.CharField(choices=[('POLICYHOLDER', 'Policyholder'), ('AGENT', 'Agent'), ('STAFF', 'Staff'), ('PARTNER', 'Partner')], default='POLICYHOLDER', max_length=20)),
                ('recipient_identifier', models.CharField(blank=True, default='', max_length=200)),
                ('template_code', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHED', 'Dispatched'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('source_channel', models.CharField(choices=[('WEB', 'Web'), ('API', 'API'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('IMPORT', 'Import'), ('PORTAL', 'Portal'), ('BATCH', 'Batch'), ('MANUAL', 'Manual'), ('QUICK_CREATE', 'Quick create')], default='SYSTEM', max_length=30)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='ol_commitments.olcommitment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OL Commitment Notification',
                'verbose_name_plural': 'OL Commitment Notifications',
                'db_table': 'ol_commitments_notification_log',
                'ordering': ['-dispatch_on', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='olcommitment',
            index=models.Index(fields=['status', 'due_date'], name='ol_commitment_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='olcommitment',
            index=models.Index(fields=['source_type', 'status'], name='ol_commitment_src_status_idx'),
        ),
        migrations.AddIndex(
            model_name='olcommitment',
            index=models.Index(fields=['partner', 'due_date'], name='ol_commitment_partner_due_idx'),
        ),
        migrations.AddIndex(
            model_name='olcommitment',
            index=models.Index(fields=['product', 'plan', 'due_date'], name='ol_commitment_product_due_idx'),
        ),
        migrations.AddIndex(
            model_name='olcommitment',
            index=models.Index(fields=['currency', 'due_date'], name='ol_commitment_currency_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='olcommitment',
            constraint=models.CheckConstraint(check=models.Q(('premium_amount__gt', 0)), name='ol_commitment_premium_positive'),
        ),
        migrations.AddConstraint(
            model_name='olcommitment',
            constraint=models.CheckConstraint(check=models.Q(('amount_paid__gte', 0)), name='ol_commitment_amount_paid_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olcommitment',
            constraint=models.CheckConstraint(check=models.Q(('amount_waived__gte', 0)), name='ol_commitment_amount_waived_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olcommitment',
            constraint=models.CheckConstraint(check=models.Q(('installment_number__gt', 0), ('installment_count__gt', 0)), name='ol_commitment_installment_positive'),
        ),
        migrations.AddConstraint(
            model_name='olcommitment',
            constraint=models.UniqueConstraint(fields=('source_content_type', 'source_object_id', 'installment_number'), name='ol_commitment_source_installment_unique'),
        ),
        migrations.AddIndex(
            model_name='olcommitmentallocation',
            index=models.Index(fields=['receipt_reference'], name='ol_alloc_receipt_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='olcommitmentallocation',
            index=models.Index(fields=['commitment', 'allocated_at'], name='ol_alloc_commitment_idx'),
        ),
        migrations.AddConstraint(
            model_name='olcommitmentallocation',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='ol_commitment_allocation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='olcommitmentallocation',
            constraint=models.CheckConstraint(check=models.Q(('exchange_rate__gt', 0)), name='ol_commitment_allocation_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='olcommitmentallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('reversal_of__isnull', True)), fields=('commitment', 'receipt_reference'), name='ol_commitment_allocation_receipt_unique'),
        ),
        migrations.AddIndex(
            model_name='olcommitmentnotificationlog',
            index=models.Index(fields=['commitment', 'status', 'dispatch_on'], name='ol_commitment_notify_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='olcommitmentnotificationlog',
            constraint=models.UniqueConstraint(fields=('commitment', 'event_type', 'dispatch_on', 'notification_channel', 'recipient_type'), name='ol_commitment_notification_unique'),
        ),
    ]
