# Generated by Django 5.0.14 on 2026-08-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_commitments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olcommitment',
            name='lapse_review_flag',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
