# Generated by Django 5.0.14 on 2026-08-24 21:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_commitments', '0002_olcommitment_lapse_review_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='olcommitmentallocation',
            name='converted_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddConstraint(
            model_name='olcommitmentallocation',
            constraint=models.CheckConstraint(check=models.Q(('converted_amount__gte', 0)), name='ol_commitment_allocation_converted_nonnegative'),
        ),
    ]
