# Generated by Django 5.0.14 on 2026-08-14 15:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [  # type: ignore[var-annotated]
    ]

    operations = [
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=150)),
                ('aggregate_type', models.CharField(db_index=True, max_length=100)),
                ('aggregate_id', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['status', 'occurred_at'], name='common_doma_status_46f54c_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='common_doma_aggrega_e64c4e_idx')],
            },
        ),
    ]
