# Generated by Django 5.0.14 on 2026-08-19 11:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ol_quotations', '0013_preserve_print_document_provenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposal_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CONVERTED', 'Converted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('prospect_snapshot', models.JSONField(blank=True, default=dict)),
                ('plans_snapshot', models.JSONField(blank=True, default=list)),
                ('financial_summary_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ol_proposals', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='ol_quotations.olquotation')),
                ('quotation_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='ol_quotations.olquotationversion')),
            ],
            options={
                'verbose_name': 'OL Proposal',
                'verbose_name_plural': 'OL Proposals',
                'db_table': 'ol_quotation_proposal',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['quotation', 'status'], name='ol_quotatio_quotati_36b9fb_idx'), models.Index(fields=['quotation_version'], name='ol_quotatio_quotati_5287c1_idx'), models.Index(fields=['status', 'created_at'], name='ol_quotatio_status_48179b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='olproposal',
            constraint=models.UniqueConstraint(fields=('quotation', 'quotation_version'), name='ol_proposal_quotation_version_unique'),
        ),
    ]
