# Generated by Django 5.0.14 on 2026-08-23 05:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0018_olproposalstatus_and_more'),
        ('ol_proposals', '0001_initial_proposal_model'),
        ('ol_quotations', '0013_preserve_print_document_provenance'),
        ('ordinary_life', '0007_oldocumentrecord_idempotency_key_and_more'),
        ('partners', '0011_partner_created_by_partner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLProposalBeneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=255)),
                ('identity_type', models.CharField(blank=True, default='', max_length=80)),
                ('identity_number', models.CharField(blank=True, default='', max_length=120)),
                ('beneficial_type_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('share_percent', models.DecimalField(decimal_places=4, max_digits=7)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_minor', models.BooleanField(default=False)),
                ('guardian_name', models.CharField(blank=True, default='', max_length=255)),
                ('guardian_identity_type', models.CharField(blank=True, default='', max_length=80)),
                ('guardian_identity_number', models.CharField(blank=True, default='', max_length=120)),
                ('guardian_relationship', models.CharField(blank=True, default='', max_length=80)),
            ],
            options={
                'db_table': 'ol_proposal_beneficiary',
                'ordering': ['proposal', '-is_primary', 'person_name'],
            },
        ),
        migrations.CreateModel(
            name='OLProposalBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('benefit_type', models.CharField(blank=True, default='', max_length=80)),
                ('basis', models.CharField(default='FIXED', max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('loading', models.DecimalField(decimal_places=4, default='0', max_digits=9)),
                ('discount', models.DecimalField(decimal_places=4, default='0', max_digits=9)),
                ('maximum_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sum_assured', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('is_selected', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_proposal_benefit',
                'ordering': ['proposal', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLProposalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(db_index=True, max_length=120)),
                ('file_reference', models.CharField(blank=True, default='', max_length=500)),
                ('mandatory', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('UPLOADED', 'Uploaded'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='REQUESTED', max_length=30)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ol_proposal_document',
                'ordering': ['proposal', 'document_type'],
            },
        ),
        migrations.CreateModel(
            name='OLProposalFundAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fund_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('allocation_percentage', models.DecimalField(decimal_places=4, max_digits=7)),
                ('allocation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('is_selected', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_proposal_fund_allocation',
                'ordering': ['proposal', 'fund__code'],
            },
        ),
        migrations.CreateModel(
            name='OLProposalHealthAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.JSONField(blank=True, default=dict)),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('triggers_medical', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ol_proposal_health_answer',
                'ordering': ['proposal', 'answered_at'],
            },
        ),
        migrations.CreateModel(
            name='OLProposalInstallmentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(max_length=40)),
                ('annuity_period_years', models.PositiveSmallIntegerField(default=1)),
                ('number_of_installments', models.PositiveIntegerField(default=1)),
                ('after_maturity_benefits', models.BooleanField(default=False)),
                ('before_maturity_benefits', models.BooleanField(default=False)),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('first_due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('is_selected', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_proposal_installment_config',
                'ordering': ['proposal', 'frequency'],
            },
        ),
        migrations.CreateModel(
            name='OLProposalInstallmentRateRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('period_from', models.PositiveIntegerField()),
                ('period_to', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('rate_percent', models.DecimalField(decimal_places=4, default='0', max_digits=7)),
                ('rate', models.DecimalField(decimal_places=8, default='0', max_digits=18)),
                ('charge', models.DecimalField(decimal_places=2, default='0', max_digits=18)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'ol_proposal_installment_rate_row',
                'ordering': ['installment_config', 'period_from'],
            },
        ),
        migrations.CreateModel(
            name='OLProposalMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_type', models.CharField(choices=[('POLICYHOLDER', 'Policyholder'), ('LIFE_ASSURED', 'Life assured'), ('DEPENDENT', 'Dependent'), ('OTHER', 'Other')], max_length=30)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('full_name_snapshot', models.CharField(blank=True, default='', max_length=300)),
                ('identity_number', models.CharField(blank=True, default='', max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age_at_quote', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=40)),
                ('smoker_status', models.CharField(blank=True, default='', max_length=40)),
                ('relationship', models.CharField(blank=True, default='', max_length=80)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=40)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('member_sum_assured', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('coverage_basis', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'ol_proposal_member',
                'ordering': ['proposal', 'member_type', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='OLProposalPlanConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('sub_product_code', models.CharField(blank=True, default='', max_length=80)),
                ('section_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('base_sum_assured', models.DecimalField(decimal_places=2, max_digits=18)),
                ('term_years', models.PositiveSmallIntegerField()),
                ('payment_period_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('premium_frequency', models.CharField(max_length=40)),
                ('quote_basis', models.CharField(default='SUM_ASSURED', max_length=80)),
                ('estimated_maturity_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('premium_factor', models.CharField(default='NONE', max_length=80)),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('is_selected', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_proposal_plan_config',
                'ordering': ['proposal', '-is_selected', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OLProposalRider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rider_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('rider_sum_assured', models.DecimalField(decimal_places=2, max_digits=18)),
                ('rider_term_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('benefit_basis', models.CharField(default='FIXED', max_length=20)),
                ('benefit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('loading', models.DecimalField(decimal_places=4, default='0', max_digits=9)),
                ('discount', models.DecimalField(decimal_places=4, default='0', max_digits=9)),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('is_selected', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_proposal_rider',
                'ordering': ['proposal', 'rider__code'],
            },
        ),
        migrations.AddField(
            model_name='olproposal',
            name='agent_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='agent_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_proposals_agent', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='converted_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_proposals_converted', to='ordinary_life.olpolicy'),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='currency',
            field=models.CharField(default='TZS', max_length=3),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='employer_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='employer_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_proposals_employer', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='medical_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_proposals_policyholder', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='partner_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='payment_ready',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='payment_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='reason_code',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='reason_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='source_channel',
            field=models.CharField(choices=[('WEB', 'Web'), ('API', 'API'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('IMPORT', 'Import'), ('PORTAL', 'Portal'), ('BATCH', 'Batch'), ('QUICK_CREATE', 'Quick create')], default='WEB', max_length=30),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='underwriting_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MEDICAL_REQUIRED', 'Medical required'), ('UNDER_REVIEW', 'Under review'), ('CLEARED', 'Cleared'), ('DECLINED', 'Declined')], db_index=True, default='PENDING', max_length=40),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ol_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='olproposal',
            name='status',
            field=models.CharField(db_index=True, default='DRAFT', max_length=40),
        ),
        migrations.AddIndex(
            model_name='olproposal',
            index=models.Index(fields=['partner', 'status'], name='ol_quotatio_partner_e96408_idx'),
        ),
        migrations.AddIndex(
            model_name='olproposal',
            index=models.Index(fields=['payment_ready', 'status'], name='ol_quotatio_payment_6ef908_idx'),
        ),
        migrations.AddField(
            model_name='olproposalbeneficiary',
            name='beneficial_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_proposal_beneficiaries', to='ol_parameters.olbeneficialtype'),
        ),
        migrations.AddField(
            model_name='olproposalbeneficiary',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='ol_proposals.olproposal'),
        ),
        migrations.AddField(
            model_name='olproposalbenefit',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='ol_proposals.olproposal'),
        ),
        migrations.AddField(
            model_name='olproposaldocument',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ol_proposals.olproposal'),
        ),
        migrations.AddField(
            model_name='olproposaldocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_ol_proposal_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='olproposalfundallocation',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_allocations', to='ol_parameters.olinvestmentfund'),
        ),
        migrations.AddField(
            model_name='olproposalfundallocation',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_allocations', to='ol_proposals.olproposal'),
        ),
        migrations.AddField(
            model_name='olproposalhealthanswer',
            name='health_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ol_proposal_health_answers', to='ol_parameters.olhealthquestion'),
        ),
        migrations.AddField(
            model_name='olproposalhealthanswer',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_answers', to='ol_proposals.olproposal'),
        ),
        migrations.AddField(
            model_name='olproposalhealthanswer',
            name='questionnaire_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_proposal_health_answers', to='ol_parameters.olhealthquestionnaireitem'),
        ),
        migrations.AddField(
            model_name='olproposalinstallmentconfig',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_configs', to='ol_proposals.olproposal'),
        ),
        migrations.AddField(
            model_name='olproposalinstallmentraterow',
            name='installment_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_rows', to='ol_proposals.olproposalinstallmentconfig'),
        ),
        migrations.AddField(
            model_name='olproposalmember',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_proposal_members', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='olproposalmember',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ol_proposals.olproposal'),
        ),
        migrations.AddField(
            model_name='olproposalplanconfig',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposal_plan_configs', to='ordinary_life.olplan'),
        ),
        migrations.AddField(
            model_name='olproposalplanconfig',
            name='product_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposal_plan_configs', to='ordinary_life.olproductversion'),
        ),
        migrations.AddField(
            model_name='olproposalplanconfig',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_configs', to='ol_proposals.olproposal'),
        ),
        migrations.AddField(
            model_name='olproposalinstallmentconfig',
            name='plan_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installment_configs', to='ol_proposals.olproposalplanconfig'),
        ),
        migrations.AddField(
            model_name='olproposalfundallocation',
            name='plan_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_allocations', to='ol_proposals.olproposalplanconfig'),
        ),
        migrations.AddField(
            model_name='olproposalbenefit',
            name='plan_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='ol_proposals.olproposalplanconfig'),
        ),
        migrations.AddField(
            model_name='olproposalrider',
            name='beneficial_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_proposal_riders', to='ol_parameters.olbeneficialtype'),
        ),
        migrations.AddField(
            model_name='olproposalrider',
            name='plan_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riders', to='ol_proposals.olproposalplanconfig'),
        ),
        migrations.AddField(
            model_name='olproposalrider',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riders', to='ol_proposals.olproposal'),
        ),
        migrations.AddField(
            model_name='olproposalrider',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_riders', to='ol_parameters.olridersetup'),
        ),
        migrations.AddConstraint(
            model_name='olproposalbeneficiary',
            constraint=models.CheckConstraint(check=models.Q(('share_percent__gt', 0), ('share_percent__lte', 100)), name='ol_proposal_beneficiary_share_range'),
        ),
        migrations.AddIndex(
            model_name='olproposalhealthanswer',
            index=models.Index(fields=['proposal', 'triggers_medical'], name='ol_proposal_proposa_e82984_idx'),
        ),
        migrations.AddConstraint(
            model_name='olproposalinstallmentraterow',
            constraint=models.CheckConstraint(check=models.Q(('period_from__gt', 0), ('period_to__gte', models.F('period_from'))), name='ol_proposal_installment_rate_period_valid'),
        ),
        migrations.AddIndex(
            model_name='olproposalmember',
            index=models.Index(fields=['proposal', 'member_type'], name='ol_proposal_proposa_718ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='olproposalplanconfig',
            index=models.Index(fields=['proposal', 'is_selected'], name='ol_proposal_proposa_28fc75_idx'),
        ),
        migrations.AddIndex(
            model_name='olproposalinstallmentconfig',
            index=models.Index(fields=['proposal', 'is_selected', 'frequency'], name='ol_proposal_proposa_393946_idx'),
        ),
        migrations.AddConstraint(
            model_name='olproposalfundallocation',
            constraint=models.CheckConstraint(check=models.Q(('allocation_percentage__gte', 0), ('allocation_percentage__lte', 100)), name='ol_proposal_fund_percentage_range'),
        ),
    ]
