# Generated by Django 5.0.14 on 2026-08-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_proposals', '0002_olproposalbeneficiary_olproposalbenefit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olproposal',
            name='status',
            field=models.CharField(db_index=True, default='', max_length=40),
        ),
    ]
