# Generated by Django 5.0.14 on 2026-08-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_proposals', '0003_alter_olproposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='olproposal',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='declaration_aml_flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='declaration_pep_flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='declarations_free_text',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='employment_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='existing_policies_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='intermediary_channel',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='occupation_risk_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='payroll_deduction',
            field=models.BooleanField(default=False),
        ),
    ]
