# Generated by Django 5.0.14 on 2026-08-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_proposals', '0004_olproposal_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olproposal',
            name='declaration_aml_flag',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='olproposal',
            name='declaration_pep_flag',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
