# Generated by Django 5.0.14 on 2026-08-23 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_commitments', '0002_olcommitment_lapse_review_flag'),
        ('ol_proposals', '0005_alter_olproposal_declaration_aml_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olproposal',
            name='first_premium_commitment',
            field=models.ForeignKey(blank=True, help_text='Linked first-premium commitment (source_type=PROPOSAL, installment 1).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_first_premiums', to='ol_commitments.olcommitment'),
        ),
    ]
