# Generated by Django 5.0.14 on 2026-08-23 09:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_proposals', '0006_olproposal_first_premium_commitment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='olproposaldocument',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olproposaldocument',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_ol_proposal_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='olproposaldocument',
            name='html_reference',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='olproposaldocument',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='olproposaldocument',
            name='mime_type',
            field=models.CharField(default='application/pdf', max_length=120),
        ),
        migrations.AddField(
            model_name='olproposaldocument',
            name='template_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='olproposaldocument',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('UPLOADED', 'Uploaded'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('GENERATED', 'Generated')], db_index=True, default='REQUESTED', max_length=30),
        ),
        migrations.CreateModel(
            name='OLProposalPrintTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, default='')),
                ('template_html', models.TextField()),
                ('layout_variables', models.JSONField(blank=True, default=dict)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ol_proposal_print_template',
                'ordering': ['code', '-version'],
                'indexes': [models.Index(fields=['code', 'is_active', 'effective_from', 'effective_to'], name='ol_prop_print_tpl_active_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='olproposalprinttemplate',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='ol_proposal_print_template_code_version_uq'),
        ),
        migrations.AddField(
            model_name='olproposaldocument',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='ol_proposals.olproposalprinttemplate'),
        ),
        migrations.AddIndex(
            model_name='olproposaldocument',
            index=models.Index(fields=['proposal', 'document_type', 'status'], name='ol_prop_doc_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='olproposaldocument',
            index=models.Index(fields=['proposal', 'template_version'], name='ol_prop_doc_tpl_ver_idx'),
        ),
    ]
