# Generated by Django 5.0.14 on 2026-08-23 09:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_proposals', '0007_olproposaldocument_generated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OLProposalNotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=150)),
                ('dispatch_on', models.DateField(blank=True, db_index=True, null=True)),
                ('notification_channel', models.CharField(choices=[('SYSTEM', 'System'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PORTAL', 'Portal'), ('OTHER', 'Other')], default='SYSTEM', max_length=30)),
                ('recipient_type', models.CharField(choices=[('POLICYHOLDER', 'Policyholder'), ('AGENT', 'Agent'), ('STAFF', 'Staff'), ('PARTNER', 'Partner')], default='STAFF', max_length=30)),
                ('recipient_identifier', models.CharField(blank=True, default='', max_length=200)),
                ('template_code', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHED', 'Dispatched'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('source_channel', models.CharField(choices=[('WEB', 'Web'), ('API', 'API'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('IMPORT', 'Import'), ('PORTAL', 'Portal'), ('BATCH', 'Batch'), ('QUICK_CREATE', 'Quick create')], default='SYSTEM', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='ol_proposals.olproposal')),
            ],
            options={
                'db_table': 'ol_proposal_notification_log',
                'ordering': ['-dispatch_on', '-created_at'],
                'indexes': [models.Index(fields=['proposal', 'status', 'dispatch_on'], name='ol_prop_notify_state_idx'), models.Index(fields=['event_type', 'dispatch_on'], name='ol_prop_notify_type_date_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='olproposalnotificationlog',
            constraint=models.UniqueConstraint(fields=('proposal', 'event_type', 'dispatch_on', 'notification_channel', 'recipient_type'), name='ol_proposal_notification_unique'),
        ),
        migrations.AddConstraint(
            model_name='olproposalnotificationlog',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['PENDING', 'DISPATCHED', 'FAILED', 'SKIPPED'])), name='ol_proposal_notify_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='olproposalnotificationlog',
            constraint=models.CheckConstraint(check=models.Q(('notification_channel__in', ['SYSTEM', 'EMAIL', 'SMS', 'PORTAL', 'OTHER'])), name='ol_proposal_notify_channel_valid'),
        ),
    ]
