# Generated by Django 5.0.14 on 2026-08-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_proposals', '0008_olproposalnotificationlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olproposal',
            name='policy_ref',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
