from django.urls import path

from apps.front_office.receipts.views import (
    ExchangeRateView,
    PartnerPortalReceiptDetailView,
    PartnerPortalReceiptListView,
    ReceiptAllocateView,
    ReceiptAllocationOptionsView,
    ReceiptAllocationReverseView,
    ReceiptAllocationsView,
    ReceiptAuditTimelineView,
    ReceiptAutoAllocateView,
    ReceiptBankAccountView,
    ReceiptCancelView,
    ReceiptDetailView,
    ReceiptDocumentDownloadView,
    ReceiptDocumentsView,
    ReceiptExportView,
    ReceiptImportBatchDetailView,
    ReceiptImportBatchListView,
    ReceiptImportCommitView,
    ReceiptImportDryRunView,
    ReceiptImportReprocessView,
    ReceiptImportTemplateView,
    ReceiptKpisView,
    ReceiptListView,
    ReceiptOptionsResourceView,
    ReceiptOptionsView,
    ReceiptPostView,
    ReceiptPrintView,
    ReceiptReportingDatasetView,
    ReceiptReversalsView,
    ReceiptReverseView,
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="receipts-list"),
    path("kpis/", ReceiptKpisView.as_view(), name="receipts-kpis"),
    path("export/", ReceiptExportView.as_view(), name="receipts-export"),
    path("options/", ReceiptOptionsView.as_view(), name="receipts-options"),
    path("options/<str:resource>/quick-create-schema/", ReceiptOptionsResourceView.as_view(), name="receipts-options-resource-schema"),
    path("options/<str:resource>/quick-create/", ReceiptOptionsResourceView.as_view(), name="receipts-options-resource-create"),
    path("options/<str:resource>/", ReceiptOptionsResourceView.as_view(), name="receipts-options-resource"),
    path("exchange-rate/", ExchangeRateView.as_view(), name="receipts-exchange-rate"),
    path("reporting/dataset/", ReceiptReportingDatasetView.as_view(), name="receipts-reporting-dataset"),
    path("portal/", PartnerPortalReceiptListView.as_view(), name="receipts-portal-list"),
    path("portal/<uuid:receipt_id>/", PartnerPortalReceiptDetailView.as_view(), name="receipts-portal-detail"),
    path("import/template/", ReceiptImportTemplateView.as_view(), name="receipts-import-template"),
    path("import/dry-run/", ReceiptImportDryRunView.as_view(), name="receipts-import-dry-run"),
    path("import/commit/", ReceiptImportCommitView.as_view(), name="receipts-import-commit"),
    path("imports/", ReceiptImportBatchListView.as_view(), name="receipts-import-batches"),
    path("imports/<uuid:batch_id>/", ReceiptImportBatchDetailView.as_view(), name="receipts-import-batch-detail"),
    path("imports/<uuid:batch_id>/reprocess/", ReceiptImportReprocessView.as_view(), name="receipts-import-reprocess"),
    path("documents/<uuid:document_id>/download/", ReceiptDocumentDownloadView.as_view(), name="receipts-document-download"),
    path("<uuid:receipt_id>/allocations/", ReceiptAllocationsView.as_view(), name="receipts-allocations"),
    path("<uuid:receipt_id>/reversals/", ReceiptReversalsView.as_view(), name="receipts-reversals"),
    path("<uuid:receipt_id>/audit-timeline/", ReceiptAuditTimelineView.as_view(), name="receipts-audit-timeline"),
    path("<uuid:receipt_id>/bank-account/", ReceiptBankAccountView.as_view(), name="receipts-bank-account"),
    path("<uuid:receipt_id>/allocation-options/", ReceiptAllocationOptionsView.as_view(), name="receipts-allocation-options"),
    path("<uuid:receipt_id>/allocate/", ReceiptAllocateView.as_view(), name="receipts-allocate"),
    path("<uuid:receipt_id>/auto-allocate/", ReceiptAutoAllocateView.as_view(), name="receipts-auto-allocate"),
    path("<uuid:receipt_id>/reverse/", ReceiptReverseView.as_view(), name="receipts-reverse"),
    path("<uuid:receipt_id>/allocations/<uuid:allocation_id>/reverse/", ReceiptAllocationReverseView.as_view(), name="receipts-allocation-reverse"),
    path("<uuid:receipt_id>/cancel/", ReceiptCancelView.as_view(), name="receipts-cancel"),
    path("<uuid:receipt_id>/post/", ReceiptPostView.as_view(), name="receipts-post"),
    path("<uuid:receipt_id>/print/", ReceiptPrintView.as_view(), name="receipts-print"),
    path("<uuid:receipt_id>/documents/", ReceiptDocumentsView.as_view(), name="receipts-documents"),
    path("<uuid:receipt_id>/", ReceiptDetailView.as_view(), name="receipts-detail"),
]
