# Generated by Django 5.0.14 on 2026-08-14 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('target_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_pairs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['base_currency', 'quote_currency'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('provider', models.CharField(default='frankfurter', max_length=80)),
                ('as_of', models.DateField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='dashboard.currencypair')),
            ],
            options={
                'ordering': ['-as_of', '-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('DISMISSED', 'Dismissed')], db_index=True, default='OPEN', max_length=20)),
                ('route', models.CharField(blank=True, max_length=255)),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_dashboard_alerts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_key', models.CharField(max_length=180)),
                ('kind', models.CharField(default='SYSTEM', max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=80)),
                ('route', models.CharField(blank=True, max_length=255)),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('TODO', 'To do'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done'), ('ARCHIVED', 'Archived')], db_index=True, default='TODO', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('route', models.CharField(blank=True, max_length=255)),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dashboard_tasks', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'due_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='currencypair',
            constraint=models.UniqueConstraint(fields=('owner', 'base_currency', 'quote_currency'), name='currency_pair_owner_currencies_unique'),
        ),
        migrations.AddIndex(
            model_name='currencyrate',
            index=models.Index(fields=['pair', 'as_of'], name='dashboard_c_pair_id_22bece_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardalert',
            index=models.Index(fields=['owner', 'status'], name='dashboard_d_owner_i_8e715a_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardalert',
            index=models.Index(fields=['owner', 'severity'], name='dashboard_d_owner_i_711d02_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardnotification',
            index=models.Index(fields=['owner', 'is_read', 'created_at'], name='dashboard_d_owner_i_8b0027_idx'),
        ),
        migrations.AddConstraint(
            model_name='dashboardnotification',
            constraint=models.UniqueConstraint(fields=('owner', 'external_key'), name='dashboard_notification_owner_key_unique'),
        ),
        migrations.AddIndex(
            model_name='dashboardtask',
            index=models.Index(fields=['owner', 'status'], name='dashboard_d_owner_i_2dd2b8_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardtask',
            index=models.Index(fields=['owner', 'due_at'], name='dashboard_d_owner_i_0f53b8_idx'),
        ),
    ]
