# Generated by Django 5.0.14 on 2026-08-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_seed_user_management_rbac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('PORTAL_USER', 'Portal User'), ('MANAGER', 'Manager'), ('QUOTATION_ONLY', 'Quotation Only'), ('UNDERWRITER', 'Underwriter'), ('SYSTEM_MANAGER', 'System Manager'), ('ZIC_GROUP', 'ZIC Group'), ('SUPER_ADMIN', 'Super Admin')], default='PORTAL_USER', max_length=30),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(choices=[('PORTAL_USER', 'Portal User'), ('MANAGER', 'Manager'), ('QUOTATION_ONLY', 'Quotation Only'), ('UNDERWRITER', 'Underwriter'), ('SYSTEM_MANAGER', 'System Manager'), ('ZIC_GROUP', 'ZIC Group'), ('SUPER_ADMIN', 'Super Admin')], max_length=30, unique=True),
        ),
    ]
