# Generated by Django 5.0.14 on 2026-08-14 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_group_codes_and_flags(apps, schema_editor):
    UserGroup = apps.get_model('users', 'UserGroup')
    UserPermission = apps.get_model('users', 'UserPermission')
    system_names = {
        'PORTAL_USER', 'MANAGER', 'QUOTATION_ONLY', 'UNDERWRITER',
        'SYSTEM_MANAGER', 'ZIC_GROUP', 'SUPER_ADMIN',
    }
    for group in UserGroup.objects.all().iterator():
        group.code = (group.code or group.name).upper().replace(' ', '_')
        group.is_system = bool(group.is_system or group.is_system_group or group.name in system_names)
        group.is_system_group = group.is_system
        group.save(update_fields=['code', 'is_system', 'is_system_group'])
    for permission in UserPermission.objects.all().iterator():
        if not permission.description:
            permission.description = permission.name
            permission.save(update_fields=['description'])


def reverse_group_codes_and_flags(apps, schema_editor):
    UserGroup = apps.get_model('users', 'UserGroup')
    UserGroup.objects.update(code=None, is_system=False)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_created_by_user_last_password_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpermission',
            options={'ordering': ['module', 'action', 'name'], 'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='group_type',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('PARTNER', 'Partner'), ('ADMINISTRATIVE', 'Administrative'), ('AUDIT', 'Audit')], db_index=True, default='INTERNAL', max_length=20),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='is_system',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='action',
            field=models.CharField(choices=[('VIEW', 'View'), ('READ', 'Read'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('CONFIGURE', 'Configure'), ('EXPORT', 'Export'), ('PRINT', 'Print'), ('REVERSE', 'Reverse'), ('SETTLE', 'Settle'), ('ASSIGN', 'Assign'), ('ADMINISTER', 'Administer'), ('MANAGE', 'Manage'), ('REVIEW', 'Review'), ('COMPLIANCE', 'Compliance'), ('ASSESS', 'Assess'), ('CONVERT', 'Convert'), ('BULK_IMPORT', 'Bulk import'), ('SUSPEND', 'Suspend')], default='READ', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='codename',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AddConstraint(
            model_name='userpermission',
            constraint=models.UniqueConstraint(fields=('module', 'action', 'resource_type'), name='users_permission_module_action_resource_uniq'),
        ),
        migrations.RunPython(backfill_group_codes_and_flags, reverse_group_codes_and_flags),
    ]
