# Generated by Django 5.0.14 on 2026-08-14 17:09

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_seed_zic_permission_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('business_area', models.CharField(db_index=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_system', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Category',
                'verbose_name_plural': 'Report Categories',
                'ordering': ['business_area', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserGroupReportCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_report_categories', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_category_assignments', to='users.usergroup')),
                ('report_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_assignments', to='users.reportcategory')),
            ],
            options={
                'verbose_name': 'Group Report Category Assignment',
                'verbose_name_plural': 'Group Report Category Assignments',
            },
        ),
        migrations.AddField(
            model_name='usergroup',
            name='report_categories',
            field=models.ManyToManyField(blank=True, related_name='groups', through='users.UserGroupReportCategory', to='users.reportcategory'),
        ),
        migrations.AddIndex(
            model_name='usergroupreportcategory',
            index=models.Index(fields=['group', 'report_category'], name='users_userg_group_i_f27318_idx'),
        ),
        migrations.AddIndex(
            model_name='usergroupreportcategory',
            index=models.Index(fields=['report_category', 'group'], name='users_userg_report__f0f7ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='usergroupreportcategory',
            constraint=models.UniqueConstraint(fields=('group', 'report_category'), name='users_group_report_category_unique'),
        ),
    ]
