# Generated by Django 5.0.14 on 2026-08-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_seed_report_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='action',
            field=models.CharField(choices=[('VIEW', 'View'), ('READ', 'Read'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('DEACTIVATE', 'Deactivate'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('CONFIGURE', 'Configure'), ('EXPORT', 'Export'), ('PRINT', 'Print'), ('REVERSE', 'Reverse'), ('SETTLE', 'Settle'), ('ASSIGN', 'Assign'), ('ADMINISTER', 'Administer'), ('MANAGE', 'Manage'), ('REVIEW', 'Review'), ('COMPLIANCE', 'Compliance'), ('ASSESS', 'Assess'), ('CONVERT', 'Convert'), ('BULK_IMPORT', 'Bulk import'), ('SUSPEND', 'Suspend')], default='READ', max_length=20),
        ),
    ]
