# Generated by Django 5.0.14 on 2026-06-22 12:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(db_index=True, max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('entity_repr', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(max_length=30)),
                ('requested_data', models.JSONField(blank=True, null=True)),
                ('current_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_approvals', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Request',
                'verbose_name_plural': 'Approval Requests',
                'db_table': 'governance_approval_request',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['module', 'status'], name='governance__module_36e6d5_idx'), models.Index(fields=['entity_type', 'entity_id'], name='governance__entity__1bb0d5_idx'), models.Index(fields=['submitted_by', '-submitted_at'], name='governance__submitt_a1cf6c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('SUBMIT', 'Submit'), ('ACTIVATE', 'Activate'), ('DEACTIVATE', 'Deactivate'), ('ASSIGN', 'Assign'), ('UNASSIGN', 'Unassign'), ('UPLOAD', 'Upload'), ('DOWNLOAD', 'Download'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VERIFY', 'Verify'), ('ESCALATE', 'Escalate'), ('RENEW', 'Renew'), ('EXPIRE', 'Expire')], db_index=True, max_length=30)),
                ('entity_type', models.CharField(db_index=True, max_length=100)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('entity_repr', models.CharField(blank=True, max_length=255)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('request_id', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'governance_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='governance__entity__9f1f1f_idx'), models.Index(fields=['user', '-timestamp'], name='governance__user_id_d6d5c4_idx'), models.Index(fields=['action_type', '-timestamp'], name='governance__action__c4f3a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(db_index=True, max_length=100)),
                ('version_number', models.PositiveIntegerField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], db_index=True, default='DRAFT', max_length=20)),
                ('configuration_data', models.JSONField(blank=True, default=dict)),
                ('change_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_config_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration Version',
                'verbose_name_plural': 'Configuration Versions',
                'db_table': 'governance_configuration_version',
                'ordering': ['module', '-version_number'],
                'indexes': [models.Index(fields=['module', 'status'], name='governance__module_ca987d_idx'), models.Index(fields=['effective_from', 'effective_to'], name='governance__effecti_e307cc_idx')],
                'unique_together': {('module', 'version_number')},
            },
        ),
    ]
