# Generated by Django 5.0.14 on 2026-08-18 21:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ol_parameters', '0017_olclaimtype_olclaimreason_olcorrespondenttype_and_more'),
        ('ordinary_life', '0007_oldocumentrecord_idempotency_key_and_more'),
        ('partners', '0011_partner_created_by_partner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLQuotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('quote_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('CONVERTED', 'Converted'), ('EXPIRED', 'Expired')], db_index=True, default='DRAFT', max_length=20)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('total_sum_assured', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('calculation_snapshot', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ol_quotations_v2', to='partners.partner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='ol_parameters.olproduct')),
                ('product_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parameter_quotations', to='ordinary_life.olproductversion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_quotation_header',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OLQuotationBeneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=4, max_digits=7)),
                ('identity_number', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_quotation_beneficiaries', to='partners.partner')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='ol_quotations.olquotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_quotation_beneficiary',
                'ordering': ['quotation', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OLQuotationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=80)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_quotation_events', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ol_quotations.olquotation')),
            ],
            options={
                'db_table': 'ol_quotation_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OLQuotationFundAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation_percentage', models.DecimalField(decimal_places=4, max_digits=7)),
                ('allocation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('is_selected', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_allocations', to='ol_parameters.olinvestmentfund')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_allocations', to='ol_quotations.olquotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_quotation_fund_allocation',
                'ordering': ['quotation', 'fund__code'],
            },
        ),
        migrations.CreateModel(
            name='OLQuotationInstallmentConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(max_length=40)),
                ('number_of_installments', models.PositiveIntegerField(default=1)),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('first_due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('is_selected', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_configurations', to='ol_quotations.olquotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_quotation_installment_configuration',
                'ordering': ['quotation', 'frequency'],
            },
        ),
        migrations.CreateModel(
            name='OLQuotationInstallmentRateRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_from', models.PositiveIntegerField()),
                ('period_to', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('charge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('installment_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_rows', to='ol_quotations.olquotationinstallmentconfiguration')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_quotation_installment_rate_row',
                'ordering': ['installment_configuration', 'period_from'],
            },
        ),
        migrations.CreateModel(
            name='OLQuotationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_type', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('identity_number', models.CharField(blank=True, max_length=120)),
                ('date_of_birth', models.DateField()),
                ('age_at_quote', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=40)),
                ('smoker_status', models.CharField(blank=True, max_length=40)),
                ('relationship', models.CharField(blank=True, max_length=80)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('member_sum_assured', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_quotation_members', to='partners.partner')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ol_quotations.olquotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_quotation_member',
                'ordering': ['quotation', 'member_type', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='OLQuotationPaymentDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('account_reference', models.CharField(blank=True, max_length=150)),
                ('payment_reference', models.CharField(blank=True, max_length=150)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_quotation_payment_details', to='partners.partner')),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail', to='ol_quotations.olquotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_quotation_payment_detail',
            },
        ),
        migrations.CreateModel(
            name='OLQuotationPlanConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_product_code', models.CharField(blank=True, max_length=80)),
                ('is_selected', models.BooleanField(default=True)),
                ('base_sum_assured', models.DecimalField(decimal_places=2, max_digits=18)),
                ('term_years', models.PositiveSmallIntegerField()),
                ('premium_frequency', models.CharField(max_length=40)),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('coverage_rules', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_plan_configurations', to='ordinary_life.olplan')),
                ('product_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_plan_configurations', to='ordinary_life.olproductversion')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_configurations', to='ol_quotations.olquotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_quotation_plan_configuration',
                'ordering': ['quotation', '-is_selected', 'id'],
            },
        ),
        migrations.AddField(
            model_name='olquotationinstallmentconfiguration',
            name='plan_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installment_configurations', to='ol_quotations.olquotationplanconfiguration'),
        ),
        migrations.CreateModel(
            name='OLQuotationRiderSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider_sum_assured', models.DecimalField(decimal_places=2, max_digits=18)),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('is_selected', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('plan_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_selections', to='ol_quotations.olquotationplanconfiguration')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_selections', to='ol_quotations.olquotation')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_selections', to='ol_parameters.olridersetup')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_quotation_rider_selection',
                'ordering': ['quotation', 'rider__code'],
            },
        ),
        migrations.CreateModel(
            name='OLQuotationUnderwriting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_required', models.BooleanField(default=False)),
                ('financial_underwriting_required', models.BooleanField(default=False)),
                ('risk_class', models.CharField(blank=True, max_length=60)),
                ('health_answers', models.JSONField(blank=True, default=dict)),
                ('medical_requirements', models.JSONField(blank=True, default=list)),
                ('declarations', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='underwriting_detail', to='ol_quotations.olquotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_quotation_underwriting',
            },
        ),
        migrations.AddIndex(
            model_name='olquotation',
            index=models.Index(fields=['partner', 'status', 'created_at'], name='ol_quotatio_partner_53c3a2_idx'),
        ),
        migrations.AddIndex(
            model_name='olquotation',
            index=models.Index(fields=['product', 'status', 'quote_date'], name='ol_quotatio_product_d1cebc_idx'),
        ),
        migrations.AddIndex(
            model_name='olquotation',
            index=models.Index(fields=['status', 'expiry_date'], name='ol_quotatio_status_4d84f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='olquotation',
            constraint=models.CheckConstraint(check=models.Q(('total_sum_assured__isnull', True), ('total_sum_assured__gte', 0), _connector='OR'), name='ol_quotation_total_sum_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olquotation',
            constraint=models.CheckConstraint(check=models.Q(('total_premium__isnull', True), ('total_premium__gte', 0), _connector='OR'), name='ol_quotation_total_premium_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='olquotationbeneficiary',
            index=models.Index(fields=['quotation', 'percentage'], name='ol_quotatio_quotati_857e13_idx'),
        ),
        migrations.AddConstraint(
            model_name='olquotationbeneficiary',
            constraint=models.CheckConstraint(check=models.Q(('percentage__gt', 0), ('percentage__lte', 100)), name='ol_quotation_beneficiary_percentage_range'),
        ),
        migrations.AddIndex(
            model_name='olquotationevent',
            index=models.Index(fields=['quotation', 'created_at'], name='ol_quotatio_quotati_a845ec_idx'),
        ),
        migrations.AddIndex(
            model_name='olquotationevent',
            index=models.Index(fields=['event_type', 'created_at'], name='ol_quotatio_event_t_fb58f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='olquotationfundallocation',
            constraint=models.UniqueConstraint(fields=('quotation', 'fund'), name='ol_quotation_fund_unique'),
        ),
        migrations.AddConstraint(
            model_name='olquotationfundallocation',
            constraint=models.CheckConstraint(check=models.Q(('allocation_percentage__gte', 0), ('allocation_percentage__lte', 100)), name='ol_quotation_fund_percentage_range'),
        ),
        migrations.AddConstraint(
            model_name='olquotationfundallocation',
            constraint=models.CheckConstraint(check=models.Q(('allocation_amount__isnull', True), ('allocation_amount__gte', 0), _connector='OR'), name='ol_quotation_fund_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olquotationinstallmentraterow',
            constraint=models.UniqueConstraint(fields=('installment_configuration', 'period_from', 'period_to'), name='ol_quotation_installment_rate_scope_unique'),
        ),
        migrations.AddConstraint(
            model_name='olquotationinstallmentraterow',
            constraint=models.CheckConstraint(check=models.Q(('period_from__gt', 0), ('period_to__gte', models.F('period_from'))), name='ol_quotation_installment_rate_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='olquotationinstallmentraterow',
            constraint=models.CheckConstraint(check=models.Q(('rate__gte', 0), ('charge__gte', 0)), name='ol_quotation_installment_rate_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='olquotationmember',
            index=models.Index(fields=['quotation', 'member_type'], name='ol_quotatio_quotati_dae1ed_idx'),
        ),
        migrations.AddIndex(
            model_name='olquotationmember',
            index=models.Index(fields=['identity_number'], name='ol_quotatio_identit_13dbbb_idx'),
        ),
        migrations.AddConstraint(
            model_name='olquotationmember',
            constraint=models.CheckConstraint(check=models.Q(('member_sum_assured__isnull', True), ('member_sum_assured__gte', 0), _connector='OR'), name='ol_quotation_member_sum_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='olquotationplanconfiguration',
            index=models.Index(fields=['quotation', 'is_selected'], name='ol_quotatio_quotati_1a8670_idx'),
        ),
        migrations.AddIndex(
            model_name='olquotationplanconfiguration',
            index=models.Index(fields=['product_version', 'plan'], name='ol_quotatio_product_036d6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='olquotationplanconfiguration',
            constraint=models.UniqueConstraint(fields=('quotation', 'product_version', 'plan', 'sub_product_code'), name='ol_quotation_plan_config_scope_unique'),
        ),
        migrations.AddConstraint(
            model_name='olquotationplanconfiguration',
            constraint=models.CheckConstraint(check=models.Q(('base_sum_assured__gt', 0)), name='ol_quotation_plan_config_sum_positive'),
        ),
        migrations.AddConstraint(
            model_name='olquotationplanconfiguration',
            constraint=models.CheckConstraint(check=models.Q(('term_years__gt', 0)), name='ol_quotation_plan_config_term_positive'),
        ),
        migrations.AddConstraint(
            model_name='olquotationplanconfiguration',
            constraint=models.CheckConstraint(check=models.Q(('premium_amount__isnull', True), ('premium_amount__gte', 0), _connector='OR'), name='ol_quotation_plan_config_premium_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='olquotationinstallmentconfiguration',
            index=models.Index(fields=['quotation', 'is_selected', 'frequency'], name='ol_quotatio_quotati_236ccf_idx'),
        ),
        migrations.AddConstraint(
            model_name='olquotationinstallmentconfiguration',
            constraint=models.UniqueConstraint(fields=('quotation', 'plan_configuration', 'frequency'), name='ol_quotation_installment_scope_unique'),
        ),
        migrations.AddConstraint(
            model_name='olquotationinstallmentconfiguration',
            constraint=models.CheckConstraint(check=models.Q(('number_of_installments__gt', 0)), name='ol_quotation_installment_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='olquotationinstallmentconfiguration',
            constraint=models.CheckConstraint(check=models.Q(('installment_amount__gt', 0)), name='ol_quotation_installment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='olquotationriderselection',
            constraint=models.UniqueConstraint(fields=('quotation', 'rider', 'plan_configuration'), name='ol_quotation_rider_scope_unique'),
        ),
        migrations.AddConstraint(
            model_name='olquotationriderselection',
            constraint=models.CheckConstraint(check=models.Q(('rider_sum_assured__gt', 0)), name='ol_quotation_rider_sum_positive'),
        ),
        migrations.AddConstraint(
            model_name='olquotationriderselection',
            constraint=models.CheckConstraint(check=models.Q(('premium_amount__isnull', True), ('premium_amount__gte', 0), _connector='OR'), name='ol_quotation_rider_premium_nonnegative'),
        ),
    ]
