# Generated by Django 5.0.14 on 2026-08-18 21:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0017_olclaimtype_olclaimreason_olcorrespondenttype_and_more'),
        ('ol_quotations', '0001_initial'),
        ('partners', '0011_partner_created_by_partner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='olquotation',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='age_at_quote',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_quotation_agent_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='current_version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='identity_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='identity_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='linked_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_ol_quotations', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='partner_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='quote_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='smoker_status',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='wizard_step_completion',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='olquotation',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_quotations_v2', to='partners.partner'),
        ),
        migrations.AlterField(
            model_name='olquotation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='ol_parameters.olproduct'),
        ),
        migrations.CreateModel(
            name='OLQuotationBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('benefit_type', models.CharField(blank=True, default='', max_length=80)),
                ('sum_assured', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('is_selected', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='ol_quotations.olquotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_quotation_benefit',
                'ordering': ['quotation', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLQuotationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(max_length=80)),
                ('file_reference', models.CharField(max_length=500)),
                ('status', models.CharField(default='PENDING', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ol_quotations.olquotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_quotation_document',
                'ordering': ['quotation', 'document_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OLQuotationFinancialSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_sum_assured', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_premium', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_rider_premium', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_benefit_premium', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('calculation_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_summary', to='ol_quotations.olquotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_quotation_financial_summary',
            },
        ),
        migrations.CreateModel(
            name='OLQuotationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('CONVERTED', 'Converted'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('change_reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ol_quotations.olquotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_quotations_version',
                'ordering': ['quotation', '-version_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='olquotationbenefit',
            constraint=models.UniqueConstraint(fields=('quotation', 'code'), name='ol_quotation_benefit_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='olquotationbenefit',
            constraint=models.CheckConstraint(check=models.Q(('sum_assured__isnull', True), ('sum_assured__gte', 0), _connector='OR'), name='ol_quotation_benefit_sum_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olquotationbenefit',
            constraint=models.CheckConstraint(check=models.Q(('premium_amount__isnull', True), ('premium_amount__gte', 0), _connector='OR'), name='ol_quotation_benefit_premium_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='olquotationdocument',
            index=models.Index(fields=['quotation', 'document_type', 'status'], name='ol_quotatio_quotati_5854aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='olquotationversion',
            constraint=models.UniqueConstraint(fields=('quotation', 'version_number'), name='ol_quotations_version_unique'),
        ),
    ]
