# Generated by Django 5.0.14 on 2026-08-18 21:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0017_olclaimtype_olclaimreason_olcorrespondenttype_and_more'),
        ('ol_quotations', '0002_olquotation_address_olquotation_age_at_quote_and_more'),
        ('ordinary_life', '0007_oldocumentrecord_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLQuotationProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('is_selected', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_product_selections', to='ol_parameters.olproduct')),
                ('product_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_product_selections', to='ordinary_life.olproductversion')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ol_quotations.olquotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_quotation_product',
                'ordering': ['quotation', '-is_primary', 'created_at'],
                'indexes': [models.Index(fields=['quotation', 'is_selected'], name='ol_quotatio_quotati_69a755_idx'), models.Index(fields=['product', 'product_version'], name='ol_quotatio_product_e24e1a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='olquotationproduct',
            constraint=models.UniqueConstraint(fields=('quotation', 'product', 'product_version'), name='ol_quotation_product_scope_unique'),
        ),
        migrations.AddConstraint(
            model_name='olquotationproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('quotation',), name='ol_quotation_one_primary_product'),
        ),
    ]
