# Generated by Django 5.0.14 on 2026-08-19 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0017_olclaimtype_olclaimreason_olcorrespondenttype_and_more'),
        ('ol_quotations', '0003_olquotationproduct_and_more'),
        ('ordinary_life', '0007_oldocumentrecord_idempotency_key_and_more'),
        ('partner_onboarding', '0014_applicationpartnertype_kyc_status'),
        ('partners', '0011_partner_created_by_partner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='olquotation',
            name='agent_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_quotation_agent_records', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='location_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_quotations', to='partner_onboarding.location'),
        ),
        migrations.AddIndex(
            model_name='olquotation',
            index=models.Index(fields=['identity_type', 'identity_number', 'date_of_birth', 'status'], name='ol_quotatio_identit_9f82a7_idx'),
        ),
        migrations.AddIndex(
            model_name='olquotation',
            index=models.Index(fields=['agent_partner', 'status', 'created_at'], name='ol_quotatio_agent_p_4bc4fa_idx'),
        ),
        migrations.AddIndex(
            model_name='olquotation',
            index=models.Index(fields=['location_master', 'status', 'created_at'], name='ol_quotatio_locatio_262c56_idx'),
        ),
    ]
