# Generated by Django 5.0.14 on 2026-08-19 06:42

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_quotations', '0004_olquotation_agent_partner_and_more'),
        ('ordinary_life', '0007_oldocumentrecord_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='olquotationplanconfiguration',
            name='estimated_bonus_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='olquotationplanconfiguration',
            name='estimated_maturity_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='olquotationplanconfiguration',
            name='joint_life',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='olquotationplanconfiguration',
            name='mortgage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='olquotationplanconfiguration',
            name='payment_period_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olquotationplanconfiguration',
            name='personal_accident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='olquotationplanconfiguration',
            name='premium_factor',
            field=models.CharField(default='NONE', max_length=80),
        ),
        migrations.AddField(
            model_name='olquotationplanconfiguration',
            name='premium_waiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='olquotationplanconfiguration',
            name='quote_basis',
            field=models.CharField(default='SUM_ASSURED', max_length=80),
        ),
        migrations.AddField(
            model_name='olquotationplanconfiguration',
            name='section_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='olquotationplanconfiguration',
            index=models.Index(fields=['quotation', 'section_number'], name='ol_quotatio_quotati_a8bc65_idx'),
        ),
        migrations.AddConstraint(
            model_name='olquotationplanconfiguration',
            constraint=models.CheckConstraint(check=models.Q(('section_number__isnull', True), ('section_number__gt', 0), _connector='OR'), name='ol_quotation_plan_config_section_positive'),
        ),
        migrations.AddConstraint(
            model_name='olquotationplanconfiguration',
            constraint=models.CheckConstraint(check=models.Q(('estimated_maturity_value__isnull', True), ('estimated_maturity_value__gt', 0), _connector='OR'), name='ol_quotation_plan_config_maturity_positive'),
        ),
        migrations.AddConstraint(
            model_name='olquotationplanconfiguration',
            constraint=models.CheckConstraint(check=models.Q(('estimated_bonus_rate__gte', 0)), name='ol_quotation_plan_config_bonus_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olquotationplanconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(('section_number__isnull', False)), fields=('quotation', 'section_number'), name='ol_quotation_plan_config_section_unique'),
        ),
    ]
