# Generated by Django 5.0.14 on 2026-08-19 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_quotations', '0005_olquotationplanconfiguration_estimated_bonus_rate_and_more'),
        ('partners', '0011_partner_created_by_partner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='olquotationmember',
            name='coverage_basis',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='olquotationmember',
            name='waiting_period_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='olquotationmember',
            index=models.Index(fields=['quotation', 'relationship', 'date_of_birth'], name='ol_quotatio_quotati_d12354_idx'),
        ),
    ]
