# Generated by Django 5.0.14 on 2026-08-19 07:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_quotations', '0006_olquotationmember_coverage_basis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olquotationinstallmentconfiguration',
            name='after_maturity_benefits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='olquotationinstallmentconfiguration',
            name='annuity_period_years',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='olquotationinstallmentconfiguration',
            name='before_maturity_benefits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='olquotationinstallmentraterow',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='olquotationinstallmentraterow',
            name='paid_up_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='olquotationinstallmentraterow',
            name='rate_percent',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7),
        ),
        migrations.AddField(
            model_name='olquotationinstallmentraterow',
            name='sequence',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
