# Generated by Django 5.0.14 on 2026-08-19 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0017_olclaimtype_olclaimreason_olcorrespondenttype_and_more'),
        ('ol_quotations', '0007_installment_configuration_modal_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='olquotationfundallocation',
            name='ol_quotation_fund_unique',
        ),
        migrations.AddField(
            model_name='olquotationfundallocation',
            name='plan_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_allocations', to='ol_quotations.olquotationplanconfiguration'),
        ),
        migrations.AddConstraint(
            model_name='olquotationfundallocation',
            constraint=models.UniqueConstraint(fields=('quotation', 'plan_configuration', 'fund'), name='ol_quotation_fund_scope_unique'),
        ),
    ]
