# Generated by Django 5.0.14 on 2026-08-19 08:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0017_olclaimtype_olclaimreason_olcorrespondenttype_and_more'),
        ('ol_quotations', '0008_investment_fund_plan_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='olquotationbenefit',
            name='basis',
            field=models.CharField(choices=[('FIXED', 'Fixed'), ('RATIO', 'Ratio'), ('LOADED', 'Loaded'), ('DISCOUNTED', 'Discounted'), ('CAPPED', 'Capped')], default='FIXED', max_length=20),
        ),
        migrations.AddField(
            model_name='olquotationbenefit',
            name='beneficial_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_benefits', to='ol_parameters.olbeneficialtype'),
        ),
        migrations.AddField(
            model_name='olquotationbenefit',
            name='discount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=9),
        ),
        migrations.AddField(
            model_name='olquotationbenefit',
            name='loading',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=9),
        ),
        migrations.AddField(
            model_name='olquotationbenefit',
            name='maximum_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='olquotationbenefit',
            name='plan_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='ol_quotations.olquotationplanconfiguration'),
        ),
        migrations.AddField(
            model_name='olquotationbenefit',
            name='rider_selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefit_configurations', to='ol_quotations.olquotationriderselection'),
        ),
        migrations.AddField(
            model_name='olquotationbenefit',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='olquotationriderselection',
            name='beneficial_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_rider_selections', to='ol_parameters.olbeneficialtype'),
        ),
        migrations.AddField(
            model_name='olquotationriderselection',
            name='benefit_basis',
            field=models.CharField(choices=[('FIXED', 'Fixed'), ('RATIO', 'Ratio'), ('LOADED', 'Loaded'), ('DISCOUNTED', 'Discounted'), ('CAPPED', 'Capped')], default='FIXED', max_length=20),
        ),
        migrations.AddField(
            model_name='olquotationriderselection',
            name='benefit_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='olquotationriderselection',
            name='discount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=9),
        ),
        migrations.AddField(
            model_name='olquotationriderselection',
            name='loading',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=9),
        ),
        migrations.AddField(
            model_name='olquotationriderselection',
            name='maximum_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='olquotationriderselection',
            name='rider_term_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='olquotationbenefit',
            constraint=models.CheckConstraint(check=models.Q(('value__isnull', True), ('value__gte', 0), _connector='OR'), name='ol_quotation_benefit_value_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olquotationbenefit',
            constraint=models.CheckConstraint(check=models.Q(('loading__gte', 0), ('loading__lte', 100)), name='ol_quotation_benefit_loading_valid'),
        ),
        migrations.AddConstraint(
            model_name='olquotationbenefit',
            constraint=models.CheckConstraint(check=models.Q(('discount__gte', 0), ('discount__lte', 100)), name='ol_quotation_benefit_discount_valid'),
        ),
        migrations.AddConstraint(
            model_name='olquotationbenefit',
            constraint=models.CheckConstraint(check=models.Q(('maximum_cap__isnull', True), ('maximum_cap__gte', 0), _connector='OR'), name='ol_quotation_benefit_cap_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olquotationriderselection',
            constraint=models.CheckConstraint(check=models.Q(('rider_term_years__isnull', True), ('rider_term_years__gt', 0), _connector='OR'), name='ol_quotation_rider_term_positive'),
        ),
        migrations.AddConstraint(
            model_name='olquotationriderselection',
            constraint=models.CheckConstraint(check=models.Q(('benefit_value__isnull', True), ('benefit_value__gte', 0), _connector='OR'), name='ol_quotation_rider_benefit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olquotationriderselection',
            constraint=models.CheckConstraint(check=models.Q(('loading__gte', 0), ('loading__lte', 100)), name='ol_quotation_rider_loading_valid'),
        ),
        migrations.AddConstraint(
            model_name='olquotationriderselection',
            constraint=models.CheckConstraint(check=models.Q(('discount__gte', 0), ('discount__lte', 100)), name='ol_quotation_rider_discount_valid'),
        ),
        migrations.AddConstraint(
            model_name='olquotationriderselection',
            constraint=models.CheckConstraint(check=models.Q(('maximum_cap__isnull', True), ('maximum_cap__gte', 0), _connector='OR'), name='ol_quotation_rider_cap_nonnegative'),
        ),
    ]
