# Generated by Django 5.0.14 on 2026-08-19 10:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_quotations', '0009_riders_and_benefits_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='olquotationfinancialsummary',
            name='base_premium',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='olquotationfinancialsummary',
            name='calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olquotationfinancialsummary',
            name='estimated_maturity_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='olquotationfinancialsummary',
            name='input_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='olquotationfinancialsummary',
            name='installment_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='olquotationfinancialsummary',
            name='installment_payouts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='olquotationfinancialsummary',
            name='projections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='olquotationfinancialsummary',
            name='quotation_version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='olquotationfinancialsummary',
            name='recalculation_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='olquotationfinancialsummary',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='olquotationfinancialsummary',
            name='total_loading',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='olquotationfinancialsummary',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
    ]
