# Generated by Django 5.0.14 on 2026-08-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_quotations', '0010_financial_summary_calculation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olquotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('CONVERTED', 'Converted'), ('EXPIRED', 'Expired'), ('SUPERSEDED', 'Superseded')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='olquotationversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('CONVERTED', 'Converted'), ('EXPIRED', 'Expired'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20),
        ),
    ]
