# Generated by Django 5.0.14 on 2026-08-19 11:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_quotations', '0011_quotation_lifecycle_versioning_expiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='olquotationdocument',
            options={'ordering': ['quotation', '-generated_at', 'document_type']},
        ),
        migrations.AddField(
            model_name='olquotationdocument',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='olquotationdocument',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_quotation_documents_generated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='olquotationdocument',
            name='html_reference',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='olquotationdocument',
            name='mime_type',
            field=models.CharField(default='application/pdf', max_length=120),
        ),
        migrations.AddField(
            model_name='olquotationdocument',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='ol_quotations.olquotationversion'),
        ),
        migrations.AddField(
            model_name='olquotationdocument',
            name='template_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='olquotationdocument',
            name='status',
            field=models.CharField(default='GENERATED', max_length=40),
        ),
        migrations.CreateModel(
            name='OLQuotationPrintTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, default='')),
                ('template_html', models.TextField()),
                ('layout_variables', models.JSONField(blank=True, default=dict)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_quotation_print_template',
                'ordering': ['code', '-version'],
            },
        ),
        migrations.AddField(
            model_name='olquotationdocument',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='ol_quotations.olquotationprinttemplate'),
        ),
        migrations.AddIndex(
            model_name='olquotationdocument',
            index=models.Index(fields=['quotation', 'source_version', 'template_version'], name='ol_quotatio_quotati_423ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='olquotationprinttemplate',
            index=models.Index(fields=['code', 'is_active', 'effective_from', 'effective_to'], name='ol_quotatio_code_f1a277_idx'),
        ),
        migrations.AddConstraint(
            model_name='olquotationprinttemplate',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='ol_quote_print_template_code_version_uq'),
        ),
    ]
