# Generated by Django 5.0.14 on 2026-08-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_quotations', '0012_print_templates_and_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='olquotation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
