# Generated by Django 5.0.14 on 2026-06-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.useractivitylog',),
        ),
    ]
