import { expect, test, type Page } from "@playwright/test"
import { mockAccessApi, mockDropdownQuickCreateApi, seedSuperuserSession } from "./fixtures"

const UUID_PATTERN = /\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b/i

async function expectNoVisibleUuid(page: Page) {
  const bodyText = await page.locator("body").innerText()
  expect(bodyText).not.toMatch(UUID_PATTERN)
}

async function createOption(page: Page, entityLabel: string, code: string, name: string, configure?: (dialog: ReturnType<Page["getByRole"]>) => Promise<void>) {
  await page.getByRole("button", { name: `Add new ${entityLabel}` }).click()
  const dialog = page.getByRole("dialog").filter({ has: page.getByRole("heading", { name: `Add ${entityLabel}`, exact: true }) }).last()
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole("heading", { name: `Add ${entityLabel}` })).toBeVisible()
  await dialog.getByLabel(/Code/).fill(code)
  await dialog.getByLabel(/Name/).fill(name)
  if (configure) await configure(dialog)
  await dialog.getByRole("button", { name: "Create option" }).click()
  await expect(dialog).toBeHidden()
  await expect(page.getByText(name, { exact: true }).last()).toBeVisible()
}

async function createNestedOption(page: Page, parentEntityLabel: string, nestedEntityLabel: string, parentCode: string, parentName: string, nestedCode: string, nestedName: string, configureParent?: (dialog: ReturnType<Page["getByRole"]>) => Promise<void>) {
  await page.getByRole("button", { name: `Add new ${parentEntityLabel}` }).click()
  const parentDialog = page.getByRole("dialog").filter({ has: page.getByRole("heading", { name: `Add ${parentEntityLabel}`, exact: true }) }).last()
  await expect(parentDialog).toBeVisible()
  await parentDialog.getByLabel(/Code/).fill(parentCode)
  await parentDialog.getByLabel(/Name/).fill(parentName)
  await parentDialog.getByRole("button", { name: `Add new ${nestedEntityLabel}` }).click()
  const nestedDialog = page.getByRole("dialog").filter({ has: page.getByRole("heading", { name: `Add ${nestedEntityLabel}`, exact: true }) }).last()
  await expect(nestedDialog).toBeVisible()
  await nestedDialog.getByLabel(/Code/).fill(nestedCode)
  await nestedDialog.getByLabel(/Name/).fill(nestedName)
  await nestedDialog.getByRole("button", { name: "Create option" }).click()
  await expect(nestedDialog).toBeHidden()
  if (configureParent) await configureParent(parentDialog)
  await parentDialog.getByRole("button", { name: "Create option" }).click()
  await expect(parentDialog).toBeHidden()
  await expect(page.getByText(parentName, { exact: true }).last()).toBeVisible()
}

test("full OL quotation wizard populates every dropdown from empty data with audited quick-create", async ({ page }) => {
  await seedSuperuserSession(page)
  await mockAccessApi(page)
  await mockDropdownQuickCreateApi(page)

  await page.goto("/ordinary-life/quotations/new")
  await expect(page.getByRole("heading", { name: "Personal Details" })).toBeVisible()
  await expectNoVisibleUuid(page)

  await page.getByLabel(/Quote Name/).fill("E2E Empty Dropdown Quote")
  await page.getByLabel(/Quote Date/).fill("2026-08-19")
  await createOption(page, "Identity Type", "PASS-E2E", "Passport (E2E)")
  await page.getByLabel(/Identity Number/).fill("PASS-E2E-001")
  await page.getByLabel(/Date of Birth/).fill("1990-01-01")
  await expect(page.getByLabel(/Gender/).locator("option[value='MALE']")).toHaveCount(1)
  await expect(page.getByLabel(/Smoker/).locator("option[value='NON_SMOKER']")).toHaveCount(1)
  await page.getByLabel(/Gender/).selectOption("MALE")
  await page.getByLabel(/Smoker/).selectOption("NON_SMOKER")
  await createOption(page, "Location", "ZAN-E2E", "Zanzibar City", async (dialog) => {
    await dialog.getByLabel(/Branch/).selectOption("branch-e2e")
  })
  await page.getByLabel(/Address/).fill("Stone Town, Zanzibar")
  await page.getByRole("button", { name: /^Agentrequired$/ }).click()
  await page.getByRole("option", { name: "E2E Agent" }).click()
  await expectNoVisibleUuid(page)
  await page.getByRole("button", { name: "Next" }).click()

  await expect(page.getByRole("button", { name: "Plan & Sub-Products" })).toHaveAttribute("aria-current", "step")
  await page.getByRole("button", { name: "Add product" }).click()
  const productDialog = page.getByRole("dialog").last()
  await expect(productDialog.getByRole("heading", { name: "Add Product" })).toBeVisible()
  await productDialog.getByLabel(/Code/).fill("PROD-E2E")
  await productDialog.getByLabel(/Name/).fill("E2E Dropdown Product")
  await productDialog.getByRole("button", { name: "Add new Plan type" }).click()
  const planTypeDialog = page.getByRole("dialog").filter({ has: page.getByRole("heading", { name: "Add Plan Types", exact: true }) })
  await planTypeDialog.locator('input[name="code"]').fill("PLAN-E2E")
  await planTypeDialog.locator('input[name="name"]').fill("Individual Life (E2E)")
  await planTypeDialog.getByRole("button", { name: "Create option" }).click()
  await expect(planTypeDialog).toBeHidden()
  await productDialog.getByRole("button", { name: "Create option" }).click()
  await expect(productDialog).toBeHidden()
  await expect(page.getByText("E2E Dropdown Product", { exact: true }).last()).toBeVisible()
  const createdPlanCard = page.getByRole("button", { name: /E2E-DROPDOWN.*E2E Dropdown Product/ })
  await expect(createdPlanCard).toBeVisible()
  await expect(createdPlanCard).toHaveAttribute("aria-pressed", "true")
  await expect(page.getByText("1 Plan selected")).toBeVisible()
  await expectNoVisibleUuid(page)

  const planFrequency = page.getByRole("button", { name: "Payment Frequency" })
  await planFrequency.click()
  await page.getByRole("option", { name: "Annual" }).click()
  await page.getByRole("button", { name: "Quote Basis" }).click()
  await page.getByRole("option", { name: "Sum Assured" }).click()
  await page.getByRole("button", { name: "Premium Factor", exact: true }).click()
  await page.getByRole("option", { name: "None" }).click()
  await page.getByLabel(/Policy Term/).fill("20")
  await page.getByLabel(/Payment Period/).fill("20")
  await page.getByLabel(/Estimated Maturity Value/).fill("250000")
  await page.getByRole("button", { name: "Next" }).click()

  await expect(page.getByRole("heading", { name: "Member Coverage" })).toBeVisible()
  await expectNoVisibleUuid(page)
  await page.getByRole("button", { name: /Add member/i }).click()
  const memberDialog = page.getByRole("dialog").last()
  await memberDialog.getByLabel(/Name/).fill("E2E Spouse")
  await createOption(page, "Member Relation", "SPOUSE-E2E", "Spouse (E2E)")
  await memberDialog.getByLabel(/Date of Birth/).fill("1992-01-01")
  await memberDialog.locator('select[name="member_gender"]').selectOption("FEMALE")
  await memberDialog.getByLabel(/Sum Assured/).fill("100000")
  await memberDialog.getByRole("button", { name: /Save member|Add member/i }).click()
  await expect(memberDialog).toBeHidden()
  await expect(page.getByText("E2E Spouse", { exact: true })).toBeVisible()

  await page.getByRole("button", { name: "Installments", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Installments" })).toBeVisible()
  await page.getByRole("button", { name: "Configure" }).click()
  const installmentDialog = page.getByRole("dialog").last()
  await installmentDialog.getByLabel("Annuity Period (years)").fill("20")
  await installmentDialog.getByRole("button", { name: "Add new Payment Mode" }).click()
  const paymentModeDialog = page.getByRole("dialog").filter({ has: page.getByRole("heading", { name: "Add Payment Mode", exact: true }) }).last()
  await paymentModeDialog.getByLabel(/Code/).fill("EFT-E2E")
  await paymentModeDialog.getByLabel(/Name/).fill("Electronic Transfer (E2E)")
  await paymentModeDialog.getByRole("button", { name: "Create option" }).click()
  await expect(paymentModeDialog).toBeHidden()
  await installmentDialog.getByLabel("Installment 1 rate").fill("100")
  await installmentDialog.getByRole("button", { name: "Save configuration" }).click()
  await expect(installmentDialog).toBeHidden()
  await expectNoVisibleUuid(page)

  await page.getByRole("button", { name: "Investment Funds", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Investment Funds" })).toBeVisible()
  await page.getByRole("button", { name: "Add fund" }).click()
  await page.getByRole("button", { name: "Add new Investment Fund" }).click()
  const fundDialog = page.getByRole("dialog").last()
  await fundDialog.getByLabel(/Code/).fill("FUND-E2E")
  await fundDialog.getByLabel(/Name/).fill("ZIC Balanced Fund (E2E)")
  await fundDialog.getByRole("button", { name: "Add new Investment Fund Type" }).click()
  const fundTypeDialog = page.getByRole("dialog").filter({ has: page.getByRole("heading", { name: "Add Investment Fund Types", exact: true }) }).last()
  await fundTypeDialog.locator('input[name="code"]').fill("FT-E2E")
  await fundTypeDialog.locator('input[name="name"]').fill("Balanced (E2E)")
  await fundTypeDialog.getByRole("button", { name: "Create option" }).click()
  await expect(fundTypeDialog).toBeHidden()
  await fundDialog.getByRole("button", { name: "Create option" }).click()
  await expect(fundDialog).toBeHidden()
  await page.getByLabel("Allocation percentage 1").fill("100")
  await page.getByLabel("Allocated amount 1").fill("250000")
  await page.getByRole("button", { name: "Save fund allocations" }).click()
  await expect(page.getByText(/Investment fund allocations saved/i)).toBeVisible()
  await expectNoVisibleUuid(page)

  await page.getByRole("button", { name: "Riders & Benefits", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Riders & Benefits" })).toBeVisible()
  await page.getByRole("button", { name: "Add new Rider" }).click()
  const riderDialog = page.getByRole("dialog").last()
  await riderDialog.getByLabel(/Code/).fill("RIDER-E2E")
  await riderDialog.getByLabel(/Name/).fill("Family Protection Rider (E2E)")
  await riderDialog.locator('select[name="rider_category"]').selectOption("PROTECTION")
  await riderDialog.locator('select[name="benefit_type"]').selectOption("DEATH")
  await riderDialog.getByRole("button", { name: "Create option" }).click()
  await expect(riderDialog).toBeHidden()
  await expect(page.getByText("Family Protection Rider (E2E)", { exact: true }).last()).toBeVisible()
  const benefitTrigger = page.locator('button[id="benefit_type_0"]')
  await benefitTrigger.click()
  await page.getByRole("button", { name: "Add new Benefit Type" }).click()
  const benefitDialog = page.getByRole("dialog").last()
  await benefitDialog.getByLabel(/Code/).fill("BEN-E2E")
  await benefitDialog.getByLabel(/Name/).fill("Death Benefit (E2E)")
  await benefitDialog.getByRole("button", { name: "Create option" }).click()
  await expect(benefitDialog).toBeHidden()
  await page.getByLabel(/Rider Sum Assured \/ Amount/).fill("100000")
  await page.getByLabel(/Value/).fill("100000")
  await page.getByRole("button", { name: "Save rider configuration" }).click()
  await expect(page.getByText("Rider configuration saved", { exact: false })).toBeVisible()
  await expectNoVisibleUuid(page)

  await page.getByRole("button", { name: "Financial Details", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Financial Details" })).toBeVisible()
  await page.getByRole("button", { name: /Calculate|Recalculate/ }).click()
  await page.getByRole("button", { name: "Review & Finalize" }).click()
  await expect(page.getByRole("heading", { name: "Review & Finalize" })).toBeVisible()
  await expectNoVisibleUuid(page)
  await page.getByRole("button", { name: "Finalize quotation" }).click()
  await page.getByRole("button", { name: "Confirm finalize" }).click()
  await expect(page.getByText(/finalized/i).last()).toBeVisible()

  const auditResponse = await page.evaluate(async () => {
    const response = await fetch("/api/v1/governance/audit-logs/?source_channel=QUICK_CREATE")
    return response.json()
  })
  expect(auditResponse.data.results).toHaveLength(10)
  expect(auditResponse.data.results).toEqual(expect.arrayContaining([
    expect.objectContaining({ entity: "identity-types", source_channel: "QUICK_CREATE", actor: "e2e-superuser" }),
    expect.objectContaining({ entity: "locations", source_channel: "QUICK_CREATE", actor: "e2e-superuser" }),
    expect.objectContaining({ entity: "plan-types", source_channel: "QUICK_CREATE", actor: "e2e-superuser" }),
    expect.objectContaining({ entity: "products", source_channel: "QUICK_CREATE", actor: "e2e-superuser" }),
    expect.objectContaining({ entity: "member-relations", source_channel: "QUICK_CREATE", actor: "e2e-superuser" }),
    expect.objectContaining({ entity: "payment-modes", source_channel: "QUICK_CREATE", actor: "e2e-superuser" }),
    expect.objectContaining({ entity: "investment-fund-types", source_channel: "QUICK_CREATE", actor: "e2e-superuser" }),
    expect.objectContaining({ entity: "investment-funds", source_channel: "QUICK_CREATE", actor: "e2e-superuser" }),
    expect.objectContaining({ entity: "riders", source_channel: "QUICK_CREATE", actor: "e2e-superuser" }),
    expect.objectContaining({ entity: "benefit-types", source_channel: "QUICK_CREATE", actor: "e2e-superuser" }),
  ]))
  for (const entry of auditResponse.data.results) expect(entry.reason).toBe("Created from OL quotation wizard")
})

test("unauthorized users see no quick-create plus controls on the OL wizard", async ({ page }) => {
  await seedSuperuserSession(page)
  await mockAccessApi(page, undefined, [])
  await mockDropdownQuickCreateApi(page)

  await page.goto("/ordinary-life/quotations/new")
  await expect(page.getByRole("heading", { name: "Personal Details" })).toBeVisible()
  for (const entityLabel of ["Identity Type", "Location", "Agent"]) {
    await expect(page.getByRole("button", { name: `Add new ${entityLabel}` })).toHaveCount(0)
  }
  await page.getByRole("button", { name: "Plan & Sub-Products" }).click()
  await expect(page.getByRole("button", { name: "Add product" })).toHaveCount(0)
  await expect(page.getByRole("button", { name: "Add new Payment Frequency" })).toHaveCount(0)
  await expect(page.getByRole("button", { name: "Add new Quote Basis" })).toHaveCount(0)
  await expect(page.getByRole("button", { name: "Add new Premium Factor" })).toHaveCount(0)
})
