# Generated by Django 5.0.14 on 2026-06-21 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system_parameters.parametergroup')),
            ],
            options={
                'verbose_name': 'Parameter Group',
                'verbose_name_plural': 'Parameter Groups',
                'db_table': 'system_parameter_group',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_lists', to='system_parameters.parametergroup')),
            ],
            options={
                'verbose_name': 'Choice List',
                'verbose_name_plural': 'Choice Lists',
                'db_table': 'system_choice_list',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('STRING', 'String'), ('TEXT', 'Text'), ('INTEGER', 'Integer'), ('FLOAT', 'Float'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON'), ('FILE', 'File')], default='STRING', max_length=10)),
                ('string_value', models.TextField(blank=True, null=True)),
                ('integer_value', models.IntegerField(blank=True, null=True)),
                ('float_value', models.FloatField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('json_value', models.JSONField(blank=True, null=True)),
                ('file_value', models.FileField(blank=True, null=True, upload_to='system_parameters/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='system_parameters.parametergroup')),
            ],
            options={
                'verbose_name': 'System Parameter',
                'verbose_name_plural': 'System Parameters',
                'db_table': 'system_parameter',
                'ordering': ['group__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='system_parameters.choicelist')),
            ],
            options={
                'verbose_name': 'Choice Option',
                'verbose_name_plural': 'Choice Options',
                'db_table': 'system_choice_option',
                'ordering': ['choice_list', 'sort_order', 'label'],
                'unique_together': {('choice_list', 'code')},
            },
        ),
    ]
