# Generated by Django 5.0.14 on 2026-06-28 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_parameters', '0008_seed_system_parameters'),
    ]

    operations = [
    ]
