# Generated by Django 5.0.14 on 2026-06-28 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_parameters', '0009_add_app_status_choices'),
    ]

    operations = [
    ]
