# Generated by Django 5.0.14 on 2026-06-30 03:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OLAnticipatedEndowmentInstallmentRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_year', models.PositiveIntegerField()),
                ('percentage_payout', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_anticipated_endowment_rate',
            },
        ),
        migrations.CreateModel(
            name='OLBeneficiaryType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_beneficiary_type',
            },
        ),
        migrations.CreateModel(
            name='OLCommitmentStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_commitment_status',
            },
        ),
        migrations.CreateModel(
            name='OLComputationApproach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_computation_approach',
            },
        ),
        migrations.CreateModel(
            name='OLDefaultSystemParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_default_system_parameter',
            },
        ),
        migrations.CreateModel(
            name='OLGracePeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('days', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_grace_period',
            },
        ),
        migrations.CreateModel(
            name='OLGracePeriodNotificationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days_past_due', models.PositiveIntegerField()),
                ('notification_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_grace_period_notification_schedule',
            },
        ),
        migrations.CreateModel(
            name='OLHealthQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('question_text', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_health_question',
            },
        ),
        migrations.CreateModel(
            name='OLHealthQuestionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_health_questionnaire',
            },
        ),
        migrations.CreateModel(
            name='OLMaturityClaimSetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('notification_days_prior', models.PositiveIntegerField(help_text='Days prior to maturity to notify')),
                ('requires_discharge_voucher', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_maturity_claim_setup',
            },
        ),
        migrations.CreateModel(
            name='OLMemberCoverConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('max_dependents', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_member_cover_configuration',
            },
        ),
        migrations.CreateModel(
            name='OLOverrideCommissionSetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
                ('override_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of base commission', max_digits=5)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_override_commission_setup',
            },
        ),
        migrations.CreateModel(
            name='OLPaidUpRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_year', models.PositiveIntegerField()),
                ('rate_factor', models.DecimalField(decimal_places=5, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_paid_up_rate',
            },
        ),
        migrations.CreateModel(
            name='OLPaidUpSetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('min_years_in_force', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_paid_up_setup',
            },
        ),
        migrations.CreateModel(
            name='OLPolicyRenewalStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_policy_renewal_status',
            },
        ),
        migrations.CreateModel(
            name='OLPolicyStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_terminal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_policy_status',
            },
        ),
        migrations.CreateModel(
            name='OLReinstatementWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_months', models.PositiveIntegerField(help_text='Max months after lapse to allow reinstatement')),
                ('requires_medical', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_reinstatement_window',
            },
        ),
        migrations.CreateModel(
            name='OLSurrenderSetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('min_years_in_force', models.PositiveIntegerField()),
                ('penalty_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_surrender_setup',
            },
        ),
        migrations.CreateModel(
            name='OLSurrenderValueRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_year', models.PositiveIntegerField()),
                ('rate_factor', models.DecimalField(decimal_places=5, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_surrender_value_rate',
            },
        ),
        migrations.CreateModel(
            name='OLLookupValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, help_text='The dropdown parameter category (e.g., POLICY_STATUS).', max_length=50)),
                ('value', models.CharField(help_text='The stored value in the database.', max_length=50)),
                ('label', models.CharField(help_text='The human-readable label displayed in the UI.', max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ol_lookup_value',
                'ordering': ['category', 'sort_order', 'label'],
                'unique_together': {('category', 'value')},
            },
        ),
    ]
