# Generated by Django 5.0.14 on 2026-08-14 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinary_life', '0002_olclient_olpolicy_olproduct_olproposal_and_more'),
        ('partners', '0010_partnertypedocumentrequirement_allow_multiple_uploads_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='olpolicy',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordinary_life_policies', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='olpolicy',
            name='currency',
            field=models.CharField(default='TZS', max_length=3),
        ),
        migrations.AddField(
            model_name='olpolicy',
            name='life_assured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='life_assured_policies', to='ordinary_life.olclient'),
        ),
        migrations.AddField(
            model_name='olpolicy',
            name='policyholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policyholder_policies', to='ordinary_life.olclient'),
        ),
        migrations.AddField(
            model_name='olpolicy',
            name='premium_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='olpolicy',
            name='sum_assured',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='OLBeneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordinary_life_beneficiaries', to='ordinary_life.olbeneficiarytype')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='ordinary_life.olpolicy')),
            ],
            options={
                'db_table': 'ol_beneficiary',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OLWorkflowEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(db_index=True, max_length=50)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(max_length=80)),
                ('previous_status', models.CharField(blank=True, max_length=50)),
                ('new_status', models.CharField(blank=True, max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordinary_life_workflow_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_workflow_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'created_at'], name='ol_workflow_entity__7e0502_idx')],
            },
        ),
    ]
