# Generated by Django 5.0.14 on 2026-08-14 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinary_life', '0003_olpolicy_agent_olpolicy_currency_and_more'),
        ('partners', '0011_partner_created_by_partner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('benefit_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ol_benefit',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OLMedicalRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement_type', models.CharField(max_length=80)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADED', 'Uploaded'), ('VERIFIED', 'Verified'), ('WAIVED', 'Waived'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ol_medical_requirement',
            },
        ),
        migrations.CreateModel(
            name='OLRider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('eligibility_rules', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ol_rider',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OLUnderwritingCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_class', models.CharField(blank=True, max_length=30)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REFERRED', 'Referred'), ('DECLINED', 'Declined'), ('POSTPONED', 'Postponed')], default='PENDING', max_length=20)),
                ('decision_reason', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ol_underwriting_case',
            },
        ),
        migrations.AddField(
            model_name='olclient',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordinary_life_legacy_clients', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='olpolicy',
            name='life_assured_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordinary_life_assured_policies', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='olpolicy',
            name='policyholder_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordinary_life_policyholders', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='olpolicy',
            name='product_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='olpolicy',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='olproduct',
            name='business_area',
            field=models.CharField(default='ORDINARY_LIFE', max_length=50),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='payment_currency',
            field=models.CharField(default='TZS', max_length=3),
        ),
        migrations.AddField(
            model_name='olproposal',
            name='payment_required_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='currency',
            field=models.CharField(default='TZS', max_length=3),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordinary_life_quotations', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='payment_frequency',
            field=models.CharField(default='ANNUAL', max_length=30),
        ),
        migrations.CreateModel(
            name='OLApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(max_length=100, unique=True)),
                ('declarations', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='DRAFT', max_length=40)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('life_assured', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordinary_life_life_assured_applications', to='partners.partner')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordinary_life_applications', to='partners.partner')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordinary_life_payer_applications', to='partners.partner')),
                ('policyholder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordinary_life_policyholder_applications', to='partners.partner')),
                ('proposal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application', to='ordinary_life.olproposal')),
            ],
            options={
                'db_table': 'ol_application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OLBeneficiaryAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='ordinary_life.olbeneficiary')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiary_allocations', to='ordinary_life.olpolicy')),
            ],
            options={
                'db_table': 'ol_beneficiary_allocation',
            },
        ),
        migrations.CreateModel(
            name='OLDocumentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=80)),
                ('file_reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADED', 'Uploaded'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_records', to='ordinary_life.olpolicy')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_records', to='ordinary_life.olproposal')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordinary_life_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_ordinary_life_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_document_record',
            },
        ),
        migrations.CreateModel(
            name='OLEndorsement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endorsement_number', models.CharField(max_length=100, unique=True)),
                ('endorsement_type', models.CharField(max_length=50)),
                ('requested_effective_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('APPLIED', 'Applied'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('requested_changes', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_ordinary_life_endorsements', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_ordinary_life_endorsements', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endorsements', to='ordinary_life.olpolicy')),
            ],
            options={
                'db_table': 'ol_endorsement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OLHealthDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('is_complete', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_declarations', to='ordinary_life.olproposal')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='ordinary_life.olhealthquestionnaire')),
            ],
            options={
                'db_table': 'ol_health_declaration',
            },
        ),
        migrations.CreateModel(
            name='OLHealthResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.JSONField(default=dict)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ordinary_life.olhealthdeclaration')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_responses', to='ordinary_life.olhealthquestion')),
            ],
            options={
                'db_table': 'ol_health_response',
            },
        ),
        migrations.CreateModel(
            name='OLMedicalResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=30)),
                ('evidence_reference', models.CharField(blank=True, max_length=255)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='ordinary_life.olmedicalrequirement')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordinary_life_medical_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_medical_result',
            },
        ),
        migrations.CreateModel(
            name='OLNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordinary_life_notes', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='ordinary_life.olpolicy')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='ordinary_life.olproposal')),
            ],
            options={
                'db_table': 'ol_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OLPartyRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('POLICYHOLDER', 'Policyholder'), ('LIFE_ASSURED', 'Life assured'), ('PAYER', 'Payer'), ('BENEFICIARY', 'Beneficiary'), ('EMPLOYER', 'Employer'), ('INTERMEDIARY', 'Intermediary')], max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('identity_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_roles', to='ordinary_life.olapplication')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordinary_life_party_roles', to='partners.partner')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_roles', to='ordinary_life.olpolicy')),
            ],
            options={
                'db_table': 'ol_party_role',
            },
        ),
        migrations.CreateModel(
            name='OLPaymentObligation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('obligation_type', models.CharField(choices=[('FIRST_PREMIUM', 'First premium'), ('RENEWAL_PREMIUM', 'Renewal premium'), ('INSTALMENT', 'Instalment'), ('LOAN', 'Loan'), ('WITHDRAWAL', 'Withdrawal')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('DUE', 'Due'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('VOID', 'Void')], default='DUE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_obligations', to='ordinary_life.olpolicy')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_obligations', to='ordinary_life.olproposal')),
            ],
            options={
                'db_table': 'ol_payment_obligation',
            },
        ),
        migrations.CreateModel(
            name='OLPaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_receipt_reference', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordinary_life_payment_allocations', to=settings.AUTH_USER_MODEL)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='ordinary_life.olpaymentobligation')),
            ],
            options={
                'db_table': 'ol_payment_allocation',
            },
        ),
        migrations.CreateModel(
            name='OLPolicyParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('POLICYHOLDER', 'Policyholder'), ('LIFE_ASSURED', 'Life assured'), ('PAYER', 'Payer'), ('BENEFICIARY', 'Beneficiary'), ('EMPLOYER', 'Employer'), ('INTERMEDIARY', 'Intermediary')], max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('identity_snapshot', models.JSONField(blank=True, default=dict)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legacy_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy_party_snapshots', to='ordinary_life.olclient')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordinary_life_policy_parties', to='partners.partner')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_parties', to='ordinary_life.olpolicy')),
            ],
            options={
                'db_table': 'ol_policy_party',
            },
        ),
        migrations.CreateModel(
            name='OLPolicyStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('correlation_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordinary_life_policy_status_changes', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='ordinary_life.olpolicy')),
            ],
            options={
                'db_table': 'ol_policy_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OLPolicyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_number', models.CharField(max_length=100, unique=True)),
                ('transaction_type', models.CharField(choices=[('ISSUANCE', 'Issuance'), ('ENDORSEMENT', 'Endorsement'), ('PAYMENT', 'Payment'), ('LOAN', 'Loan'), ('WITHDRAWAL', 'Withdrawal'), ('SURRENDER', 'Surrender'), ('PAID_UP', 'Paid up'), ('REINSTATEMENT', 'Reinstatement'), ('RENEWAL', 'Renewal'), ('MATURITY', 'Maturity'), ('CANCELLATION', 'Cancellation')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('effective_date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('reason', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordinary_life_policy_transactions', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ordinary_life.olpolicy')),
            ],
            options={
                'db_table': 'ol_policy_transaction',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OLPremiumSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(max_length=30)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('total_premium', models.DecimalField(decimal_places=2, max_digits=14)),
                ('installment_count', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premium_schedules', to='ordinary_life.olpolicy')),
            ],
            options={
                'db_table': 'ol_premium_schedule',
            },
        ),
        migrations.CreateModel(
            name='OLPremiumInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('DUE', 'Due'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('WAIVED', 'Waived'), ('OVERDUE', 'Overdue')], default='DUE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='ordinary_life.olpremiumschedule')),
            ],
            options={
                'db_table': 'ol_premium_installment',
            },
        ),
        migrations.CreateModel(
            name='OLProductVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('min_entry_age', models.PositiveIntegerField(default=18)),
                ('max_entry_age', models.PositiveIntegerField(default=65)),
                ('min_term_years', models.PositiveIntegerField(default=1)),
                ('max_term_years', models.PositiveIntegerField(default=30)),
                ('payment_frequencies', models.JSONField(default=list)),
                ('underwriting_rules', models.JSONField(blank=True, default=dict)),
                ('servicing_rules', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculation_approach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_versions', to='ordinary_life.olcomputationapproach')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='ordinary_life.olproduct')),
            ],
            options={
                'db_table': 'ol_product_version',
                'ordering': ['product', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='OLProductBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_versions', to='ordinary_life.olbenefit')),
                ('product_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benefits', to='ordinary_life.olproductversion')),
            ],
            options={
                'db_table': 'ol_product_benefit',
            },
        ),
        migrations.CreateModel(
            name='OLPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('minimum_sum_assured', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('maximum_sum_assured', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='ordinary_life.olproductversion')),
            ],
            options={
                'db_table': 'ol_plan',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='olpolicy',
            name='product_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='ordinary_life.olproductversion'),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='product_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='ordinary_life.olproductversion'),
        ),
        migrations.CreateModel(
            name='OLQuotationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('inputs', models.JSONField(default=dict)),
                ('calculated_outputs', models.JSONField(default=dict)),
                ('product_version_snapshot', models.JSONField(default=dict)),
                ('calculation_hash', models.CharField(max_length=128)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordinary_life_quotation_versions', to=settings.AUTH_USER_MODEL)),
                ('product_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_versions', to='ordinary_life.olproductversion')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='ordinary_life.olquotation')),
            ],
            options={
                'db_table': 'ol_quotation_version',
                'ordering': ['quotation', '-version_number'],
            },
        ),
        migrations.AddField(
            model_name='olproposal',
            name='quotation_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='ordinary_life.olquotationversion'),
        ),
        migrations.AddField(
            model_name='olquotation',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_quotations', to='ordinary_life.olquotationversion'),
        ),
        migrations.CreateModel(
            name='OLRateBand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_age', models.PositiveIntegerField()),
                ('max_age', models.PositiveIntegerField()),
                ('min_term_years', models.PositiveIntegerField()),
                ('max_term_years', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=8, max_digits=12)),
                ('assumptions', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rate_bands', to='ordinary_life.olplan')),
                ('product_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_bands', to='ordinary_life.olproductversion')),
            ],
            options={
                'db_table': 'ol_rate_band',
            },
        ),
        migrations.CreateModel(
            name='OLProductRider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('premium_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('product_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riders', to='ordinary_life.olproductversion')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_versions', to='ordinary_life.olrider')),
            ],
            options={
                'db_table': 'ol_product_rider',
            },
        ),
        migrations.CreateModel(
            name='OLStateTransitionGuard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('from_status', models.CharField(max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ol_state_transition_guard',
                'indexes': [models.Index(fields=['entity_type', 'from_status', 'is_active'], name='ol_state_tr_entity__27da71_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='olstatetransitionguard',
            constraint=models.UniqueConstraint(fields=('entity_type', 'from_status', 'to_status', 'action'), name='ol_transition_guard_unique'),
        ),
        migrations.AddField(
            model_name='olunderwritingcase',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='underwriting_case', to='ordinary_life.olproposal'),
        ),
        migrations.AddField(
            model_name='olunderwritingcase',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordinary_life_underwriting_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='olmedicalrequirement',
            name='underwriting_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_requirements', to='ordinary_life.olunderwritingcase'),
        ),
        migrations.AddIndex(
            model_name='olapplication',
            index=models.Index(fields=['partner', 'status'], name='ol_applicat_partner_f118a3_idx'),
        ),
        migrations.AddIndex(
            model_name='olapplication',
            index=models.Index(fields=['application_number'], name='ol_applicat_applica_d467c9_idx'),
        ),
        migrations.AddIndex(
            model_name='olbeneficiaryallocation',
            index=models.Index(fields=['policy', 'is_active'], name='ol_benefici_policy__850d96_idx'),
        ),
        migrations.AddConstraint(
            model_name='olbeneficiaryallocation',
            constraint=models.CheckConstraint(check=models.Q(('percentage__gt', 0), ('percentage__lte', 100)), name='ol_beneficiary_allocation_valid_percentage'),
        ),
        migrations.AddConstraint(
            model_name='olbeneficiaryallocation',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ol_beneficiary_allocation_valid_dates'),
        ),
        migrations.AddIndex(
            model_name='oldocumentrecord',
            index=models.Index(fields=['policy', 'status'], name='ol_document_policy__a90ef8_idx'),
        ),
        migrations.AddConstraint(
            model_name='oldocumentrecord',
            constraint=models.CheckConstraint(check=models.Q(('proposal__isnull', False), ('policy__isnull', False), _connector='OR'), name='ol_document_has_parent'),
        ),
        migrations.AddConstraint(
            model_name='oldocumentrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('proposal__isnull', False)), fields=('proposal', 'document_type'), name='ol_document_one_proposal_type'),
        ),
        migrations.AddIndex(
            model_name='olendorsement',
            index=models.Index(fields=['policy', 'status'], name='ol_endorsem_policy__5a7c5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='olhealthdeclaration',
            constraint=models.UniqueConstraint(fields=('proposal', 'version_number'), name='ol_health_declaration_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='olhealthresponse',
            constraint=models.UniqueConstraint(fields=('declaration', 'question'), name='ol_health_response_unique_question'),
        ),
        migrations.AddConstraint(
            model_name='olnote',
            constraint=models.CheckConstraint(check=models.Q(('proposal__isnull', False), ('policy__isnull', False), _connector='OR'), name='ol_note_has_parent'),
        ),
        migrations.AddIndex(
            model_name='olpartyrole',
            index=models.Index(fields=['partner', 'role'], name='ol_party_ro_partner_9ec7ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='olpartyrole',
            constraint=models.CheckConstraint(check=models.Q(('application__isnull', False), ('policy__isnull', False), _connector='OR'), name='ol_party_role_has_parent'),
        ),
        migrations.AddConstraint(
            model_name='olpartyrole',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ol_party_role_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='olpartyrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('application', 'role'), name='ol_party_role_one_primary_application'),
        ),
        migrations.AddConstraint(
            model_name='olpartyrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('policy', 'role'), name='ol_party_role_one_primary_policy'),
        ),
        migrations.AddIndex(
            model_name='olpaymentobligation',
            index=models.Index(fields=['policy', 'status', 'due_date'], name='ol_payment__policy__4c191a_idx'),
        ),
        migrations.AddConstraint(
            model_name='olpaymentobligation',
            constraint=models.CheckConstraint(check=models.Q(('proposal__isnull', False), ('policy__isnull', False), _connector='OR'), name='ol_payment_obligation_has_parent'),
        ),
        migrations.AddConstraint(
            model_name='olpaymentobligation',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='ol_payment_obligation_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='olpaymentobligation',
            constraint=models.CheckConstraint(check=models.Q(('allocated_amount__gte', 0), ('allocated_amount__lte', models.F('amount'))), name='ol_payment_obligation_valid_allocation'),
        ),
        migrations.AddIndex(
            model_name='olpaymentallocation',
            index=models.Index(fields=['external_receipt_reference'], name='ol_payment__externa_6e6f10_idx'),
        ),
        migrations.AddConstraint(
            model_name='olpaymentallocation',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='ol_payment_allocation_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='olpolicyparty',
            constraint=models.CheckConstraint(check=models.Q(('partner__isnull', False), ('legacy_client__isnull', False), _connector='OR'), name='ol_policy_party_has_identity'),
        ),
        migrations.AddConstraint(
            model_name='olpolicyparty',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ol_policy_party_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='olpolicyparty',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True), ('is_primary', True)), fields=('policy', 'role'), name='ol_policy_party_one_current_primary'),
        ),
        migrations.AddIndex(
            model_name='olpolicystatushistory',
            index=models.Index(fields=['policy', 'created_at'], name='ol_policy_s_policy__ac80a5_idx'),
        ),
        migrations.AddIndex(
            model_name='olpolicytransaction',
            index=models.Index(fields=['policy', 'transaction_type', 'effective_date'], name='ol_policy_t_policy__0765ee_idx'),
        ),
        migrations.AddIndex(
            model_name='olpolicytransaction',
            index=models.Index(fields=['status', 'created_at'], name='ol_policy_t_status_68c7e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='olpolicytransaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__isnull', True), ('amount__gte', 0), _connector='OR'), name='ol_policy_transaction_nonnegative_amount'),
        ),
        migrations.AddConstraint(
            model_name='olpremiumschedule',
            constraint=models.CheckConstraint(check=models.Q(('total_premium__gt', 0)), name='ol_premium_schedule_positive_total'),
        ),
        migrations.AddConstraint(
            model_name='olpremiumschedule',
            constraint=models.CheckConstraint(check=models.Q(('installment_count__gt', 0)), name='ol_premium_schedule_positive_count'),
        ),
        migrations.AddConstraint(
            model_name='olpremiumschedule',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='ol_premium_schedule_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='olpremiumschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('policy',), name='ol_premium_schedule_one_current'),
        ),
        migrations.AddConstraint(
            model_name='olpremiuminstallment',
            constraint=models.UniqueConstraint(fields=('schedule', 'sequence'), name='ol_premium_installment_unique_sequence'),
        ),
        migrations.AddConstraint(
            model_name='olpremiuminstallment',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gt', 0)), name='ol_premium_installment_positive_sequence'),
        ),
        migrations.AddConstraint(
            model_name='olpremiuminstallment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='ol_premium_installment_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='olpremiuminstallment',
            constraint=models.CheckConstraint(check=models.Q(('allocated_amount__gte', 0), ('allocated_amount__lte', models.F('amount'))), name='ol_premium_installment_valid_allocation'),
        ),
        migrations.AddIndex(
            model_name='olproductversion',
            index=models.Index(fields=['product', 'effective_from', 'effective_to'], name='ol_product__product_896f38_idx'),
        ),
        migrations.AddIndex(
            model_name='olproductversion',
            index=models.Index(fields=['is_active', 'currency'], name='ol_product__is_acti_e87550_idx'),
        ),
        migrations.AddConstraint(
            model_name='olproductversion',
            constraint=models.UniqueConstraint(fields=('product', 'version_number'), name='ol_product_version_unique_number'),
        ),
        migrations.AddConstraint(
            model_name='olproductversion',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='ol_product_version_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='olproductversion',
            constraint=models.CheckConstraint(check=models.Q(('min_entry_age__lte', models.F('max_entry_age'))), name='ol_product_version_valid_ages'),
        ),
        migrations.AddConstraint(
            model_name='olproductversion',
            constraint=models.CheckConstraint(check=models.Q(('min_term_years__lte', models.F('max_term_years')), ('min_term_years__gt', 0)), name='ol_product_version_valid_terms'),
        ),
        migrations.AddConstraint(
            model_name='olproductbenefit',
            constraint=models.UniqueConstraint(fields=('product_version', 'benefit'), name='ol_product_benefit_unique'),
        ),
        migrations.AddConstraint(
            model_name='olproductbenefit',
            constraint=models.CheckConstraint(check=models.Q(('minimum_amount__isnull', True), ('maximum_amount__isnull', True), ('minimum_amount__lte', models.F('maximum_amount')), _connector='OR'), name='ol_product_benefit_valid_amount_range'),
        ),
        migrations.AddConstraint(
            model_name='olplan',
            constraint=models.UniqueConstraint(fields=('product_version', 'code'), name='ol_plan_unique_code_per_version'),
        ),
        migrations.AddConstraint(
            model_name='olplan',
            constraint=models.CheckConstraint(check=models.Q(('minimum_sum_assured__isnull', True), ('maximum_sum_assured__isnull', True), ('minimum_sum_assured__lte', models.F('maximum_sum_assured')), _connector='OR'), name='ol_plan_valid_sum_assured_range'),
        ),
        migrations.AddIndex(
            model_name='olquotationversion',
            index=models.Index(fields=['calculation_hash'], name='ol_quotatio_calcula_979378_idx'),
        ),
        migrations.AddConstraint(
            model_name='olquotationversion',
            constraint=models.UniqueConstraint(fields=('quotation', 'version_number'), name='ol_quotation_version_unique_number'),
        ),
        migrations.AddConstraint(
            model_name='olquotationversion',
            constraint=models.UniqueConstraint(fields=('quotation', 'calculation_hash'), name='ol_quotation_version_unique_hash'),
        ),
        migrations.AddIndex(
            model_name='olrateband',
            index=models.Index(fields=['product_version', 'min_age', 'max_age'], name='ol_rate_ban_product_9baf23_idx'),
        ),
        migrations.AddConstraint(
            model_name='olrateband',
            constraint=models.CheckConstraint(check=models.Q(('min_age__lte', models.F('max_age'))), name='ol_rate_band_valid_ages'),
        ),
        migrations.AddConstraint(
            model_name='olrateband',
            constraint=models.CheckConstraint(check=models.Q(('min_term_years__lte', models.F('max_term_years'))), name='ol_rate_band_valid_terms'),
        ),
        migrations.AddConstraint(
            model_name='olrateband',
            constraint=models.CheckConstraint(check=models.Q(('rate__gte', 0)), name='ol_rate_band_nonnegative_rate'),
        ),
        migrations.AddConstraint(
            model_name='olproductrider',
            constraint=models.UniqueConstraint(fields=('product_version', 'rider'), name='ol_product_rider_unique'),
        ),
        migrations.AddConstraint(
            model_name='olproductrider',
            constraint=models.CheckConstraint(check=models.Q(('premium_rate__isnull', True), ('premium_rate__gte', 0), _connector='OR'), name='ol_product_rider_nonnegative_rate'),
        ),
        migrations.AddIndex(
            model_name='olunderwritingcase',
            index=models.Index(fields=['decision', 'created_at'], name='ol_underwri_decisio_022711_idx'),
        ),
        migrations.AddConstraint(
            model_name='olmedicalrequirement',
            constraint=models.UniqueConstraint(fields=('underwriting_case', 'requirement_type'), name='ol_medical_requirement_unique_type'),
        ),
    ]
