# Generated by Django 5.0.14 on 2026-08-14 21:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinary_life', '0004_olbenefit_olmedicalrequirement_olrider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLUnderwritingDecisionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_decision', models.CharField(blank=True, max_length=20)),
                ('decision', models.CharField(max_length=20)),
                ('risk_class', models.CharField(blank=True, max_length=30)),
                ('reason', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordinary_life_underwriting_decision_events', to=settings.AUTH_USER_MODEL)),
                ('underwriting_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_events', to='ordinary_life.olunderwritingcase')),
            ],
            options={
                'db_table': 'ol_underwriting_decision_event',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['underwriting_case', 'created_at'], name='ol_underwri_underwr_6b1684_idx')],
            },
        ),
    ]
