# Generated by Django 5.0.14 on 2026-08-14 21:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinary_life', '0005_olunderwritingdecisionevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLPolicyRenewal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('renewal_number', models.CharField(max_length=100, unique=True)),
                ('requested_effective_date', models.DateField()),
                ('new_end_date', models.DateField()),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVAL_PENDING', 'Approval pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ol_policy_renewal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OLReinstatementRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(max_length=100, unique=True)),
                ('requested_effective_date', models.DateField()),
                ('arrears_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVAL_PENDING', 'Approval pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ol_reinstatement_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='olpaymentobligation',
            name='ol_payment_obligation_has_parent',
        ),
        migrations.AddField(
            model_name='olendorsement',
            name='after_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='olendorsement',
            name='applied_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_endorsements', to='ordinary_life.olpolicytransaction'),
        ),
        migrations.AddField(
            model_name='olendorsement',
            name='before_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='olpaymentobligation',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_obligations', to='ordinary_life.olpremiuminstallment'),
        ),
        migrations.AddField(
            model_name='olpolicytransaction',
            name='correlation_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='olpolicytransaction',
            name='external_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='olpolicytransaction',
            name='source_channel',
            field=models.CharField(default='SYSTEM', max_length=20),
        ),
        migrations.AlterField(
            model_name='olpolicytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('ISSUANCE', 'Issuance'), ('ENDORSEMENT', 'Endorsement'), ('PAYMENT', 'Payment'), ('LOAN', 'Loan'), ('WITHDRAWAL', 'Withdrawal'), ('SURRENDER', 'Surrender'), ('PAID_UP', 'Paid up'), ('REINSTATEMENT', 'Reinstatement'), ('RENEWAL', 'Renewal'), ('MATURITY', 'Maturity'), ('CANCELLATION', 'Cancellation'), ('STATUS_CHANGE', 'Status change')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='olpaymentobligation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('policy__isnull', True), ('proposal__isnull', False)), models.Q(('policy__isnull', False), ('proposal__isnull', True)), _connector='OR'), name='ol_payment_obligation_exactly_one_parent'),
        ),
        migrations.AddField(
            model_name='olpolicyrenewal',
            name='applied_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_renewals', to='ordinary_life.olpolicytransaction'),
        ),
        migrations.AddField(
            model_name='olpolicyrenewal',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_ordinary_life_renewals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='olpolicyrenewal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_ordinary_life_renewals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='olpolicyrenewal',
            name='payment_obligation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewal_requests', to='ordinary_life.olpaymentobligation'),
        ),
        migrations.AddField(
            model_name='olpolicyrenewal',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='ordinary_life.olpolicy'),
        ),
        migrations.AddField(
            model_name='olreinstatementrequest',
            name='applied_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_reinstatements', to='ordinary_life.olpolicytransaction'),
        ),
        migrations.AddField(
            model_name='olreinstatementrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_ordinary_life_reinstatements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='olreinstatementrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_ordinary_life_reinstatements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='olreinstatementrequest',
            name='payment_obligation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reinstatement_requests', to='ordinary_life.olpaymentobligation'),
        ),
        migrations.AddField(
            model_name='olreinstatementrequest',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reinstatement_requests', to='ordinary_life.olpolicy'),
        ),
        migrations.AddIndex(
            model_name='olpolicyrenewal',
            index=models.Index(fields=['policy', 'status'], name='ol_policy_r_policy__0aef87_idx'),
        ),
        migrations.AddConstraint(
            model_name='olpolicyrenewal',
            constraint=models.CheckConstraint(check=models.Q(('premium_amount__gt', 0)), name='ol_policy_renewal_positive_premium'),
        ),
        migrations.AddIndex(
            model_name='olreinstatementrequest',
            index=models.Index(fields=['policy', 'status'], name='ol_reinstat_policy__0ffabe_idx'),
        ),
        migrations.AddConstraint(
            model_name='olreinstatementrequest',
            constraint=models.CheckConstraint(check=models.Q(('arrears_amount__gt', 0)), name='ol_reinstatement_positive_arrears'),
        ),
    ]
