# Generated by Django 5.0.14 on 2026-08-14 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinary_life', '0006_olpolicyrenewal_olreinstatementrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oldocumentrecord',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='oldocumentrecord',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldocumentrecord',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_ordinary_life_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oldocumentrecord',
            name='status_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='olnote',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
