# Generated by Django 5.0.14 on 2026-06-30 04:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FOCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(help_text='Agent identifier', max_length=50)),
                ('policy_reference', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fo_commission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FOCommissionStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(default='DRAFT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fo_commission_statement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FOParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fo_parameter',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='FOPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_date', models.DateField()),
                ('recipient', models.CharField(max_length=200)),
                ('status', models.CharField(default='COMPLETED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fo_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FOReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_date', models.DateField()),
                ('reference', models.CharField(blank=True, help_text='e.g. Policy Number or Proposal ID', max_length=100, null=True)),
                ('status', models.CharField(default='COMPLETED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fo_receipt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FORequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requisition_number', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fo_requisition',
                'ordering': ['-created_at'],
            },
        ),
    ]
