# Generated by Django 5.0.14 on 2026-08-24 11:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_office', '0001_initial'),
        ('partner_onboarding', '0014_applicationpartnertype_kyc_status'),
        ('partners', '0011_partner_created_by_partner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('receipt_date', models.DateField(db_index=True)),
                ('branch_name_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('partner_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('payer_name', models.CharField(max_length=255)),
                ('payer_identity', models.CharField(blank=True, default='', help_text='National ID / TIN / policyholder identity snapshot.', max_length=100)),
                ('source_module', models.CharField(choices=[('OL_PROPOSAL', 'OL Proposal'), ('OL_POLICY', 'OL Policy'), ('GROUP_CREDIT', 'Group Credit'), ('MANUAL', 'Manual'), ('OTHER', 'Other')], db_index=True, default='MANUAL', max_length=30)),
                ('source_reference_type', models.CharField(blank=True, default='', help_text='e.g. PROPOSAL_NUMBER, COMMITMENT_NUMBER, POLICY_NUMBER.', max_length=60)),
                ('source_reference_id', models.CharField(blank=True, db_index=True, default='', help_text='Human reference of the source record (names, never UUIDs).', max_length=120)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=12)),
                ('receipt_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('unallocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank transfer'), ('CHEQUE', 'Cheque'), ('M-PESA', 'M-PESA'), ('OTHER', 'Other')], default='CASH', max_length=30)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=120)),
                ('bank_account_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('narration', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('PARTIALLY_ALLOCATED', 'Partially allocated'), ('FULLY_ALLOCATED', 'Fully allocated'), ('REVERSED', 'Reversed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('source_channel', models.CharField(choices=[('WEB', 'Web'), ('API', 'API'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('IMPORT', 'Import'), ('PORTAL', 'Portal'), ('BATCH', 'Batch'), ('MANUAL', 'Manual')], default='API', max_length=30)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='partners.partnerbankaccount')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='partner_onboarding.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='partners.partner')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_receipts', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_receipts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'db_table': 'front_office_receipt',
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('OL_COMMITMENT', 'OL Commitment'), ('OL_PROPOSAL', 'OL Proposal'), ('OL_POLICY', 'OL Policy'), ('MANUAL', 'Manual')], default='OL_COMMITMENT', max_length=30)),
                ('target_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('target_display', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=12)),
                ('allocation_status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVERSED', 'Reversed'), ('VOID', 'Void')], db_index=True, default='ACTIVE', max_length=30)),
                ('narration', models.TextField(blank=True, default='')),
                ('allocated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_channel', models.CharField(choices=[('WEB', 'Web'), ('API', 'API'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('IMPORT', 'Import'), ('PORTAL', 'Portal'), ('BATCH', 'Batch'), ('MANUAL', 'Manual')], default='API', max_length=30)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_receipts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='front_office.receipt')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_allocations', to='front_office.receiptallocation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt Allocation',
                'verbose_name_plural': 'Receipt Allocations',
                'db_table': 'front_office_receipt_allocation',
                'ordering': ['-allocated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(default='RECEIPT', max_length=60)),
                ('document_number', models.CharField(blank=True, default='', help_text='Future government control number (e.g. TRA GST).', max_length=120)),
                ('file_reference', models.CharField(blank=True, default='', max_length=255)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='UPLOADED', max_length=30)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='front_office.receipt')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_receipt_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt Document',
                'verbose_name_plural': 'Receipt Documents',
                'db_table': 'front_office_receipt_document',
                'ordering': ['-uploaded_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptReversal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reversal_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('reason', models.TextField()),
                ('reversed_allocations', models.JSONField(blank=True, default=list)),
                ('reversed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='front_office.receipt')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_receipt_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt Reversal',
                'verbose_name_plural': 'Receipt Reversals',
                'db_table': 'front_office_receipt_reversal',
                'ordering': ['-reversed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, default='', max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_channel', models.CharField(choices=[('WEB', 'Web'), ('API', 'API'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('IMPORT', 'Import'), ('PORTAL', 'Portal'), ('BATCH', 'Batch'), ('MANUAL', 'Manual')], default='API', max_length=30)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_status_changes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='front_office.receipt')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt Status History',
                'verbose_name_plural': 'Receipt Status History',
                'db_table': 'front_office_receipt_status_history',
                'ordering': ['-changed_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['status', 'receipt_date'], name='receipt_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['branch', 'receipt_date'], name='receipt_branch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['source_module', 'source_reference_id'], name='receipt_source_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['partner', 'receipt_date'], name='receipt_partner_date_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['currency', 'receipt_date'], name='receipt_currency_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(check=models.Q(('receipt_amount__gt', 0)), name='receipt_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(check=models.Q(('exchange_rate__gt', 0)), name='receipt_exchange_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(check=models.Q(('allocated_amount__gte', 0)), name='receipt_allocated_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(check=models.Q(('unallocated_amount__gte', 0)), name='receipt_unallocated_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='receiptallocation',
            index=models.Index(fields=['receipt', 'target_type', 'target_id'], name='receipt_alloc_target_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptallocation',
            index=models.Index(fields=['receipt', 'allocation_status'], name='receipt_alloc_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='receiptallocation',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='receipt_allocation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='receiptallocation',
            constraint=models.CheckConstraint(check=models.Q(('exchange_rate__gt', 0)), name='receipt_allocation_rate_positive'),
        ),
        migrations.AddIndex(
            model_name='receiptdocument',
            index=models.Index(fields=['receipt', 'document_type'], name='receipt_document_type_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptreversal',
            index=models.Index(fields=['receipt', 'reversed_at'], name='receipt_reversal_receipt_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptstatushistory',
            index=models.Index(fields=['receipt', 'changed_at'], name='receipt_status_history_idx'),
        ),
    ]
