# Generated by Django 5.0.14 on 2026-08-24 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_office', '0002_receipt_receiptallocation_receiptdocument_and_more'),
        ('partner_onboarding', '0014_applicationpartnertype_kyc_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=60)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_bank_accounts', to='partner_onboarding.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Bank Account',
                'verbose_name_plural': 'Company Bank Accounts',
                'db_table': 'front_office_company_bank_account',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptNumberingRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('prefix', models.CharField(max_length=20)),
                ('sequence_padding', models.PositiveSmallIntegerField(default=6)),
                ('next_sequence', models.PositiveBigIntegerField(default=1)),
                ('reset_frequency', models.CharField(choices=[('NEVER', 'Never'), ('YEARLY', 'Yearly'), ('MONTHLY', 'Monthly'), ('DAILY', 'Daily')], default='YEARLY', max_length=20)),
                ('last_reset_at', models.DateTimeField(blank=True, help_text='Used to detect period rollover for the reset frequency.', null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch-specific rule; empty means the default rule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_numbering_rules', to='partner_onboarding.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt Numbering Rule',
                'verbose_name_plural': 'Receipt Numbering Rules',
                'db_table': 'front_office_receipt_numbering_rule',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptPaymentModeRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_mode', models.CharField(db_index=True, max_length=30, unique=True)),
                ('requires_reference', models.BooleanField(default=False)),
                ('requires_bank_account', models.BooleanField(default=False)),
                ('allows_cash', models.BooleanField(default=False)),
                ('allows_card', models.BooleanField(default=False)),
                ('allows_mobile_money', models.BooleanField(default=False)),
                ('allows_bank_transfer', models.BooleanField(default=False)),
                ('allows_cheque', models.BooleanField(default=False)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt Payment Mode Rule',
                'verbose_name_plural': 'Receipt Payment Mode Rules',
                'db_table': 'front_office_receipt_payment_mode_rule',
                'ordering': ['payment_mode'],
            },
        ),
    ]
