# Generated by Django 5.0.14 on 2026-08-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front_office", "0004_alter_receipt_receipt_number"),
        ("ol_commitments", "0002_olcommitment_lapse_review_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptallocation",
            name="commitment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipt_allocations",
                to="ol_commitments.olcommitment",
            ),
        ),
        migrations.AddField(
            model_name="receiptallocation",
            name="ol_commitment_allocation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipt_allocations",
                to="ol_commitments.olcommitmentallocation",
            ),
        ),
    ]
