# Generated by Django 5.0.14 on 2026-08-24 21:04

import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_office', '0005_receiptallocation_commitment_links'),
        ('ol_commitments', '0003_olcommitmentallocation_converted_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('effective_date', models.DateField()),
                ('source', models.CharField(default='MANUAL', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'db_table': 'front_office_exchange_rate',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='receiptallocation',
            name='converted_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='receiptallocation',
            name='converted_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='receiptallocation',
            name='exchange_rate_source',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='receiptallocation',
            name='exchange_rate_used',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='receiptallocation',
            constraint=models.CheckConstraint(check=models.Q(('exchange_rate_used__gt', 0)), name='receipt_allocation_rate_used_positive'),
        ),
        migrations.AddConstraint(
            model_name='receiptallocation',
            constraint=models.CheckConstraint(check=models.Q(('converted_amount__gte', 0)), name='receipt_allocation_converted_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['from_currency', 'to_currency', 'effective_date'], name='exchange_rate_pair_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.CheckConstraint(check=models.Q(('rate__gt', 0)), name='exchange_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('from_currency', 'to_currency', 'effective_date'), name='exchange_rate_pair_date_unique'),
        ),
    ]
