# Generated by Django 5.0.14 on 2026-08-25 02:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_office', '0006_exchangerate_receiptallocation_converted_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptdocument',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptdocument',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_receipt_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptdocument',
            name='html_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='receiptdocument',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='receiptdocument',
            name='template_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receiptdocument',
            name='mime_type',
            field=models.CharField(blank=True, default='application/pdf', max_length=100),
        ),
        migrations.AlterField(
            model_name='receiptdocument',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('GENERATED', 'Generated')], db_index=True, default='UPLOADED', max_length=30),
        ),
        migrations.CreateModel(
            name='ReceiptPrintTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, default='')),
                ('template_html', models.TextField()),
                ('layout_variables', models.JSONField(blank=True, default=dict)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Receipt Print Template',
                'verbose_name_plural': 'Receipt Print Templates',
                'db_table': 'front_office_receipt_print_template',
                'ordering': ['code', '-version'],
                'indexes': [models.Index(fields=['code', 'is_active', 'effective_from', 'effective_to'], name='receipt_print_tpl_active_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='receiptprinttemplate',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='receipt_print_template_code_version_uq'),
        ),
        migrations.AddField(
            model_name='receiptdocument',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='front_office.receiptprinttemplate'),
        ),
        migrations.AddIndex(
            model_name='receiptdocument',
            index=models.Index(fields=['receipt', 'status', 'template_version'], name='receipt_doc_tpl_ver_idx'),
        ),
    ]
