# Generated by Django 5.0.14 on 2026-08-25 03:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_office', '0007_receiptdocument_generated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptImportBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(db_index=True, max_length=60, unique=True)),
                ('import_mode', models.CharField(choices=[('DRAFT', 'Draft only'), ('POST', 'Draft and post'), ('ALLOCATE', 'Draft, post and allocate')], default='DRAFT', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('COMMITTED', 'Committed'), ('PARTIAL', 'Partially committed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=30)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('committed_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt Import Batch',
                'verbose_name_plural': 'Receipt Import Batches',
                'db_table': 'front_office_receipt_import_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptImportRow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField(db_index=True)),
                ('row_hash', models.CharField(db_index=True, max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid'), ('COMMITTED', 'Committed'), ('FAILED', 'Failed'), ('DUPLICATE', 'Duplicate')], db_index=True, default='PENDING', max_length=30)),
                ('validation_errors', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=60)),
                ('error_message', models.TextField(blank=True, default='')),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='front_office.receiptimportbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='front_office.receipt')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt Import Row',
                'verbose_name_plural': 'Receipt Import Rows',
                'db_table': 'front_office_receipt_import_row',
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='receiptimportbatch',
            index=models.Index(fields=['status', 'created_at'], name='imp_batch_status_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptimportbatch',
            index=models.Index(fields=['import_mode', 'status'], name='imp_batch_mode_status_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptimportrow',
            index=models.Index(fields=['batch', 'status'], name='imp_row_batch_status_idx'),
        ),
    ]
