# Generated by Django 5.0.14 on 2026-08-25 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_office', '0009_receiptnotificationlog_and_more'),
        ('partner_onboarding', '0014_applicationpartnertype_kyc_status'),
        ('partners', '0011_partner_created_by_partner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['payment_mode', 'receipt_date'], name='receipt_payment_mode_date_idx'),
        ),
    ]
