# Generated by Django 5.0.14 on 2026-08-26 12:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ol_proposals', '0008_olproposalnotificationlog_and_more'),
        ('partners', '0011_partner_created_by_partner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_number', models.CharField(blank=True, db_index=True, max_length=40, unique=True)),
                ('product_plan_ref', models.CharField(help_text='Immutable product/plan code or reference captured at issuance.', max_length=160)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('sum_assured', models.DecimalField(decimal_places=2, max_digits=18)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('premium_frequency', models.CharField(max_length=30)),
                ('term_years', models.PositiveIntegerField()),
                ('risk_commencement_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('LAPSED', 'Lapsed'), ('PAID_UP', 'Paid-up'), ('SURRENDER_PENDING', 'Surrender pending'), ('SURRENDERED', 'Surrendered'), ('MATURED_PENDING_PAYMENT', 'Matured pending payment'), ('MATURED', 'Matured'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('CLAIM_SETTLED', 'Claim settled'), ('TERMINATED', 'Terminated')], db_index=True, default='ACTIVE', max_length=35)),
                ('first_premium_receipt_ref', models.CharField(blank=True, default='', max_length=160)),
                ('contract_snapshot', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_policy_agents', to='partners.partner')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ol_policyholders', to='partners.partner')),
                ('proposal_ref', models.ForeignKey(db_column='proposal_ref_id', on_delete=django.db.models.deletion.PROTECT, related_name='issued_policy_snapshots', to='ol_proposals.olproposal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_policies_policy',
                'ordering': ['-created_at', 'policy_number'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('from_status', models.CharField(blank=True, default='', max_length=35)),
                ('to_status', models.CharField(blank=True, default='', max_length=35)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('source_channel', models.CharField(choices=[('WEB', 'Web'), ('API', 'API'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('BATCH', 'Batch'), ('PORTAL', 'Portal'), ('IMPORT', 'Import')], default='SYSTEM', max_length=20)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=100)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_policy_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='ol_policies.policy')),
            ],
            options={
                'db_table': 'ol_policies_policy_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('benefit_type', models.CharField(max_length=100)),
                ('calculation_basis', models.CharField(max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benefits', to='ol_policies.policy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_policies_policy_benefit',
                'ordering': ['benefit_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyEndorsement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endorsement_number', models.CharField(blank=True, db_index=True, max_length=45, unique=True)),
                ('endorsement_type', models.CharField(choices=[('PREMIUM_CHANGE', 'Premium change'), ('TERM_CHANGE', 'Term change'), ('MEMBER_ADD', 'Member add'), ('MEMBER_REMOVE', 'Member remove'), ('BENEFICIARY_CHANGE', 'Beneficiary change'), ('ADDRESS_CHANGE', 'Address change'), ('CHANGE_BENEFIT', 'Change benefit'), ('SURRENDER', 'Surrender'), ('OTHER', 'Other')], max_length=40)),
                ('effective_date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('APPLIED', 'Applied'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=25)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('source_channel', models.CharField(choices=[('WEB', 'Web'), ('API', 'API'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('BATCH', 'Batch'), ('PORTAL', 'Portal'), ('IMPORT', 'Import')], default='API', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endorsements', to='ol_policies.policy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_policies_policy_endorsement',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_relation', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=30)),
                ('benefit_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='ol_policies.policy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_policies_policy_member',
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyRider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider_code', models.CharField(max_length=100)),
                ('sum_assured', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('premium', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riders', to='ol_policies.policy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_policies_policy_rider',
                'ordering': ['rider_code', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['status', 'maturity_date'], name='ol_policy_status_maturity_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['partner', 'status'], name='ol_policy_partner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['agent', 'status'], name='ol_policy_agent_status_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['currency', 'status'], name='ol_policy_currency_status_idx'),
        ),
        migrations.AddIndex(
            model_name='policyauditlog',
            index=models.Index(fields=['policy', 'created_at'], name='ol_pol_audit_pol_ct_idx'),
        ),
        migrations.AddIndex(
            model_name='policyauditlog',
            index=models.Index(fields=['event_type', 'created_at'], name='ol_pol_audit_evt_ct_idx'),
        ),
        migrations.AddIndex(
            model_name='policybenefit',
            index=models.Index(fields=['policy', 'benefit_type'], name='ol_policy_benefit_type_idx'),
        ),
        migrations.AddIndex(
            model_name='policyendorsement',
            index=models.Index(fields=['policy', 'status'], name='ol_pol_endorse_st_idx'),
        ),
        migrations.AddIndex(
            model_name='policymember',
            index=models.Index(fields=['policy', 'member_relation'], name='ol_policy_member_relation_idx'),
        ),
        migrations.AddIndex(
            model_name='policyrider',
            index=models.Index(fields=['policy', 'rider_code'], name='ol_policy_rider_code_idx'),
        ),
    ]
