# Generated by Django 5.0.14 on 2026-08-26 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_policies', '0001_initial'),
        ('ol_proposals', '0008_olproposalnotificationlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='proposal_ref',
            field=models.OneToOneField(db_column='proposal_ref_id', on_delete=django.db.models.deletion.PROTECT, related_name='issued_policy_snapshot', to='ol_proposals.olproposal'),
        ),
    ]
