# Generated by Django 5.0.14 on 2026-08-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_policies', '0002_alter_policy_proposal_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='policymember',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policymember',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
