# Generated by Django 5.0.14 on 2026-08-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_policies', '0003_policymember_ended_at_policymember_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='expired_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='lapsed_at',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='reinstated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
