# Generated by Django 5.0.14 on 2026-08-26 12:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_office', '0010_receipt_receipt_payment_mode_date_idx'),
        ('ol_policies', '0004_policy_expired_at_policy_lapsed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurrenderRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('request_date', models.DateField(default=django.utils.timezone.localdate)),
                ('surrender_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('outstanding_loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_surrender_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PENDING_PAYMENT', 'Pending payment'), ('PAID', 'Paid'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING_PAYMENT', max_length=25)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('payment_requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_policy_surrenders', to='front_office.forequisition')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surrender_requests', to='ol_policies.policy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_policies_surrender_request',
                'ordering': ['-request_date', '-created_at'],
                'indexes': [models.Index(fields=['policy', 'status'], name='ol_policy_surr_st_idx')],
            },
        ),
    ]
