# Generated by Django 5.0.14 on 2026-08-26 12:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_office', '0010_receipt_receipt_payment_mode_date_idx'),
        ('ol_policies', '0005_surrenderrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('requested_at', models.DateField(default=django.utils.timezone.localdate)),
                ('approved_at', models.DateField(blank=True, null=True)),
                ('disbursed_at', models.DateField(blank=True, null=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('outstanding_principal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('accrued_interest', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('outstanding_interest', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('interest_rate', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed'), ('PARTIALLY_REPAID', 'Partially repaid'), ('REPAID', 'Repaid'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], db_index=True, default='REQUESTED', max_length=25)),
                ('approval_required', models.BooleanField(default=False)),
                ('repayment_options', models.JSONField(blank=True, default=list)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('payment_requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_policy_loans', to='front_office.forequisition')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='ol_policies.policy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_policies_policy_loan',
                'ordering': ['-requested_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyLoanRepayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repayment_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_component', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('principal_component', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='ol_policies.policyloan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_policies_policy_loan_repayment',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('request_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cash_value_before', models.DecimalField(decimal_places=2, max_digits=18)),
                ('loan_balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=25)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('payment_requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_policy_withdrawals', to='front_office.forequisition')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='ol_policies.policy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_policies_withdrawal_request',
                'ordering': ['-request_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='policyloan',
            index=models.Index(fields=['policy', 'status'], name='ol_policy_loan_st_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['policy', 'status'], name='ol_policy_withdrawal_st_idx'),
        ),
    ]
