# Generated by Django 5.0.14 on 2026-08-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_policies', '0006_policyloan_policyloanrepayment_withdrawalrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyloan',
            name='last_interest_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
