# Generated by Django 5.0.14 on 2026-08-26 12:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_office', '0010_receipt_receipt_payment_mode_date_idx'),
        ('ol_policies', '0007_policyloan_last_interest_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaturityClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('claim_date', models.DateField(default=django.utils.timezone.localdate)),
                ('maturity_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_payout', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payout_method', models.CharField(default='BANK_TRANSFER', max_length=40)),
                ('status', models.CharField(choices=[('PENDING_DOCUMENTS', 'Pending documents'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('DECLINED', 'Declined')], db_index=True, default='PENDING_APPROVAL', max_length=30)),
                ('approval_required', models.BooleanField(default=True)),
                ('documents_required', models.BooleanField(default=True)),
                ('documents_verified', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('payment_requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_policy_maturity_claims', to='front_office.forequisition')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maturity_claims', to='ol_policies.policy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_policies_maturity_claim',
                'ordering': ['-claim_date', '-created_at'],
                'indexes': [models.Index(fields=['policy', 'status'], name='ol_policy_maturity_st_idx')],
            },
        ),
    ]
