# Generated by Django 5.0.14 on 2026-08-26 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_policies', '0008_maturityclaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyNotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('channel', models.CharField(max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('external_key', models.CharField(max_length=180)),
                ('status', models.CharField(db_index=True, default='QUEUED', max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_logs', to='ol_policies.policy')),
            ],
            options={
                'db_table': 'ol_policies_policy_notification_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['policy', 'event_type'], name='ol_policy_notif_event_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='policynotificationlog',
            constraint=models.UniqueConstraint(fields=('external_key', 'channel', 'recipient'), name='ol_policy_notification_key_uq'),
        ),
    ]
