# Generated by Django 5.1 on 2026-08-27 16:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ol_policies", "0009_policynotificationlog_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="cash_value_after",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="fee_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="fee_basis",
            field=models.CharField(default="NONE", max_length=40),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="fee_rate",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="idempotency_key",
            field=models.CharField(blank=True, db_index=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="payment_mode",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="receipt_reference",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="reversed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="approval_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="cancellation_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="reversal_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="status",
            field=models.CharField(choices=[("REQUESTED", "Requested"), ("APPROVED", "Approved"), ("PROCESSING", "Processing payout"), ("PAID", "Paid"), ("REVERSED", "Reversed"), ("DECLINED", "Declined"), ("CANCELLED", "Cancelled")], default="REQUESTED", max_length=25),
        ),
        migrations.CreateModel(
            name="WithdrawalPayment",
            fields=[
                ("id", models.UUIDField(default=__import__("uuid").uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payment_mode", models.CharField(max_length=50)),
                ("receipt_reference", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="TZS", max_length=3)),
                ("payment_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(default="COMPLETED", max_length=25)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL)),
                ("withdrawal", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="ol_policies.withdrawalrequest")),
            ],
            options={
                "db_table": "ol_policies_withdrawal_payment",
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="withdrawalpayment",
            index=models.Index(fields=["withdrawal", "status"], name="ol_withdrawal_payment_st_idx"),
        ),
        migrations.AddConstraint(
            model_name="withdrawalpayment",
            constraint=models.UniqueConstraint(fields=("withdrawal", "receipt_reference"), name="ol_withdrawal_payment_receipt_uq"),
        ),
    ]
