# Generated by Django 5.0.14 on 2026-08-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_policies', '0010_withdrawal_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrider',
            name='exhausted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policyrider',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXHAUSTED', 'Exhausted')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('LAPSED', 'Lapsed'), ('PAID_UP', 'Paid-up'), ('SURRENDER_PENDING', 'Surrender pending'), ('SURRENDERED', 'Surrendered'), ('MATURED_PENDING_PAYMENT', 'Matured pending payment'), ('MATURED', 'Matured'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('CLAIM_SETTLED', 'Claim settled'), ('MATURITY_SETTLED', 'Maturity settled'), ('TERMINATED', 'Terminated')], db_index=True, default='ACTIVE', max_length=35),
        ),
    ]
