# Generated by Django 5.0.14 on 2026-09-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_policies', '0011_policyrider_exhausted_at_policyrider_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maturityclaim',
            name='status',
            field=models.CharField(choices=[('PENDING_DOCUMENTS', 'Pending documents'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('PAID_VIA_INSTALLMENTS', 'Paid via Installments'), ('DECLINED', 'Declined')], db_index=True, default='PENDING_APPROVAL', max_length=30),
        ),
    ]
