# Generated by Django 5.0.14 on 2026-06-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Permission Group',
                'verbose_name_plural': 'Permission Groups',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.permissiongroup',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
            ],
            options={
                'verbose_name': 'User Group',
                'verbose_name_plural': 'User Groups',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.usergroup',),
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.userpermission',),
        ),
    ]
