# Generated by Django 5.0.14 on 2026-06-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
        ('users', '0002_notificationpreference_user_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.notificationpreference',),
        ),
    ]
