# Generated by Django 5.0.14 on 2026-08-26 19:29

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ol_policies', '0009_policynotificationlog_and_more'),
        ('partners', '0011_partner_created_by_partner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLLoan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('interest_rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('compounding_frequency', models.CharField(max_length=40)),
                ('term_months', models.PositiveIntegerField()),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed'), ('ACTIVE', 'Active'), ('PARTIALLY_REPAID', 'Partially repaid'), ('SETTLED', 'Settled'), ('DEFAULTED', 'Defaulted'), ('OFFSET_ON_SURRENDER', 'Offset on surrender'), ('OFFSET_ON_MATURITY', 'Offset on maturity'), ('OFFSET_ON_CLAIM', 'Offset on claim'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], db_index=True, default='REQUESTED', max_length=30)),
                ('total_repaid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('outstanding_balance', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('approval_required', models.BooleanField(db_index=True, default=False)),
                ('reason', models.TextField(blank=True, default='')),
                ('source_channel', models.CharField(choices=[('WEB', 'Web'), ('API', 'API'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('IMPORT', 'Import'), ('PORTAL', 'Portal'), ('BATCH', 'Batch'), ('MANUAL', 'Manual')], default='SYSTEM', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ol_loans', to='partners.partner')),
                ('policy_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ol_loans', to='ol_policies.policy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OL Loan',
                'verbose_name_plural': 'OL Loans',
                'db_table': 'ol_loans_loan',
                'ordering': ['-created_at', 'loan_number'],
            },
        ),
        migrations.CreateModel(
            name='OLLoanInterestAccrual',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('principal_base', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('cumulative_interest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('source_channel', models.CharField(choices=[('WEB', 'Web'), ('API', 'API'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('IMPORT', 'Import'), ('PORTAL', 'Portal'), ('BATCH', 'Batch'), ('MANUAL', 'Manual')], default='SYSTEM', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_accruals', to='ol_loans.olloan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_loans_interest_accrual',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OLLoanOffset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SURRENDER', 'Surrender'), ('MATURITY', 'Maturity'), ('CLAIM', 'Claim')], db_index=True, max_length=20)),
                ('source_id', models.CharField(db_index=True, max_length=120)),
                ('offset_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('remaining_payout', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reason', models.TextField(blank=True, default='')),
                ('source_channel', models.CharField(choices=[('WEB', 'Web'), ('API', 'API'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('IMPORT', 'Import'), ('PORTAL', 'Portal'), ('BATCH', 'Batch'), ('MANUAL', 'Manual')], default='SYSTEM', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offsets', to='ol_loans.olloan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_loans_offset',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OLLoanRepayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_ref', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=Decimal('1.00000000'), max_digits=18)),
                ('allocation_breakdown', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('source_channel', models.CharField(choices=[('WEB', 'Web'), ('API', 'API'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('IMPORT', 'Import'), ('PORTAL', 'Portal'), ('BATCH', 'Batch'), ('MANUAL', 'Manual')], default='SYSTEM', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='ol_loans.olloan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_loans_repayment',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OLLoanSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField(db_index=True)),
                ('principal_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('interest_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('penalty_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30)),
                ('reason', models.TextField(blank=True, default='')),
                ('source_channel', models.CharField(choices=[('WEB', 'Web'), ('API', 'API'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('IMPORT', 'Import'), ('PORTAL', 'Portal'), ('BATCH', 'Batch'), ('MANUAL', 'Manual')], default='SYSTEM', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='ol_loans.olloan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_loans_schedule',
                'ordering': ['installment_number'],
            },
        ),
        migrations.AddIndex(
            model_name='olloan',
            index=models.Index(fields=['policy_ref', 'status'], name='ol_loan_policy_status_idx'),
        ),
        migrations.AddIndex(
            model_name='olloan',
            index=models.Index(fields=['partner', 'status'], name='ol_loan_partner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='olloan',
            index=models.Index(fields=['status', 'maturity_date'], name='ol_loan_status_maturity_idx'),
        ),
        migrations.AddIndex(
            model_name='olloan',
            index=models.Index(fields=['currency', 'status'], name='ol_loan_currency_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='olloan',
            constraint=models.CheckConstraint(check=models.Q(('principal_amount__gt', 0)), name='ol_loan_principal_positive'),
        ),
        migrations.AddConstraint(
            model_name='olloan',
            constraint=models.CheckConstraint(check=models.Q(('disbursed_amount__gte', 0)), name='ol_loan_disbursed_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olloan',
            constraint=models.CheckConstraint(check=models.Q(('interest_rate__gte', 0)), name='ol_loan_interest_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olloan',
            constraint=models.CheckConstraint(check=models.Q(('term_months__gt', 0)), name='ol_loan_term_positive'),
        ),
        migrations.AddConstraint(
            model_name='olloan',
            constraint=models.CheckConstraint(check=models.Q(('total_repaid__gte', 0)), name='ol_loan_repaid_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olloan',
            constraint=models.CheckConstraint(check=models.Q(('outstanding_balance__gte', 0)), name='ol_loan_outstanding_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='olloaninterestaccrual',
            index=models.Index(fields=['loan', 'period_end'], name='ol_loan_accrual_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='olloaninterestaccrual',
            constraint=models.UniqueConstraint(fields=('loan', 'period_start', 'period_end'), name='ol_loan_accrual_period_unique'),
        ),
        migrations.AddConstraint(
            model_name='olloaninterestaccrual',
            constraint=models.CheckConstraint(check=models.Q(('principal_base__gte', 0)), name='ol_loan_accrual_base_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olloaninterestaccrual',
            constraint=models.CheckConstraint(check=models.Q(('interest_amount__gte', 0)), name='ol_loan_accrual_interest_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olloaninterestaccrual',
            constraint=models.CheckConstraint(check=models.Q(('penalty_amount__gte', 0)), name='ol_loan_accrual_penalty_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olloaninterestaccrual',
            constraint=models.CheckConstraint(check=models.Q(('cumulative_interest__gte', 0)), name='ol_loan_accrual_cumulative_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='olloanoffset',
            index=models.Index(fields=['source_type', 'source_id'], name='ol_loan_offset_source_idx'),
        ),
        migrations.AddIndex(
            model_name='olloanoffset',
            index=models.Index(fields=['loan', 'created_at'], name='ol_loan_offset_loan_idx'),
        ),
        migrations.AddConstraint(
            model_name='olloanoffset',
            constraint=models.UniqueConstraint(fields=('loan', 'source_type', 'source_id'), name='ol_loan_offset_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='olloanoffset',
            constraint=models.CheckConstraint(check=models.Q(('offset_amount__gt', 0)), name='ol_loan_offset_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='olloanoffset',
            constraint=models.CheckConstraint(check=models.Q(('remaining_payout__gte', 0)), name='ol_loan_offset_payout_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='olloanrepayment',
            index=models.Index(fields=['loan', 'created_at'], name='ol_loan_repayment_created_idx'),
        ),
        migrations.AddIndex(
            model_name='olloanrepayment',
            index=models.Index(fields=['receipt_ref'], name='ol_loan_repayment_receipt_idx'),
        ),
        migrations.AddConstraint(
            model_name='olloanrepayment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='ol_loan_repayment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='olloanrepayment',
            constraint=models.CheckConstraint(check=models.Q(('exchange_rate__gt', 0)), name='ol_loan_repayment_rate_positive'),
        ),
        migrations.AddIndex(
            model_name='olloanschedule',
            index=models.Index(fields=['loan', 'due_date'], name='ol_loan_schedule_due_idx'),
        ),
        migrations.AddIndex(
            model_name='olloanschedule',
            index=models.Index(fields=['status', 'due_date'], name='ol_loan_sched_status_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='olloanschedule',
            constraint=models.UniqueConstraint(fields=('loan', 'installment_number'), name='ol_loan_schedule_installment_unique'),
        ),
        migrations.AddConstraint(
            model_name='olloanschedule',
            constraint=models.CheckConstraint(check=models.Q(('installment_number__gt', 0)), name='ol_loan_schedule_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='olloanschedule',
            constraint=models.CheckConstraint(check=models.Q(('principal_due__gte', 0)), name='ol_loan_schedule_principal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olloanschedule',
            constraint=models.CheckConstraint(check=models.Q(('interest_due__gte', 0)), name='ol_loan_schedule_interest_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olloanschedule',
            constraint=models.CheckConstraint(check=models.Q(('penalty_due__gte', 0)), name='ol_loan_schedule_penalty_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olloanschedule',
            constraint=models.CheckConstraint(check=models.Q(('amount_paid__gte', 0)), name='ol_loan_schedule_paid_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olloanschedule',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', 0)), name='ol_loan_schedule_balance_nonnegative'),
        ),
    ]
