# Generated by Django 5.0.14 on 2026-08-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ol_loans', '0001_initial'),
        ('ol_parameters', '0019_olproposaldocumentrequirement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OLLoanInterestControlDiagnostic',
            fields=[
            ],
            options={
                'verbose_name': 'Loan Interest Control Diagnostic',
                'verbose_name_plural': 'Loan Interest Control Diagnostics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ol_parameters.olloaninterestcontrol',),
        ),
        migrations.CreateModel(
            name='OLLoanSystemSetupDiagnostic',
            fields=[
            ],
            options={
                'verbose_name': 'Loan System Setup Diagnostic',
                'verbose_name_plural': 'Loan System Setup Diagnostics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ol_parameters.olloansystemsetup',),
        ),
    ]
