# Generated by Django 5.0.14 on 2026-08-26 20:25

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_loans', '0002_olloaninterestcontroldiagnostic_and_more'),
        ('ol_policies', '0009_policynotificationlog_and_more'),
        ('partners', '0011_partner_created_by_partner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='olloan',
            name='cash_value_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='olloan',
            name='repayment_mode',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='olloan',
            constraint=models.CheckConstraint(check=models.Q(('cash_value_snapshot__gte', 0)), name='ol_loan_cash_value_nonnegative'),
        ),
    ]
