# Generated by Django 5.0.14 on 2026-08-26 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_auditlog_quick_create_source_channel'),
        ('ol_loans', '0003_olloan_cash_value_snapshot_olloan_repayment_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='olloan',
            name='approval_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_loan', to='governance.approvalrequest'),
        ),
        migrations.AddField(
            model_name='olloan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olloan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ol_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='olloan',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olloan',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_ol_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='olloan',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
