# Generated by Django 5.0.14 on 2026-08-26 21:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_office', '0010_receipt_receipt_payment_mode_date_idx'),
        ('ol_loans', '0004_olloan_approval_request_olloan_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLLoanDisbursement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('payment_mode', models.CharField(max_length=40)),
                ('bank_account_code', models.CharField(blank=True, default='', max_length=50)),
                ('disbursement_date', models.DateField()),
                ('status', models.CharField(db_index=True, default='RELEASED', max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=120, unique=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('source_channel', models.CharField(choices=[('WEB', 'Web'), ('API', 'API'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('IMPORT', 'Import'), ('PORTAL', 'Portal'), ('BATCH', 'Batch'), ('MANUAL', 'Manual')], default='API', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disbursement', to='ol_loans.olloan')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ol_loan_disbursements', to='front_office.forequisition')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_loans_disbursement',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['loan', 'disbursement_date'], name='ol_loan_disb_loan_date_idx'), models.Index(fields=['status', 'disbursement_date'], name='ol_loan_disb_status_date_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='olloandisbursement',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='ol_loan_disbursement_amount_positive'),
        ),
    ]
