# Generated by Django 5.0.14 on 2026-08-26 21:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_office', '0010_receipt_receipt_payment_mode_date_idx'),
        ('ol_loans', '0005_olloandisbursement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='olloanrepayment',
            name='receipt_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_loan_repayments', to='front_office.receiptallocation'),
        ),
        migrations.AddField(
            model_name='olloanschedule',
            name='interest_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='olloanschedule',
            name='penalty_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='olloanschedule',
            name='principal_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddConstraint(
            model_name='olloanschedule',
            constraint=models.CheckConstraint(check=models.Q(('principal_paid__gte', 0)), name='ol_loan_schedule_principal_paid_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olloanschedule',
            constraint=models.CheckConstraint(check=models.Q(('interest_paid__gte', 0)), name='ol_loan_schedule_interest_paid_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olloanschedule',
            constraint=models.CheckConstraint(check=models.Q(('penalty_paid__gte', 0)), name='ol_loan_schedule_penalty_paid_nonnegative'),
        ),
    ]
