# Generated by Django 5.0.14 on 2026-08-27 18:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ol_policies', '0010_withdrawal_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.CharField(blank=True, db_index=True, max_length=45, unique=True)),
                ('claim_type', models.CharField(db_index=True, max_length=80)),
                ('claim_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('admitted_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('PENDING_MEDICAL', 'Pending medical review'), ('ASSESSMENT', 'Assessment'), ('ASSESSED', 'Assessed'), ('REQUISITION', 'Requisition'), ('REQUISITIONED', 'Requisitioned'), ('APPROVED', 'Approved'), ('SETTLED', 'Settled'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='REGISTERED', max_length=30)),
                ('cause_of_claim', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('assessment_notes', models.TextField(blank=True, default='')),
                ('fraud_flag', models.BooleanField(db_index=True, default=False)),
                ('settled_date', models.DateField(blank=True, null=True)),
                ('source_channel', models.CharField(choices=[('API', 'API'), ('WEB', 'Web'), ('PORTAL', 'Portal'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('BATCH', 'Batch')], db_index=True, default='API', max_length=20)),
                ('admitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_claims_admitted', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('policy_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ol_claims', to='ol_policies.policy')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_claims_registered', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_claims_claim',
                'ordering': ['-created_at', 'claim_number'],
            },
        ),
        migrations.CreateModel(
            name='OLClaimant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimant_type', models.CharField(choices=[('POLICYHOLDER', 'Policyholder'), ('INSURED', 'Insured'), ('DEPENDENT', 'Dependent')], db_index=True, max_length=20)),
                ('relationship', models.CharField(blank=True, default='', max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('identity_number', models.CharField(blank=True, default='', max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimants', to='ol_claims.olclaim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_claims_claimant',
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='olclaim',
            name='claimant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_claims', to='ol_claims.olclaimant'),
        ),
        migrations.CreateModel(
            name='OLClaimDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(db_index=True, max_length=100)),
                ('file_reference', models.CharField(max_length=500)),
                ('mandatory_flag', models.BooleanField(db_index=True, default=False)),
                ('upload_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ol_claims.olclaim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_claim_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_claims_claim_document',
                'ordering': ['document_type', '-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='OLClaimFileNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_text', models.TextField()),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_notes', to='ol_claims.olclaim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_claims_claim_file_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OLClaimItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('benefit_type', models.CharField(db_index=True, max_length=100)),
                ('sum_assured', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('adjustment_reason', models.TextField(blank=True, default='')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ol_claims.olclaim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_claims_claim_item',
                'ordering': ['benefit_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OLClaimRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requisition_number', models.CharField(blank=True, db_index=True, max_length=55, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bank_details_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REQUISITIONED', 'Requisitioned'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=25)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='requisition', to='ol_claims.olclaim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_claims_claim_requisition',
                'ordering': ['-created_at', 'requisition_number'],
            },
        ),
        migrations.AddIndex(
            model_name='olclaimant',
            index=models.Index(fields=['claim', 'claimant_type'], name='ol_claimant_claim_type_idx'),
        ),
        migrations.AddIndex(
            model_name='olclaimant',
            index=models.Index(fields=['identity_number'], name='ol_claimant_identity_idx'),
        ),
        migrations.AddIndex(
            model_name='olclaim',
            index=models.Index(fields=['policy_ref', 'status'], name='ol_claim_policy_status_idx'),
        ),
        migrations.AddIndex(
            model_name='olclaim',
            index=models.Index(fields=['claim_type', 'claim_date'], name='ol_claim_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='olclaim',
            index=models.Index(fields=['status', 'fraud_flag'], name='ol_claim_status_fraud_idx'),
        ),
        migrations.AddIndex(
            model_name='olclaimdocument',
            index=models.Index(fields=['claim', 'mandatory_flag'], name='ol_claim_doc_mandatory_idx'),
        ),
        migrations.AddIndex(
            model_name='olclaimfilenote',
            index=models.Index(fields=['claim', 'created_at'], name='ol_claim_note_created_idx'),
        ),
        migrations.AddIndex(
            model_name='olclaimitem',
            index=models.Index(fields=['claim', 'benefit_type'], name='ol_claim_item_benefit_idx'),
        ),
        migrations.AddIndex(
            model_name='olclaimrequisition',
            index=models.Index(fields=['claim', 'status'], name='ol_claim_req_status_idx'),
        ),
    ]
