# Generated by Django 5.0.14 on 2026-08-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olclaim',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
