# Generated by Django 5.0.14 on 2026-08-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_claims', '0002_olclaim_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='olclaim',
            name='idempotency_fingerprint',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
