# Generated by Django 5.0.14 on 2026-08-27 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_claims', '0003_olclaim_idempotency_fingerprint'),
        ('ol_policies', '0010_withdrawal_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='olclaim',
            name='medical_loading_factor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='olclaim',
            name='medical_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='olclaim',
            name='medical_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olclaim',
            name='medical_result',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='olclaim',
            name='medical_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olclaim',
            name='medical_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_claims_medical_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='olclaim',
            name='medical_status',
            field=models.CharField(choices=[('NONE', 'No medical review'), ('PENDING', 'Pending medical review'), ('CLEARED', 'Medical review cleared'), ('REJECTED', 'Medical review rejected'), ('LOADING', 'Medical loading applied')], db_index=True, default='NONE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='olclaim',
            index=models.Index(fields=['medical_status', 'status'], name='ol_claim_medical_status_idx'),
        ),
    ]
