# Generated by Django 5.0.14 on 2026-08-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_claims', '0004_olclaim_medical_loading_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olclaim',
            name='fraud_flag_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='olclaim',
            name='waiver_of_premium_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='olclaim',
            name='waiver_of_premium_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='olclaim',
            name='waiver_of_premium_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
