# Generated by Django 5.0.14 on 2026-08-27 20:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_claims', '0005_olclaim_fraud_flag_reason_and_more'),
        ('ol_policies', '0010_withdrawal_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLClaimLoanOffset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('offset_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_payout', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('REVERSED', 'Reversed')], db_index=True, default='APPLIED', max_length=20)),
                ('applied_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, default='')),
                ('loan_breakdown', models.JSONField(blank=True, default=list)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan_offset', to='ol_claims.olclaim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_offsets', to='ol_policies.policyloan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ol_claims_loan_offset',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['loan', 'status'], name='ol_claim_offset_loan_idx'), models.Index(fields=['claim', 'applied_at'], name='ol_claim_offset_claim_idx')],
            },
        ),
    ]
