# Generated by Django 5.0.14 on 2026-08-27 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_office', '0010_receipt_receipt_payment_mode_date_idx'),
        ('governance', '0003_auditlog_quick_create_source_channel'),
        ('ol_claims', '0006_olclaimloanoffset'),
    ]

    operations = [
        migrations.AddField(
            model_name='olclaimrequisition',
            name='approval_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_claim_requisitions', to='governance.approvalrequest'),
        ),
        migrations.AddField(
            model_name='olclaimrequisition',
            name='approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='olclaimrequisition',
            name='narration',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='olclaimrequisition',
            name='payment_requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ol_claim_requisitions', to='front_office.forequisition'),
        ),
    ]
