# Generated by Django 5.0.14 on 2026-08-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_claims', '0007_olclaimrequisition_approval_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olclaim',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='olclaim',
            name='policy_update_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='olclaim',
            name='reinsurance_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='olclaim',
            name='settlement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
