# Generated by Django 5.0.14 on 2026-08-18 12:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLParameterTableRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('parameter_group', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('model_label', models.CharField(help_text='Django app_label.ModelName or a future resource identifier.', max_length=200)),
                ('visible_columns', models.JSONField(default=list)),
                ('searchable_fields', models.JSONField(default=list)),
                ('filter_fields', models.JSONField(default=list)),
                ('default_ordering', models.JSONField(default=list)),
                ('allowed_actions', models.JSONField(default=list)),
                ('export_support', models.BooleanField(default=False)),
                ('permission_code', models.CharField(default='ol_parameters.view', max_length=120)),
                ('permission_requirements', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ol_parameter_tables', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ol_parameter_tables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['parameter_group', 'label', 'slug'],
                'indexes': [models.Index(fields=['is_active', 'parameter_group'], name='ol_pr_registry_act_grp_idx'), models.Index(fields=['model_label'], name='ol_params_registry_model_idx')],
            },
        ),
    ]
