# Generated by Django 5.0.14 on 2026-08-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0002_seed_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olparametertableregistry',
            name='allowed_actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='olparametertableregistry',
            name='default_ordering',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='olparametertableregistry',
            name='filter_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='olparametertableregistry',
            name='permission_requirements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='olparametertableregistry',
            name='searchable_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='olparametertableregistry',
            name='visible_columns',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
