# Generated by Django 5.0.14 on 2026-08-18 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0003_alter_olparametertableregistry_allowed_actions_and_more'),
        ('ordinary_life', '0007_oldocumentrecord_idempotency_key_and_more'),
        ('partner_onboarding', '0014_applicationpartnertype_kyc_status'),
        ('partners', '0011_partner_created_by_partner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLDefaultSystemParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter_key', models.CharField(max_length=100, unique=True)),
                ('parameter_category', models.CharField(db_index=True, max_length=80)),
                ('value_type', models.CharField(choices=[('STRING', 'String'), ('TEXT', 'Text'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('JSON', 'JSON')], default='STRING', max_length=10)),
                ('string_value', models.TextField(blank=True, null=True)),
                ('integer_value', models.IntegerField(blank=True, null=True)),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('json_value', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['parameter_category', 'name', 'parameter_key'],
            },
        ),
        migrations.CreateModel(
            name='OLMaturityClaimSetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_create_maturity_claim', models.BooleanField(default=True)),
                ('days_before_maturity_to_initiate', models.PositiveIntegerField(default=0)),
                ('notification_days', models.PositiveIntegerField(default=0)),
                ('default_payout_method', models.CharField(default='BANK_TRANSFER', max_length=40)),
                ('require_documents', models.BooleanField(default=True)),
                ('require_approval', models.BooleanField(default=True)),
                ('maturity_claim_status_to_create', models.CharField(default='REPORTED', max_length=40)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_maturity_claim_setups', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_maturity_claim_setups', to='ordinary_life.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from', 'name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLOverrideCommissionSetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intermediary_type', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('channel', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('currency', models.CharField(blank=True, db_index=True, default='', max_length=3)),
                ('premium_year_from', models.PositiveIntegerField(blank=True, null=True)),
                ('premium_year_to', models.PositiveIntegerField(blank=True, null=True)),
                ('policy_year_from', models.PositiveIntegerField(blank=True, null=True)),
                ('policy_year_to', models.PositiveIntegerField(blank=True, null=True)),
                ('rate_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed'), ('FACTOR', 'Factor')], max_length=10)),
                ('rate_value', models.DecimalField(decimal_places=8, max_digits=18)),
                ('priority', models.PositiveIntegerField(db_index=True, default=100)),
                ('reason', models.TextField(blank=True, default='')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_commission_overrides', to='partner_onboarding.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, help_text='Optional partner or agent scope; agent partners are represented by this relation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_commission_overrides', to='partners.partner')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_commission_overrides', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_commission_overrides', to='ordinary_life.olproduct')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_commission_overrides', to='ordinary_life.olrider')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', '-effective_from', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLComputationApproach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculation_area', models.CharField(db_index=True, max_length=80)),
                ('calculation_basis', models.CharField(max_length=120)),
                ('formula_key', models.CharField(max_length=120)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['calculation_area', 'sequence', 'name', 'code'],
                'indexes': [models.Index(fields=['calculation_area', 'is_active'], name='ol_compute_area_active_idx'), models.Index(fields=['calculation_area', 'sequence'], name='ol_compute_area_seq_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='olcomputationapproach',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_compute_approach_code_unique'),
        ),
        migrations.AddIndex(
            model_name='oldefaultsystemparameter',
            index=models.Index(fields=['parameter_category', 'is_active'], name='ol_def_sys_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='oldefaultsystemparameter',
            index=models.Index(fields=['parameter_key', 'is_active'], name='ol_def_sys_key_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='oldefaultsystemparameter',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_def_sys_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='oldefaultsystemparameter',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ol_def_sys_dates_valid'),
        ),
        migrations.AddIndex(
            model_name='olmaturityclaimsetup',
            index=models.Index(fields=['product', 'plan', 'is_active'], name='ol_maturity_scope_active_idx'),
        ),
        migrations.AddIndex(
            model_name='olmaturityclaimsetup',
            index=models.Index(fields=['auto_create_maturity_claim', 'is_active'], name='ol_maturity_auto_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='olmaturityclaimsetup',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_maturity_setup_code_unique'),
        ),
        migrations.AddIndex(
            model_name='oloverridecommissionsetup',
            index=models.Index(fields=['partner', 'product', 'plan', 'rider', 'is_active'], name='ol_comm_scope_active_idx'),
        ),
        migrations.AddIndex(
            model_name='oloverridecommissionsetup',
            index=models.Index(fields=['priority', 'effective_from', 'effective_to'], name='ol_comm_priority_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='oloverridecommissionsetup',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_comm_override_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='oloverridecommissionsetup',
            constraint=models.CheckConstraint(check=models.Q(('premium_year_to__isnull', True), ('premium_year_from__isnull', True), ('premium_year_to__gte', models.F('premium_year_from')), _connector='OR'), name='ol_comm_prem_years_valid'),
        ),
        migrations.AddConstraint(
            model_name='oloverridecommissionsetup',
            constraint=models.CheckConstraint(check=models.Q(('policy_year_to__isnull', True), ('policy_year_from__isnull', True), ('policy_year_to__gte', models.F('policy_year_from')), _connector='OR'), name='ol_comm_policy_years_valid'),
        ),
        migrations.AddConstraint(
            model_name='oloverridecommissionsetup',
            constraint=models.CheckConstraint(check=models.Q(('rate_value__gte', 0)), name='ol_comm_rate_nonnegative'),
        ),
    ]
