# Generated by Django 5.0.14 on 2026-08-18 12:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0004_oldefaultsystemparameter_olmaturityclaimsetup_and_more'),
        ('ordinary_life', '0007_oldocumentrecord_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLBeneficialType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('BENEFICIARY', 'Beneficiary'), ('BENEFIT', 'Benefit'), ('COVERAGE', 'Coverage'), ('OTHER', 'Other')], default='BENEFICIARY', max_length=20)),
                ('calculation_basis', models.CharField(default='PERCENTAGE', max_length=50)),
                ('default_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('allows_multiple', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLGracePeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('premium_frequency', models.CharField(blank=True, default='', max_length=30)),
                ('grace_days', models.PositiveIntegerField(default=0)),
                ('warning_days', models.PositiveIntegerField(default=0)),
                ('pre_lapse_days', models.PositiveIntegerField(default=0)),
                ('lapse_days', models.PositiveIntegerField(default=0)),
                ('minimum_due_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_grace_periods', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_grace_periods', to='ordinary_life.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product', 'plan', 'premium_frequency', '-effective_from', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLMemberCoverConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_type', models.CharField(default='INDIVIDUAL', max_length=40)),
                ('member_relation', models.CharField(default='MEMBER', max_length=40)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('waiting_period_days', models.PositiveIntegerField(default=0)),
                ('benefit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('premium_basis', models.CharField(default='MEMBER_PREMIUM', max_length=50)),
                ('coverage_basis', models.CharField(default='SUM_ASSURED', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_member_cover_configurations', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_member_cover_configurations', to='ordinary_life.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product', 'plan', 'cover_type', 'member_relation', 'min_age', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLPolicyRenewalStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('renewal_action', models.CharField(default='NONE', max_length=40)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLPolicyStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('badge_type', models.CharField(default='NEUTRAL', max_length=30)),
                ('is_terminal', models.BooleanField(default=False)),
                ('allowed_transitions', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLAnticipatedEndowmentInstallmentRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_type', models.CharField(default='ANTICIPATED_ENDOWMENT', max_length=40)),
                ('frequency', models.CharField(default='ANNUAL', max_length=30)),
                ('age_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('term_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('term_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('policy_year_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('policy_year_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rate_factor', models.DecimalField(decimal_places=8, max_digits=18)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_anticipated_endowment_rates', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ol_anticipated_endowment_rates', to='ordinary_life.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product', 'plan', 'frequency', 'age_from', 'term_from', 'policy_year_from', 'code'],
                'indexes': [models.Index(fields=['product', 'plan', 'frequency'], name='ol_policy_endow_scope_idx'), models.Index(fields=['effective_from', 'effective_to'], name='ol_policy_endow_dates_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='olanticipatedendowmentinstallmentrate',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_policy_endow_rate_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olanticipatedendowmentinstallmentrate',
            constraint=models.CheckConstraint(check=models.Q(('rate_factor__gte', 0)), name='ol_policy_endow_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olanticipatedendowmentinstallmentrate',
            constraint=models.CheckConstraint(check=models.Q(('age_to__isnull', True), ('age_from__isnull', True), ('age_to__gte', models.F('age_from')), _connector='OR'), name='ol_policy_endow_age_valid'),
        ),
        migrations.AddConstraint(
            model_name='olanticipatedendowmentinstallmentrate',
            constraint=models.CheckConstraint(check=models.Q(('term_to__isnull', True), ('term_from__isnull', True), ('term_to__gte', models.F('term_from')), _connector='OR'), name='ol_policy_endow_term_valid'),
        ),
        migrations.AddConstraint(
            model_name='olanticipatedendowmentinstallmentrate',
            constraint=models.CheckConstraint(check=models.Q(('policy_year_to__isnull', True), ('policy_year_from__isnull', True), ('policy_year_to__gte', models.F('policy_year_from')), _connector='OR'), name='ol_policy_endow_year_valid'),
        ),
        migrations.AddIndex(
            model_name='olbeneficialtype',
            index=models.Index(fields=['category', 'is_active'], name='ol_beneficial_type_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='olbeneficialtype',
            index=models.Index(fields=['is_active', 'calculation_basis'], name='ol_beneficial_type_basis_idx'),
        ),
        migrations.AddConstraint(
            model_name='olbeneficialtype',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_beneficial_type_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olbeneficialtype',
            constraint=models.CheckConstraint(check=models.Q(('default_ratio__gte', 0), ('default_ratio__lte', 100)), name='ol_beneficial_ratio_valid'),
        ),
        migrations.AddIndex(
            model_name='olgraceperiod',
            index=models.Index(fields=['product', 'plan', 'premium_frequency'], name='ol_policy_grace_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olgraceperiod',
            index=models.Index(fields=['is_active', 'effective_from'], name='ol_policy_grace_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='olgraceperiod',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_policy_grace_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olgraceperiod',
            constraint=models.CheckConstraint(check=models.Q(('minimum_due_amount__isnull', True), ('minimum_due_amount__gte', 0), _connector='OR'), name='ol_policy_grace_min_due_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='olgraceperiod',
            constraint=models.CheckConstraint(check=models.Q(('grace_days__lte', models.F('lapse_days'))), name='ol_policy_grace_days_ordered'),
        ),
        migrations.AddConstraint(
            model_name='olgraceperiod',
            constraint=models.CheckConstraint(check=models.Q(('warning_days__lte', models.F('lapse_days'))), name='ol_policy_grace_warning_valid'),
        ),
        migrations.AddConstraint(
            model_name='olgraceperiod',
            constraint=models.CheckConstraint(check=models.Q(('pre_lapse_days__lte', models.F('lapse_days'))), name='ol_policy_grace_pre_lapse_valid'),
        ),
        migrations.AddIndex(
            model_name='olmembercoverconfiguration',
            index=models.Index(fields=['product', 'plan', 'cover_type', 'member_relation'], name='ol_member_cover_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olmembercoverconfiguration',
            index=models.Index(fields=['is_active', 'effective_from'], name='ol_member_cover_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='olmembercoverconfiguration',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_member_cover_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olmembercoverconfiguration',
            constraint=models.CheckConstraint(check=models.Q(('max_age__isnull', True), ('min_age__isnull', True), ('max_age__gte', models.F('min_age')), _connector='OR'), name='ol_member_cover_age_valid'),
        ),
        migrations.AddConstraint(
            model_name='olmembercoverconfiguration',
            constraint=models.CheckConstraint(check=models.Q(('benefit_limit__isnull', True), ('benefit_limit__gte', 0), _connector='OR'), name='ol_member_cover_limit_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='olpolicyrenewalstatus',
            index=models.Index(fields=['is_active', 'display_order'], name='ol_policy_renewal_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='olpolicyrenewalstatus',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_policy_renewal_status_code_uq'),
        ),
        migrations.AddIndex(
            model_name='olpolicystatus',
            index=models.Index(fields=['is_active', 'display_order'], name='ol_policy_status_active_idx'),
        ),
        migrations.AddIndex(
            model_name='olpolicystatus',
            index=models.Index(fields=['is_terminal', 'is_active'], name='ol_policy_status_terminal_idx'),
        ),
        migrations.AddConstraint(
            model_name='olpolicystatus',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_policy_status_code_uq'),
        ),
    ]
