# Generated by Django 5.0.14 on 2026-08-18 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0005_olbeneficialtype_olgraceperiod_and_more'),
        ('ordinary_life', '0007_oldocumentrecord_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLPaidUpRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_code', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('rate_table_version', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('gender', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('smoker_status', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('age_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('term_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('term_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('policy_year_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('policy_year_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rate_factor', models.DecimalField(decimal_places=8, max_digits=18)),
                ('row_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_paid_up_rates', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_paid_up_rates', to='ordinary_life.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['table_code', 'rate_table_version', 'product', 'plan', 'row_order', 'age_from', 'term_from', 'policy_year_from', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLPaidUpSetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minimum_premiums_paid', models.PositiveIntegerField(default=0)),
                ('minimum_policy_months', models.PositiveIntegerField(default=0)),
                ('paidup_conversion_basis', models.CharField(choices=[('PROPORTIONAL', 'Proportional'), ('REDUCED_SUM_ASSURED', 'Reduced sum assured'), ('CASH_VALUE', 'Cash value'), ('CUSTOM', 'Custom formula')], default='PROPORTIONAL', max_length=30)),
                ('allow_paidup', models.BooleanField(default=True)),
                ('paidup_effective_rule', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('NEXT_ANNIVERSARY', 'Next policy anniversary'), ('NEXT_DUE_DATE', 'Next premium due date'), ('CONFIGURED_DATE', 'Configured effective date')], default='NEXT_ANNIVERSARY', max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_paid_up_setups', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_paid_up_setups', to='ordinary_life.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product', 'plan', '-effective_from', 'name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLSurrenderSetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minimum_premiums_paid', models.PositiveIntegerField(default=0)),
                ('minimum_policy_months', models.PositiveIntegerField(default=0)),
                ('minimum_premium_paid_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('surrender_charge_type', models.CharField(choices=[('NONE', 'None'), ('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed amount'), ('FACTOR', 'Factor')], default='NONE', max_length=20)),
                ('surrender_charge_value', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('partial_surrender_allowed', models.BooleanField(default=False)),
                ('surrender_payout_days', models.PositiveIntegerField(default=0)),
                ('require_approval', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_surrender_setups', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_surrender_setups', to='ordinary_life.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product', 'plan', '-effective_from', 'name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLSurrenderValueRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_code', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('rate_table_version', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('gender', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('smoker_status', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('age_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('term_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('term_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('policy_year_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('policy_year_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rate_factor', models.DecimalField(decimal_places=8, max_digits=18)),
                ('row_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_surrender_value_rates', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_surrender_value_rates', to='ordinary_life.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['table_code', 'rate_table_version', 'product', 'plan', 'row_order', 'age_from', 'term_from', 'policy_year_from', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLCommitmentStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('applies_to', models.CharField(db_index=True, default='COMMITMENT', max_length=50)),
                ('is_terminal', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['applies_to', 'display_order', 'name', 'code'],
                'indexes': [models.Index(fields=['applies_to', 'is_active', 'display_order'], name='ol_commitment_status_idx'), models.Index(fields=['is_terminal', 'is_active'], name='ol_commitment_terminal_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='olcommitmentstatus',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_commitment_status_code_uq'),
        ),
        migrations.AddIndex(
            model_name='olpaiduprate',
            index=models.Index(fields=['table_code', 'rate_table_version', 'product', 'plan'], name='ol_paidup_rate_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olpaiduprate',
            index=models.Index(fields=['product', 'gender', 'smoker_status'], name='ol_paidup_rate_dim_idx'),
        ),
        migrations.AddIndex(
            model_name='olpaiduprate',
            index=models.Index(fields=['is_active', 'effective_from'], name='ol_paidup_rate_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='olpaiduprate',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_paidup_rate_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olpaiduprate',
            constraint=models.CheckConstraint(check=models.Q(('rate_factor__gte', 0)), name='ol_paidup_rate_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='olpaiduprate',
            constraint=models.CheckConstraint(check=models.Q(('age_to__isnull', True), ('age_from__isnull', True), ('age_to__gte', models.F('age_from')), _connector='OR'), name='ol_paidup_rate_age_valid'),
        ),
        migrations.AddConstraint(
            model_name='olpaiduprate',
            constraint=models.CheckConstraint(check=models.Q(('term_to__isnull', True), ('term_from__isnull', True), ('term_to__gte', models.F('term_from')), _connector='OR'), name='ol_paidup_rate_term_valid'),
        ),
        migrations.AddConstraint(
            model_name='olpaiduprate',
            constraint=models.CheckConstraint(check=models.Q(('policy_year_to__isnull', True), ('policy_year_from__isnull', True), ('policy_year_to__gte', models.F('policy_year_from')), _connector='OR'), name='ol_paidup_rate_year_valid'),
        ),
        migrations.AddIndex(
            model_name='olpaidupsetup',
            index=models.Index(fields=['product', 'plan', 'is_active'], name='ol_paidup_setup_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olpaidupsetup',
            index=models.Index(fields=['allow_paidup', 'is_active'], name='ol_paidup_setup_allow_idx'),
        ),
        migrations.AddConstraint(
            model_name='olpaidupsetup',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_paidup_setup_code_uq'),
        ),
        migrations.AddIndex(
            model_name='olsurrendersetup',
            index=models.Index(fields=['product', 'plan', 'is_active'], name='ol_surr_setup_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olsurrendersetup',
            index=models.Index(fields=['is_active', 'effective_from'], name='ol_surr_setup_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='olsurrendersetup',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_surr_setup_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olsurrendersetup',
            constraint=models.CheckConstraint(check=models.Q(('minimum_premium_paid_ratio__gte', 0), ('minimum_premium_paid_ratio__lte', 100)), name='ol_surr_setup_ratio_valid'),
        ),
        migrations.AddConstraint(
            model_name='olsurrendersetup',
            constraint=models.CheckConstraint(check=models.Q(('surrender_charge_value__gte', 0)), name='ol_surr_setup_charge_nonneg'),
        ),
        migrations.AddIndex(
            model_name='olsurrendervaluerate',
            index=models.Index(fields=['table_code', 'rate_table_version', 'product', 'plan'], name='ol_surr_value_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olsurrendervaluerate',
            index=models.Index(fields=['product', 'gender', 'smoker_status'], name='ol_surr_value_dim_idx'),
        ),
        migrations.AddIndex(
            model_name='olsurrendervaluerate',
            index=models.Index(fields=['is_active', 'effective_from'], name='ol_surr_value_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='olsurrendervaluerate',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_surr_value_rate_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olsurrendervaluerate',
            constraint=models.CheckConstraint(check=models.Q(('rate_factor__gte', 0)), name='ol_surr_value_rate_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='olsurrendervaluerate',
            constraint=models.CheckConstraint(check=models.Q(('age_to__isnull', True), ('age_from__isnull', True), ('age_to__gte', models.F('age_from')), _connector='OR'), name='ol_surr_value_age_valid'),
        ),
        migrations.AddConstraint(
            model_name='olsurrendervaluerate',
            constraint=models.CheckConstraint(check=models.Q(('term_to__isnull', True), ('term_from__isnull', True), ('term_to__gte', models.F('term_from')), _connector='OR'), name='ol_surr_value_term_valid'),
        ),
        migrations.AddConstraint(
            model_name='olsurrendervaluerate',
            constraint=models.CheckConstraint(check=models.Q(('policy_year_to__isnull', True), ('policy_year_from__isnull', True), ('policy_year_to__gte', models.F('policy_year_from')), _connector='OR'), name='ol_surr_value_year_valid'),
        ),
    ]
