# Generated by Django 5.0.14 on 2026-08-18 14:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0006_olpaiduprate_olpaidupsetup_olsurrendersetup_and_more'),
        ('ordinary_life', '0007_oldocumentrecord_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLHealthQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField()),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('answer_type', models.CharField(choices=[('BOOLEAN', 'Boolean'), ('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('CHOICE', 'Choice')], default='BOOLEAN', max_length=20)),
                ('underwriting_impact', models.CharField(choices=[('NONE', 'None'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NONE', max_length=20)),
                ('requires_medical_followup', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLHealthQuestionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to_scope', models.CharField(choices=[('PRODUCT', 'Product'), ('PLAN', 'Plan'), ('SCHEME', 'Scheme'), ('GLOBAL', 'Global')], default='GLOBAL', max_length=20)),
                ('scheme_code', models.CharField(blank=True, default='', max_length=100)),
                ('sum_assured_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('age_threshold', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_health_questionnaires', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_health_questionnaires', to='ordinary_life.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code', '-effective_from', 'version'],
            },
        ),
        migrations.CreateModel(
            name='OLHealthQuestionnaireItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('mandatory', models.BooleanField(default=False)),
                ('trigger_medical_requirement', models.BooleanField(default=False)),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('health_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questionnaire_items', to='ol_parameters.olhealthquestion')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ol_parameters.olhealthquestionnaire')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['questionnaire', 'sequence', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLReinstatementWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_after_lapse', models.PositiveIntegerField()),
                ('maximum_reinstatements', models.PositiveIntegerField(blank=True, null=True)),
                ('require_medical_underwriting', models.BooleanField(default=False)),
                ('require_outstanding_premium_payment', models.BooleanField(default=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('penalty_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_reinstatement_windows', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_reinstatement_windows', to='ordinary_life.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product', 'plan', '-effective_from', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLGracePeriodNotificationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('PREMIUM_DUE', 'Premium due'), ('GRACE_START', 'Grace start'), ('GRACE_WARNING', 'Grace warning'), ('PRE_LAPSE', 'Pre-lapse'), ('LAPSE', 'Lapse')], max_length=30)),
                ('days_offset', models.SmallIntegerField()),
                ('notification_channel', models.CharField(choices=[('SYSTEM', 'System'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PORTAL', 'Portal'), ('OTHER', 'Other')], default='SYSTEM', max_length=20)),
                ('recipient_type', models.CharField(choices=[('POLICYHOLDER', 'Policyholder'), ('AGENT', 'Agent'), ('STAFF', 'Staff'), ('PARTNER', 'Partner')], default='POLICYHOLDER', max_length=20)),
                ('template_code', models.CharField(blank=True, default='', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_type', 'days_offset', 'code'],
                'indexes': [models.Index(fields=['event_type', 'is_active', 'effective_from'], name='ol_grace_notify_event_idx'), models.Index(fields=['notification_channel', 'recipient_type'], name='ol_grace_notify_route_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='olgraceperiodnotificationschedule',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_grace_notify_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olgraceperiodnotificationschedule',
            constraint=models.CheckConstraint(check=models.Q(('days_offset__gte', -3650), ('days_offset__lte', 3650)), name='ol_grace_notify_offset_rng'),
        ),
        migrations.AddIndex(
            model_name='olhealthquestion',
            index=models.Index(fields=['category', 'is_active'], name='ol_health_question_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='olhealthquestion',
            index=models.Index(fields=['answer_type', 'is_active'], name='ol_health_question_type_idx'),
        ),
        migrations.AddIndex(
            model_name='olhealthquestion',
            index=models.Index(fields=['requires_medical_followup', 'is_active'], name='ol_health_question_med_idx'),
        ),
        migrations.AddConstraint(
            model_name='olhealthquestion',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_health_question_code_uq'),
        ),
        migrations.AddIndex(
            model_name='olhealthquestionnaire',
            index=models.Index(fields=['applies_to_scope', 'is_active', 'effective_from'], name='ol_health_qnr_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olhealthquestionnaire',
            index=models.Index(fields=['product', 'plan', 'is_active'], name='ol_health_qnr_product_idx'),
        ),
        migrations.AddIndex(
            model_name='olhealthquestionnaire',
            index=models.Index(fields=['code', 'version'], name='ol_health_qnr_code_ver_idx'),
        ),
        migrations.AddConstraint(
            model_name='olhealthquestionnaire',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='ol_health_questionnaire_code_ver_uq'),
        ),
        migrations.AddConstraint(
            model_name='olhealthquestionnaire',
            constraint=models.CheckConstraint(check=models.Q(('sum_assured_threshold__isnull', True), ('sum_assured_threshold__gte', 0), _connector='OR'), name='ol_health_qnr_sum_nonneg'),
        ),
        migrations.AddIndex(
            model_name='olhealthquestionnaireitem',
            index=models.Index(fields=['questionnaire', 'is_active', 'sequence'], name='ol_health_qitem_order_idx'),
        ),
        migrations.AddIndex(
            model_name='olhealthquestionnaireitem',
            index=models.Index(fields=['mandatory', 'is_active'], name='ol_health_qitem_mand_idx'),
        ),
        migrations.AddConstraint(
            model_name='olhealthquestionnaireitem',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_health_qitem_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olhealthquestionnaireitem',
            constraint=models.UniqueConstraint(fields=('questionnaire', 'health_question'), name='ol_health_qitem_question_uq'),
        ),
        migrations.AddConstraint(
            model_name='olhealthquestionnaireitem',
            constraint=models.UniqueConstraint(fields=('questionnaire', 'sequence'), name='ol_health_qitem_sequence_uq'),
        ),
        migrations.AddConstraint(
            model_name='olhealthquestionnaireitem',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gt', 0)), name='ol_health_qitem_sequence_pos'),
        ),
        migrations.AddConstraint(
            model_name='olhealthquestionnaireitem',
            constraint=models.CheckConstraint(check=models.Q(('score__isnull', True), ('score__gte', 0), _connector='OR'), name='ol_health_qitem_score_nonneg'),
        ),
        migrations.AddIndex(
            model_name='olreinstatementwindow',
            index=models.Index(fields=['product', 'plan', 'is_active', 'effective_from'], name='ol_reinstate_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olreinstatementwindow',
            index=models.Index(fields=['require_medical_underwriting', 'is_active'], name='ol_reinstate_med_idx'),
        ),
        migrations.AddConstraint(
            model_name='olreinstatementwindow',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_reinstate_window_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olreinstatementwindow',
            constraint=models.CheckConstraint(check=models.Q(('days_after_lapse__gt', 0)), name='ol_reinstate_days_pos'),
        ),
        migrations.AddConstraint(
            model_name='olreinstatementwindow',
            constraint=models.CheckConstraint(check=models.Q(('maximum_reinstatements__isnull', True), ('maximum_reinstatements__gt', 0), _connector='OR'), name='ol_reinstate_max_pos'),
        ),
        migrations.AddConstraint(
            model_name='olreinstatementwindow',
            constraint=models.CheckConstraint(check=models.Q(('interest_rate__isnull', True), models.Q(('interest_rate__gte', 0), ('interest_rate__lte', 100)), _connector='OR'), name='ol_reinstate_interest_rng'),
        ),
        migrations.AddConstraint(
            model_name='olreinstatementwindow',
            constraint=models.CheckConstraint(check=models.Q(('penalty_rate__isnull', True), models.Q(('penalty_rate__gte', 0), ('penalty_rate__lte', 100)), _connector='OR'), name='ol_reinstate_penalty_rng'),
        ),
    ]
