# Generated by Django 5.0.14 on 2026-08-18 15:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0007_olhealthquestion_olhealthquestionnaire_and_more'),
        ('ordinary_life', '0007_oldocumentrecord_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLInvestmentFundType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_profile', models.CharField(choices=[('CONSERVATIVE', 'Conservative'), ('MODERATE', 'Moderate'), ('BALANCED', 'Balanced'), ('AGGRESSIVE', 'Aggressive')], default='MODERATE', max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLInvestmentFund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('valuation_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], default='DAILY', max_length=20)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('allocation_rules', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fund_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funds', to='ol_parameters.olinvestmentfundtype')),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLPlanType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_category', models.CharField(default='INDIVIDUAL', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_class', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group'), ('CREDIT', 'Credit'), ('INVESTMENT_LINKED', 'Investment linked')], default='INDIVIDUAL', max_length=30)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('min_entry_age', models.PositiveSmallIntegerField(default=18)),
                ('max_entry_age', models.PositiveSmallIntegerField(default=65)),
                ('min_term', models.PositiveSmallIntegerField(default=1)),
                ('max_term', models.PositiveSmallIntegerField(default=30)),
                ('min_sum_assured', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('max_sum_assured', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('premium_frequencies', models.JSONField(default=list)),
                ('allow_riders', models.BooleanField(default=False)),
                ('allow_loans', models.BooleanField(default=False)),
                ('allow_withdrawals', models.BooleanField(default=False)),
                ('allow_surrender', models.BooleanField(default=True)),
                ('allow_paidup', models.BooleanField(default=False)),
                ('allow_bonus', models.BooleanField(default=False)),
                ('investment_linked', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='ol_parameters.olplantype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLPlanTaxConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_type', models.CharField(max_length=50)),
                ('tax_basis', models.CharField(max_length=50)),
                ('rate_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed'), ('FACTOR', 'Factor')], default='PERCENTAGE', max_length=20)),
                ('rate_value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('apply_on', models.CharField(max_length=50)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('country_or_branch', models.CharField(blank=True, default='', max_length=80)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_tax_configurations', to='ordinary_life.olplan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_configurations', to='ol_parameters.olproduct')),
            ],
            options={
                'ordering': ['product', 'plan', 'sequence', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLPlanTargetMarket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_market_type', models.CharField(max_length=60)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('occupation_categories', models.JSONField(blank=True, default=list)),
                ('residency_requirement', models.CharField(blank=True, default='', max_length=80)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_target_markets', to='ordinary_life.olplan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_markets', to='ol_parameters.olproduct')),
            ],
            options={
                'ordering': ['product', 'plan', 'target_market_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLPlanRiskCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('underwriting_class', models.CharField(max_length=60)),
                ('loading_basis', models.CharField(max_length=60)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_risk_categories', to='ordinary_life.olplan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_categories', to='ol_parameters.olproduct')),
            ],
            options={
                'ordering': ['product', 'plan', 'underwriting_class', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLPlanOccupationRiskLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occupation_risk_category', models.CharField(max_length=80)),
                ('max_sum_assured', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('loading_rate', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('exclusion_flag', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_occupation_risk_limits', to='ordinary_life.olplan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occupation_risk_limits', to='ol_parameters.olproduct')),
            ],
            options={
                'ordering': ['product', 'plan', 'occupation_risk_category', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='olinvestmentfundtype',
            index=models.Index(fields=['risk_profile', 'is_active'], name='ol_product_fund_type_risk_idx'),
        ),
        migrations.AddConstraint(
            model_name='olinvestmentfundtype',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_product_fund_type_code_uq'),
        ),
        migrations.AddIndex(
            model_name='olinvestmentfund',
            index=models.Index(fields=['fund_type', 'is_active'], name='ol_product_fund_type_idx'),
        ),
        migrations.AddIndex(
            model_name='olinvestmentfund',
            index=models.Index(fields=['currency', 'valuation_frequency', 'is_active'], name='ol_product_fund_route_idx'),
        ),
        migrations.AddIndex(
            model_name='olinvestmentfund',
            index=models.Index(fields=['is_active', 'effective_from', 'effective_to'], name='ol_prod_fund_active_dates'),
        ),
        migrations.AddConstraint(
            model_name='olinvestmentfund',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_product_fund_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olinvestmentfund',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__isnull', True), ('unit_price__gt', 0), _connector='OR'), name='ol_product_fund_unit_price_pos_ck'),
        ),
        migrations.AddIndex(
            model_name='olplantype',
            index=models.Index(fields=['plan_category', 'is_active'], name='ol_product_plan_type_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='olplantype',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_product_plan_type_code_uq'),
        ),
        migrations.AddIndex(
            model_name='olproduct',
            index=models.Index(fields=['plan_type', 'is_active'], name='ol_product_setup_plan_idx'),
        ),
        migrations.AddIndex(
            model_name='olproduct',
            index=models.Index(fields=['insurance_class', 'is_active'], name='ol_product_setup_class_idx'),
        ),
        migrations.AddIndex(
            model_name='olproduct',
            index=models.Index(fields=['currency', 'is_active'], name='ol_product_setup_currency_idx'),
        ),
        migrations.AddIndex(
            model_name='olproduct',
            index=models.Index(fields=['is_active', 'effective_from', 'effective_to'], name='ol_prod_setup_active_dates'),
        ),
        migrations.AddConstraint(
            model_name='olproduct',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_product_setup_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olproduct',
            constraint=models.CheckConstraint(check=models.Q(('min_entry_age__lte', models.F('max_entry_age'))), name='ol_product_setup_age_range_ck'),
        ),
        migrations.AddConstraint(
            model_name='olproduct',
            constraint=models.CheckConstraint(check=models.Q(('min_term__gt', 0), ('min_term__lte', models.F('max_term'))), name='ol_product_setup_term_range_ck'),
        ),
        migrations.AddConstraint(
            model_name='olproduct',
            constraint=models.CheckConstraint(check=models.Q(('min_sum_assured__isnull', True), ('max_sum_assured__isnull', True), ('min_sum_assured__lte', models.F('max_sum_assured')), _connector='OR'), name='ol_product_setup_sum_range_ck'),
        ),
        migrations.AddIndex(
            model_name='olplantaxconfiguration',
            index=models.Index(fields=['product', 'plan', 'is_active', 'effective_from'], name='ol_product_tax_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olplantaxconfiguration',
            index=models.Index(fields=['tax_type', 'tax_basis', 'is_active'], name='ol_product_tax_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='olplantaxconfiguration',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_product_tax_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olplantaxconfiguration',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gt', 0)), name='ol_product_tax_sequence_pos_ck'),
        ),
        migrations.AddConstraint(
            model_name='olplantaxconfiguration',
            constraint=models.CheckConstraint(check=models.Q(('rate_value__gte', 0)), name='ol_product_tax_rate_nonneg_ck'),
        ),
        migrations.AddIndex(
            model_name='olplantargetmarket',
            index=models.Index(fields=['product', 'plan', 'is_active'], name='ol_product_market_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olplantargetmarket',
            index=models.Index(fields=['target_market_type', 'is_active'], name='ol_product_market_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='olplantargetmarket',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_product_market_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olplantargetmarket',
            constraint=models.CheckConstraint(check=models.Q(('max_age__isnull', True), ('min_age__isnull', True), ('max_age__gte', models.F('min_age')), _connector='OR'), name='ol_product_market_age_range_ck'),
        ),
        migrations.AddIndex(
            model_name='olplanriskcategory',
            index=models.Index(fields=['product', 'plan', 'is_active'], name='ol_product_risk_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olplanriskcategory',
            index=models.Index(fields=['underwriting_class', 'is_active'], name='ol_product_risk_class_idx'),
        ),
        migrations.AddConstraint(
            model_name='olplanriskcategory',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_product_risk_code_uq'),
        ),
        migrations.AddIndex(
            model_name='olplanoccupationrisklimit',
            index=models.Index(fields=['product', 'plan', 'is_active', 'effective_from'], name='ol_prod_occup_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olplanoccupationrisklimit',
            index=models.Index(fields=['occupation_risk_category', 'is_active'], name='ol_product_occupation_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='olplanoccupationrisklimit',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_product_occupation_limit_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olplanoccupationrisklimit',
            constraint=models.CheckConstraint(check=models.Q(('max_sum_assured__isnull', True), ('max_sum_assured__gte', 0), _connector='OR'), name='ol_product_occupation_sum_nonneg_ck'),
        ),
        migrations.AddConstraint(
            model_name='olplanoccupationrisklimit',
            constraint=models.CheckConstraint(check=models.Q(('loading_rate__gte', 0), ('loading_rate__lte', 100)), name='ol_product_occupation_loading_rng_ck'),
        ),
    ]
