# Generated by Django 5.0.14 on 2026-08-18 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0008_olinvestmentfundtype_olinvestmentfund_olplantype_and_more'),
        ('ordinary_life', '0007_oldocumentrecord_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLMortalityRateTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['table_code', '-effective_from', 'version'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OLMortalityRateRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(db_index=True, max_length=30)),
                ('smoker_status', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('policy_year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('mortality_rate', models.DecimalField(decimal_places=12, max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ol_parameters.olmortalityratetable')),
            ],
            options={
                'ordering': ['table', 'age', 'gender', 'smoker_status', 'policy_year', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLPremiumRateTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating_basis', models.CharField(choices=[('SUM_ASSURED', 'Sum assured'), ('AGE_TERM', 'Age and term'), ('PREMIUM', 'Premium'), ('FLAT', 'Flat'), ('CUSTOM', 'Custom')], default='AGE_TERM', max_length=40)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_premium_rate_tables', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premium_rate_tables', to='ol_parameters.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['table_code', '-effective_from', 'version'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OLPremiumRateRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(db_index=True, max_length=30)),
                ('smoker_status', models.CharField(db_index=True, max_length=30)),
                ('age_from', models.PositiveSmallIntegerField()),
                ('age_to', models.PositiveSmallIntegerField()),
                ('term_from', models.PositiveSmallIntegerField()),
                ('term_to', models.PositiveSmallIntegerField()),
                ('frequency', models.CharField(db_index=True, max_length=30)),
                ('sum_assured_band_from', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sum_assured_band_to', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('rate_unit', models.CharField(choices=[('PER_THOUSAND_SUM_ASSURED', 'Per thousand sum assured'), ('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed amount'), ('FACTOR', 'Factor')], default='PER_THOUSAND_SUM_ASSURED', max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ol_parameters.olpremiumratetable')),
            ],
            options={
                'ordering': ['table', 'gender', 'smoker_status', 'frequency', 'age_from', 'term_from', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLJointLifeSetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joint_life_type', models.CharField(choices=[('FIRST_DEATH', 'First death'), ('LAST_SURVIVOR', 'Last survivor'), ('JOINT_AND_SURVIVOR', 'Joint and survivor')], max_length=30)),
                ('age_basis', models.CharField(choices=[('YOUNGER_LIFE', 'Younger life'), ('OLDER_LIFE', 'Older life'), ('AVERAGE_AGE', 'Average age'), ('JOINT_AGE', 'Joint age')], max_length=30)),
                ('survivor_benefit_rule', models.CharField(max_length=120)),
                ('premium_adjustment_factor', models.DecimalField(decimal_places=6, default=1, max_digits=12)),
                ('underwriting_rule', models.CharField(max_length=120)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_joint_life_setups', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='joint_life_setups', to='ol_parameters.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product', 'plan', 'joint_life_type', '-effective_from', 'code'],
                'indexes': [models.Index(fields=['product', 'plan', 'is_active', 'effective_from'], name='ol_joint_life_scope_idx'), models.Index(fields=['joint_life_type', 'age_basis', 'is_active'], name='ol_joint_life_type_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='oljointlifesetup',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_joint_life_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='oljointlifesetup',
            constraint=models.CheckConstraint(check=models.Q(('premium_adjustment_factor__gt', 0)), name='ol_joint_life_factor_pos'),
        ),
        migrations.AddIndex(
            model_name='olmortalityratetable',
            index=models.Index(fields=['table_code', 'version'], name='ol_mort_table_ver_idx'),
        ),
        migrations.AddIndex(
            model_name='olmortalityratetable',
            index=models.Index(fields=['is_active', 'effective_from'], name='ol_mort_table_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='olmortalityratetable',
            constraint=models.UniqueConstraint(fields=('table_code', 'version'), name='ol_mort_table_code_ver_uq'),
        ),
        migrations.AddIndex(
            model_name='olmortalityraterow',
            index=models.Index(fields=['table', 'age', 'gender', 'smoker_status', 'policy_year'], name='ol_mort_row_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olmortalityraterow',
            index=models.Index(fields=['age', 'gender', 'smoker_status'], name='ol_mort_row_dim_idx'),
        ),
        migrations.AddConstraint(
            model_name='olmortalityraterow',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_mort_rate_row_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olmortalityraterow',
            constraint=models.CheckConstraint(check=models.Q(('age__lte', 150)), name='ol_mort_row_age_max_ck'),
        ),
        migrations.AddConstraint(
            model_name='olmortalityraterow',
            constraint=models.CheckConstraint(check=models.Q(('policy_year__isnull', True), ('policy_year__gt', 0), _connector='OR'), name='ol_mort_row_year_pos_ck'),
        ),
        migrations.AddConstraint(
            model_name='olmortalityraterow',
            constraint=models.CheckConstraint(check=models.Q(('mortality_rate__gte', 0)), name='ol_mort_row_rate_nonneg'),
        ),
        migrations.AddIndex(
            model_name='olpremiumratetable',
            index=models.Index(fields=['product', 'plan', 'is_active', 'effective_from'], name='ol_prem_table_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olpremiumratetable',
            index=models.Index(fields=['table_code', 'version'], name='ol_prem_table_ver_idx'),
        ),
        migrations.AddConstraint(
            model_name='olpremiumratetable',
            constraint=models.UniqueConstraint(fields=('table_code', 'version'), name='ol_prem_table_code_ver_uq'),
        ),
        migrations.AddIndex(
            model_name='olpremiumraterow',
            index=models.Index(fields=['table', 'gender', 'smoker_status', 'frequency'], name='ol_prem_row_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olpremiumraterow',
            index=models.Index(fields=['age_from', 'age_to', 'term_from', 'term_to'], name='ol_prem_row_band_idx'),
        ),
        migrations.AddIndex(
            model_name='olpremiumraterow',
            index=models.Index(fields=['is_active', 'effective_from'], name='ol_prem_row_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='olpremiumraterow',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_prem_rate_row_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olpremiumraterow',
            constraint=models.CheckConstraint(check=models.Q(('age_to__gte', models.F('age_from'))), name='ol_prem_row_age_valid'),
        ),
        migrations.AddConstraint(
            model_name='olpremiumraterow',
            constraint=models.CheckConstraint(check=models.Q(('term_to__gte', models.F('term_from'))), name='ol_prem_row_term_valid'),
        ),
        migrations.AddConstraint(
            model_name='olpremiumraterow',
            constraint=models.CheckConstraint(check=models.Q(('sum_assured_band_from__isnull', True), ('sum_assured_band_from__gte', 0), _connector='OR'), name='ol_prem_row_sa_from_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='olpremiumraterow',
            constraint=models.CheckConstraint(check=models.Q(('sum_assured_band_to__isnull', True), ('sum_assured_band_to__gte', 0), _connector='OR'), name='ol_prem_row_sa_to_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='olpremiumraterow',
            constraint=models.CheckConstraint(check=models.Q(('sum_assured_band_to__isnull', True), ('sum_assured_band_from__isnull', True), ('sum_assured_band_to__gte', models.F('sum_assured_band_from')), _connector='OR'), name='ol_prem_row_sa_valid'),
        ),
        migrations.AddConstraint(
            model_name='olpremiumraterow',
            constraint=models.CheckConstraint(check=models.Q(('rate__gte', 0)), name='ol_prem_row_rate_nonneg'),
        ),
    ]
