# Generated by Django 5.0.14 on 2026-08-18 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0009_olmortalityratetable_olmortalityraterow_and_more'),
        ('ordinary_life', '0007_oldocumentrecord_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='oljointlifesetup',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ol_joint_life_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='olmortalityraterow',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ol_mort_row_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='olmortalityratetable',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ol_mort_table_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='olpremiumraterow',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ol_prem_row_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='olpremiumratetable',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ol_prem_table_dates_valid'),
        ),
    ]
