# Generated by Django 5.0.14 on 2026-08-18 15:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0010_oljointlifesetup_ol_joint_life_dates_valid_and_more'),
        ('ordinary_life', '0007_oldocumentrecord_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLCashSurrenderValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_year_from', models.PositiveSmallIntegerField()),
                ('policy_year_to', models.PositiveSmallIntegerField()),
                ('age_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('term_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('term_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('smoker_status', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('surrender_value_factor', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_cash_surrender_values', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_surrender_values', to='ol_parameters.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product', 'plan', 'policy_year_from', 'age_from', 'term_from', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLInstallmentChargeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(choices=[('SINGLE', 'Single'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half yearly'), ('ANNUAL', 'Annual')], max_length=20)),
                ('charge_type', models.CharField(choices=[('FIXED', 'Fixed amount'), ('PERCENTAGE', 'Percentage'), ('FACTOR', 'Factor')], max_length=20)),
                ('rate_value', models.DecimalField(decimal_places=8, max_digits=12)),
                ('apply_on', models.CharField(choices=[('PREMIUM', 'Premium'), ('INSTALLMENT', 'Installment'), ('SUM_ASSURED', 'Sum assured'), ('POLICY_VALUE', 'Policy value'), ('DUE_AMOUNT', 'Due amount')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_installment_charge_rates', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installment_charge_rates', to='ol_parameters.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product', 'plan', 'frequency', 'charge_type', 'apply_on', '-effective_from', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLMortgageInterestFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factor', models.DecimalField(decimal_places=8, max_digits=12)),
                ('calculation_basis', models.CharField(choices=[('OUTSTANDING_PREMIUM', 'Outstanding premium'), ('LOAN_BALANCE', 'Loan balance'), ('PREMIUM', 'Premium'), ('SUM_ASSURED', 'Sum assured'), ('RESERVE', 'Reserve'), ('POLICY_VALUE', 'Policy value'), ('CUSTOM', 'Custom')], default='LOAN_BALANCE', max_length=40)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_mortgage_interest_factors', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mortgage_interest_factors', to='ol_parameters.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product', 'plan', 'calculation_basis', '-effective_from', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLReinstatementInterestRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=12)),
                ('calculation_basis', models.CharField(choices=[('OUTSTANDING_PREMIUM', 'Outstanding premium'), ('LOAN_BALANCE', 'Loan balance'), ('PREMIUM', 'Premium'), ('SUM_ASSURED', 'Sum assured'), ('RESERVE', 'Reserve'), ('POLICY_VALUE', 'Policy value'), ('CUSTOM', 'Custom')], default='OUTSTANDING_PREMIUM', max_length=40)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_reinstatement_interest_rates', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reinstatement_interest_rates', to='ol_parameters.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product', 'plan', 'calculation_basis', '-effective_from', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLReserveLoading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loading_type', models.CharField(choices=[('EXPENSE', 'Expense'), ('RISK', 'Risk'), ('CONTINGENCY', 'Contingency'), ('PROFIT', 'Profit'), ('CAPITAL', 'Capital'), ('OTHER', 'Other')], max_length=30)),
                ('loading_basis', models.CharField(choices=[('RESERVE', 'Reserve'), ('PREMIUM', 'Premium'), ('SUM_ASSURED', 'Sum assured'), ('POLICY_VALUE', 'Policy value'), ('CUSTOM', 'Custom')], max_length=30)),
                ('rate_value', models.DecimalField(decimal_places=8, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_reserve_loadings', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserve_loadings', to='ol_parameters.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product', 'plan', 'loading_type', 'loading_basis', '-effective_from', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLBonusRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bonus_type', models.CharField(choices=[('REVERSIONARY', 'Reversionary'), ('TERMINAL', 'Terminal'), ('LOYALTY', 'Loyalty'), ('SPECIAL', 'Special'), ('GUARANTEED', 'Guaranteed')], max_length=30)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=12)),
                ('valuation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('declaration_frequency', models.CharField(blank=True, choices=[('ANNUAL', 'Annual'), ('QUARTERLY', 'Quarterly'), ('MONTHLY', 'Monthly'), ('ON_MATURITY', 'On maturity'), ('AD_HOC', 'Ad hoc')], default='', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_bonus_rates', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bonus_rates', to='ol_parameters.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product', 'plan', 'bonus_type', 'valuation_year', '-effective_from', 'code'],
                'indexes': [models.Index(fields=['product', 'plan', 'bonus_type', 'is_active'], name='ol_bonus_rate_scope_idx'), models.Index(fields=['valuation_year', 'declaration_frequency', 'is_active'], name='ol_bonus_rate_dim_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='olbonusrate',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_bonus_rate_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olbonusrate',
            constraint=models.CheckConstraint(check=models.Q(('rate__gte', 0), ('rate__lte', 100)), name='ol_bonus_rate_rng_ck'),
        ),
        migrations.AddConstraint(
            model_name='olbonusrate',
            constraint=models.CheckConstraint(check=models.Q(('valuation_year__isnull', True), ('valuation_year__gt', 0), _connector='OR'), name='ol_bonus_year_pos_ck'),
        ),
        migrations.AddIndex(
            model_name='olcashsurrendervalue',
            index=models.Index(fields=['product', 'plan', 'is_active', 'effective_from'], name='ol_cash_surrender_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olcashsurrendervalue',
            index=models.Index(fields=['policy_year_from', 'policy_year_to', 'age_from', 'age_to'], name='ol_cash_surrender_band_idx'),
        ),
        migrations.AddIndex(
            model_name='olcashsurrendervalue',
            index=models.Index(fields=['gender', 'smoker_status', 'is_active'], name='ol_cash_surrender_demo_idx'),
        ),
        migrations.AddConstraint(
            model_name='olcashsurrendervalue',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_cash_surrender_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olcashsurrendervalue',
            constraint=models.CheckConstraint(check=models.Q(('policy_year_to__gte', models.F('policy_year_from'))), name='ol_cash_surrender_year_ck'),
        ),
        migrations.AddConstraint(
            model_name='olcashsurrendervalue',
            constraint=models.CheckConstraint(check=models.Q(('age_to__isnull', True), ('age_from__isnull', True), ('age_to__gte', models.F('age_from')), _connector='OR'), name='ol_cash_surrender_age_ck'),
        ),
        migrations.AddConstraint(
            model_name='olcashsurrendervalue',
            constraint=models.CheckConstraint(check=models.Q(('term_to__isnull', True), ('term_from__isnull', True), ('term_to__gte', models.F('term_from')), _connector='OR'), name='ol_cash_surrender_term_ck'),
        ),
        migrations.AddConstraint(
            model_name='olcashsurrendervalue',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('surrender_value_factor__isnull', False), ('rate__isnull', True)), models.Q(('surrender_value_factor__isnull', True), ('rate__isnull', False)), _connector='OR'), name='ol_cash_surrender_one_value_ck'),
        ),
        migrations.AddConstraint(
            model_name='olcashsurrendervalue',
            constraint=models.CheckConstraint(check=models.Q(('surrender_value_factor__isnull', True), models.Q(('surrender_value_factor__gte', 0), ('surrender_value_factor__lte', 1)), _connector='OR'), name='ol_cash_surrender_factor_rng_ck'),
        ),
        migrations.AddConstraint(
            model_name='olcashsurrendervalue',
            constraint=models.CheckConstraint(check=models.Q(('rate__isnull', True), models.Q(('rate__gte', 0), ('rate__lte', 100)), _connector='OR'), name='ol_cash_surrender_rate_rng_ck'),
        ),
        migrations.AddIndex(
            model_name='olinstallmentchargerate',
            index=models.Index(fields=['product', 'plan', 'frequency', 'is_active'], name='ol_install_charge_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olinstallmentchargerate',
            index=models.Index(fields=['charge_type', 'apply_on', 'is_active'], name='ol_install_charge_dim_idx'),
        ),
        migrations.AddConstraint(
            model_name='olinstallmentchargerate',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_install_charge_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olinstallmentchargerate',
            constraint=models.CheckConstraint(check=models.Q(('rate_value__gte', 0)), name='ol_install_charge_nonneg_ck'),
        ),
        migrations.AddIndex(
            model_name='olmortgageinterestfactor',
            index=models.Index(fields=['product', 'plan', 'calculation_basis', 'is_active'], name='ol_mortgage_factor_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olmortgageinterestfactor',
            index=models.Index(fields=['effective_from', 'effective_to', 'is_active'], name='ol_mortgage_factor_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='olmortgageinterestfactor',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_mortgage_factor_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olmortgageinterestfactor',
            constraint=models.CheckConstraint(check=models.Q(('factor__gt', 0)), name='ol_mortgage_factor_pos_ck'),
        ),
        migrations.AddIndex(
            model_name='olreinstatementinterestrate',
            index=models.Index(fields=['product', 'plan', 'calculation_basis', 'is_active'], name='ol_rein_interest_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olreinstatementinterestrate',
            index=models.Index(fields=['effective_from', 'effective_to', 'is_active'], name='ol_rein_interest_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='olreinstatementinterestrate',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_rein_interest_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olreinstatementinterestrate',
            constraint=models.CheckConstraint(check=models.Q(('rate__gte', 0), ('rate__lte', 100)), name='ol_rein_interest_rate_rng_ck'),
        ),
        migrations.AddIndex(
            model_name='olreserveloading',
            index=models.Index(fields=['product', 'plan', 'loading_type', 'is_active'], name='ol_reserve_load_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olreserveloading',
            index=models.Index(fields=['loading_basis', 'is_active', 'effective_from'], name='ol_reserve_load_basis_idx'),
        ),
        migrations.AddConstraint(
            model_name='olreserveloading',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_reserve_load_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olreserveloading',
            constraint=models.CheckConstraint(check=models.Q(('rate_value__gte', 0), ('rate_value__lte', 100)), name='ol_reserve_load_rate_rng_ck'),
        ),
    ]
