# Generated by Django 5.0.14 on 2026-08-18 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0011_olcashsurrendervalue_olinstallmentchargerate_and_more'),
        ('ordinary_life', '0007_oldocumentrecord_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='olbonusrate',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ol_bonus_rate_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='olcashsurrendervalue',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ol_cash_surrender_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='olinstallmentchargerate',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ol_install_charge_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='olmortgageinterestfactor',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ol_mortgage_factor_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='olreinstatementinterestrate',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ol_rein_interest_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='olreserveloading',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ol_reserve_load_dates_ck'),
        ),
    ]
