# Generated by Django 5.0.14 on 2026-08-18 16:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0012_olbonusrate_ol_bonus_rate_dates_ck_and_more'),
        ('ordinary_life', '0007_oldocumentrecord_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLRiderSetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider_category', models.CharField(choices=[('ACCIDENT', 'Accident'), ('CRITICAL_ILLNESS', 'Critical illness'), ('DISABILITY', 'Disability'), ('HEALTH', 'Health'), ('SAVINGS', 'Savings'), ('WAIVER', 'Waiver'), ('OTHER', 'Other')], max_length=40)),
                ('benefit_type', models.CharField(choices=[('ACCIDENTAL_DEATH', 'Accidental death'), ('CRITICAL_ILLNESS', 'Critical illness'), ('DEATH', 'Death'), ('DISABILITY', 'Disability'), ('HOSPITAL_CASH', 'Hospital cash'), ('INCOME_REPLACEMENT', 'Income replacement'), ('WAIVER_PREMIUM', 'Waiver of premium'), ('OTHER', 'Other')], max_length=50)),
                ('calculation_basis', models.CharField(choices=[('SUM_ASSURED', 'Sum assured'), ('PREMIUM', 'Premium'), ('AGE_TERM', 'Age and term'), ('FLAT', 'Flat'), ('CUSTOM', 'Custom')], default='SUM_ASSURED', max_length=30)),
                ('min_age', models.PositiveSmallIntegerField(default=0)),
                ('max_age', models.PositiveSmallIntegerField(default=150)),
                ('min_term', models.PositiveSmallIntegerField(default=1)),
                ('max_term', models.PositiveSmallIntegerField(default=100)),
                ('min_sum_assured', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('max_sum_assured', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('waiting_period_days', models.PositiveIntegerField(default=0)),
                ('allows_standalone', models.BooleanField(default=False)),
                ('requires_underwriting', models.BooleanField(default=True)),
                ('exclusion_rules', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_rider_setups', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rider_setups', to='ol_parameters.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rider_category', 'benefit_type', 'name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLRiderRateTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating_basis', models.CharField(choices=[('SUM_ASSURED', 'Sum assured'), ('AGE_TERM', 'Age and term'), ('PREMIUM', 'Premium'), ('FLAT', 'Flat'), ('CUSTOM', 'Custom')], default='AGE_TERM', max_length=40)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_rider_rate_tables', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rider_rate_tables', to='ol_parameters.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_tables', to='ol_parameters.olridersetup')),
            ],
            options={
                'ordering': ['table_code', 'rider', '-effective_from', 'version'],
            },
        ),
        migrations.CreateModel(
            name='OLRiderRateRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(db_index=True, max_length=30)),
                ('smoker_status', models.CharField(db_index=True, max_length=30)),
                ('age_from', models.PositiveSmallIntegerField()),
                ('age_to', models.PositiveSmallIntegerField()),
                ('term_from', models.PositiveSmallIntegerField()),
                ('term_to', models.PositiveSmallIntegerField()),
                ('frequency', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('sum_assured_band_from', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sum_assured_band_to', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('rate_unit', models.CharField(choices=[('PER_THOUSAND_SUM_ASSURED', 'Per thousand sum assured'), ('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed amount'), ('FACTOR', 'Factor')], default='PER_THOUSAND_SUM_ASSURED', max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ol_parameters.olriderratetable')),
            ],
            options={
                'ordering': ['table', 'gender', 'smoker_status', 'frequency', 'age_from', 'term_from', 'code'],
                'indexes': [models.Index(fields=['table', 'gender', 'smoker_status', 'frequency'], name='ol_rider_row_scope_idx'), models.Index(fields=['age_from', 'age_to', 'term_from', 'term_to'], name='ol_rider_row_band_idx'), models.Index(fields=['is_active', 'effective_from'], name='ol_rider_row_dates_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='olriderraterow',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ol_rider_row_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='olriderraterow',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_rider_rate_row_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olriderraterow',
            constraint=models.CheckConstraint(check=models.Q(('age_to__gte', models.F('age_from'))), name='ol_rider_row_age_order_ck'),
        ),
        migrations.AddConstraint(
            model_name='olriderraterow',
            constraint=models.CheckConstraint(check=models.Q(('term_to__gte', models.F('term_from'))), name='ol_rider_row_term_order_ck'),
        ),
        migrations.AddConstraint(
            model_name='olriderraterow',
            constraint=models.CheckConstraint(check=models.Q(('sum_assured_band_from__isnull', True), ('sum_assured_band_from__gte', 0), _connector='OR'), name='ol_rider_row_sa_from_ck'),
        ),
        migrations.AddConstraint(
            model_name='olriderraterow',
            constraint=models.CheckConstraint(check=models.Q(('sum_assured_band_to__isnull', True), ('sum_assured_band_to__gte', 0), _connector='OR'), name='ol_rider_row_sa_to_ck'),
        ),
        migrations.AddConstraint(
            model_name='olriderraterow',
            constraint=models.CheckConstraint(check=models.Q(('sum_assured_band_to__isnull', True), ('sum_assured_band_from__isnull', True), ('sum_assured_band_to__gte', models.F('sum_assured_band_from')), _connector='OR'), name='ol_rider_row_sa_order_ck'),
        ),
        migrations.AddConstraint(
            model_name='olriderraterow',
            constraint=models.CheckConstraint(check=models.Q(('rate__gte', 0)), name='ol_rider_row_rate_nonneg'),
        ),
        migrations.AddIndex(
            model_name='olridersetup',
            index=models.Index(fields=['rider_category', 'benefit_type', 'is_active'], name='ol_rider_setup_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='olridersetup',
            index=models.Index(fields=['product', 'plan', 'is_active'], name='ol_rider_setup_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olridersetup',
            index=models.Index(fields=['requires_underwriting', 'allows_standalone', 'is_active'], name='ol_rider_setup_rule_idx'),
        ),
        migrations.AddConstraint(
            model_name='olridersetup',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ol_rider_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='olridersetup',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_rider_setup_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olridersetup',
            constraint=models.CheckConstraint(check=models.Q(('max_age__gte', models.F('min_age'))), name='ol_rider_age_order_ck'),
        ),
        migrations.AddConstraint(
            model_name='olridersetup',
            constraint=models.CheckConstraint(check=models.Q(('min_age__lte', 150), ('max_age__lte', 150)), name='ol_rider_age_range_ck'),
        ),
        migrations.AddConstraint(
            model_name='olridersetup',
            constraint=models.CheckConstraint(check=models.Q(('min_term__gte', 1), ('max_term__gte', models.F('min_term'))), name='ol_rider_term_range_ck'),
        ),
        migrations.AddConstraint(
            model_name='olridersetup',
            constraint=models.CheckConstraint(check=models.Q(('min_sum_assured__isnull', True), ('min_sum_assured__gte', 0), _connector='OR'), name='ol_rider_min_sa_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='olridersetup',
            constraint=models.CheckConstraint(check=models.Q(('max_sum_assured__isnull', True), ('max_sum_assured__gte', 0), _connector='OR'), name='ol_rider_max_sa_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='olridersetup',
            constraint=models.CheckConstraint(check=models.Q(('max_sum_assured__isnull', True), ('min_sum_assured__isnull', True), ('max_sum_assured__gte', models.F('min_sum_assured')), _connector='OR'), name='ol_rider_sa_order_ck'),
        ),
        migrations.AddIndex(
            model_name='olriderratetable',
            index=models.Index(fields=['rider', 'product', 'plan', 'is_active'], name='ol_rider_rt_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olriderratetable',
            index=models.Index(fields=['table_code', 'version'], name='ol_rider_rt_ver_idx'),
        ),
        migrations.AddIndex(
            model_name='olriderratetable',
            index=models.Index(fields=['is_active', 'effective_from'], name='ol_rider_rt_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='olriderratetable',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ol_rider_rt_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='olriderratetable',
            constraint=models.UniqueConstraint(fields=('table_code', 'version'), name='ol_rider_rt_code_ver_uq'),
        ),
    ]
