# Generated by Django 5.0.14 on 2026-08-18 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0013_olridersetup_olriderratetable_olriderraterow_and_more'),
        ('ordinary_life', '0007_oldocumentrecord_idempotency_key_and_more'),
        ('partner_onboarding', '0014_applicationpartnertype_kyc_status'),
        ('partners', '0011_partner_created_by_partner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLAgentCommissionSetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intermediary_type', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('distribution_channel', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('currency', models.CharField(blank=True, db_index=True, default='', max_length=3)),
                ('commission_type', models.CharField(choices=[('FIRST_PREMIUM', 'First premium'), ('RENEWAL_PREMIUM', 'Renewal premium'), ('ADMINISTRATIVE', 'Administrative'), ('HIERARCHICAL', 'Hierarchical'), ('OVERRIDE', 'Override'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('premium_year_from', models.PositiveIntegerField(blank=True, null=True)),
                ('premium_year_to', models.PositiveIntegerField(blank=True, null=True)),
                ('policy_year_from', models.PositiveIntegerField(blank=True, null=True)),
                ('policy_year_to', models.PositiveIntegerField(blank=True, null=True)),
                ('rate_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed'), ('FACTOR', 'Factor')], db_index=True, max_length=10)),
                ('rate_value', models.DecimalField(decimal_places=8, max_digits=18)),
                ('minimum_commission', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('maximum_commission', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('priority', models.PositiveIntegerField(db_index=True, default=100)),
                ('reason', models.TextField(blank=True, default='')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_agent_commission_setups', to='partner_onboarding.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, help_text='Optional partner or agent scope; agent intermediaries are represented by this relation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_agent_commission_setups', to='partners.partner')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_agent_commission_setups', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_commission_setups', to='ol_parameters.olproduct')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_commission_setups', to='ol_parameters.olridersetup')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'commission_type', '-effective_from', 'code'],
                'indexes': [models.Index(fields=['partner', 'product', 'plan', 'rider', 'commission_type', 'distribution_channel'], name='ol_agent_comm_scope_idx'), models.Index(fields=['priority', 'is_active', 'effective_from'], name='ol_agent_comm_priority_idx'), models.Index(fields=['product', 'commission_type', 'is_active'], name='ol_agent_comm_product_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='olagentcommissionsetup',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_agent_comm_setup_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olagentcommissionsetup',
            constraint=models.CheckConstraint(check=models.Q(('premium_year_to__isnull', True), ('premium_year_from__isnull', True), ('premium_year_to__gte', models.F('premium_year_from')), _connector='OR'), name='ol_agent_comm_prem_years_ck'),
        ),
        migrations.AddConstraint(
            model_name='olagentcommissionsetup',
            constraint=models.CheckConstraint(check=models.Q(('policy_year_to__isnull', True), ('policy_year_from__isnull', True), ('policy_year_to__gte', models.F('policy_year_from')), _connector='OR'), name='ol_agent_comm_policy_years_ck'),
        ),
        migrations.AddConstraint(
            model_name='olagentcommissionsetup',
            constraint=models.CheckConstraint(check=models.Q(('rate_value__gte', 0)), name='ol_agent_comm_rate_nonneg_ck'),
        ),
        migrations.AddConstraint(
            model_name='olagentcommissionsetup',
            constraint=models.CheckConstraint(check=models.Q(('minimum_commission__isnull', True), ('minimum_commission__gte', 0), _connector='OR'), name='ol_agent_comm_min_nonneg_ck'),
        ),
        migrations.AddConstraint(
            model_name='olagentcommissionsetup',
            constraint=models.CheckConstraint(check=models.Q(('maximum_commission__isnull', True), ('maximum_commission__gte', 0), _connector='OR'), name='ol_agent_comm_max_nonneg_ck'),
        ),
        migrations.AddConstraint(
            model_name='olagentcommissionsetup',
            constraint=models.CheckConstraint(check=models.Q(('maximum_commission__isnull', True), ('minimum_commission__isnull', True), ('maximum_commission__gte', models.F('minimum_commission')), _connector='OR'), name='ol_agent_comm_min_max_ck'),
        ),
    ]
