# Generated by Django 5.0.14 on 2026-08-18 17:00

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0014_olagentcommissionsetup_and_more'),
        ('ordinary_life', '0007_oldocumentrecord_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLLoanSystemSetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_policy_loans', models.BooleanField(default=True)),
                ('loan_basis', models.CharField(choices=[('CASH_VALUE', 'Cash value'), ('PAID_UP_VALUE', 'Paid-up value'), ('PREMIUM_BASED', 'Premium based'), ('OTHER', 'Other')], default='CASH_VALUE', max_length=30)),
                ('max_loan_percentage_of_cash_value', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('min_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('max_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('loan_currency', models.CharField(blank=True, db_index=True, default='', max_length=3)),
                ('repayment_options', models.JSONField(blank=True, default=list)),
                ('auto_deduct_from_benefits', models.BooleanField(default=True)),
                ('effect_on_claim', models.CharField(choices=[('DEDUCT_BALANCE', 'Deduct loan balance'), ('REDUCE_BENEFIT', 'Reduce benefit'), ('BLOCK_BENEFIT', 'Block benefit'), ('NET_BENEFIT', 'Pay benefit net of loan'), ('NO_EFFECT', 'No effect'), ('OTHER', 'Other')], default='DEDUCT_BALANCE', max_length=30)),
                ('effect_on_surrender', models.CharField(choices=[('DEDUCT_BALANCE', 'Deduct loan balance'), ('REDUCE_BENEFIT', 'Reduce benefit'), ('BLOCK_BENEFIT', 'Block benefit'), ('NET_BENEFIT', 'Pay benefit net of loan'), ('NO_EFFECT', 'No effect'), ('OTHER', 'Other')], default='DEDUCT_BALANCE', max_length=30)),
                ('effect_on_maturity', models.CharField(choices=[('DEDUCT_BALANCE', 'Deduct loan balance'), ('REDUCE_BENEFIT', 'Reduce benefit'), ('BLOCK_BENEFIT', 'Block benefit'), ('NET_BENEFIT', 'Pay benefit net of loan'), ('NO_EFFECT', 'No effect'), ('OTHER', 'Other')], default='DEDUCT_BALANCE', max_length=30)),
                ('require_approval', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_loan_system_setups', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_system_setups', to='ol_parameters.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product', 'plan', '-effective_from', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLLoanInterestControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interest_rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('compounding_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMI_ANNUAL', 'Semi-annual'), ('ANNUAL', 'Annual'), ('OTHER', 'Other')], default='ANNUAL', max_length=20)),
                ('interest_calculation_basis', models.CharField(choices=[('SIMPLE', 'Simple interest'), ('COMPOUND', 'Compound interest'), ('ACTUAL_365', 'Actual/365'), ('ACTUAL_360', 'Actual/360'), ('OTHER', 'Other')], default='COMPOUND', max_length=20)),
                ('grace_period_days', models.PositiveIntegerField(default=0)),
                ('penalty_interest_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('interest_suspension_rule', models.CharField(blank=True, default='', max_length=120)),
                ('capitalize_interest', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_loan_interest_controls', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_interest_controls', to='ol_parameters.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product', 'plan', '-effective_from', 'code'],
                'indexes': [models.Index(fields=['product', 'plan', 'is_active', 'effective_from'], name='ol_loan_interest_scope_idx'), models.Index(fields=['compounding_frequency', 'interest_calculation_basis'], name='ol_loan_interest_basis_idx'), models.Index(fields=['capitalize_interest', 'is_active'], name='ol_loan_interest_cap_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='olloaninterestcontrol',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_loan_interest_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olloaninterestcontrol',
            constraint=models.CheckConstraint(check=models.Q(('interest_rate__gte', 0), ('interest_rate__lte', 100)), name='ol_loan_interest_rate_rng'),
        ),
        migrations.AddConstraint(
            model_name='olloaninterestcontrol',
            constraint=models.CheckConstraint(check=models.Q(('penalty_interest_rate__isnull', True), models.Q(('penalty_interest_rate__gte', 0), ('penalty_interest_rate__lte', 100)), _connector='OR'), name='ol_loan_interest_penalty_rng'),
        ),
        migrations.AddIndex(
            model_name='olloansystemsetup',
            index=models.Index(fields=['product', 'plan', 'is_active', 'effective_from'], name='ol_loan_system_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olloansystemsetup',
            index=models.Index(fields=['loan_basis', 'is_active'], name='ol_loan_system_basis_idx'),
        ),
        migrations.AddIndex(
            model_name='olloansystemsetup',
            index=models.Index(fields=['allow_policy_loans', 'is_active'], name='ol_loan_system_allowed_idx'),
        ),
        migrations.AddConstraint(
            model_name='olloansystemsetup',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_loan_system_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olloansystemsetup',
            constraint=models.CheckConstraint(check=models.Q(('max_loan_percentage_of_cash_value__gte', 0), ('max_loan_percentage_of_cash_value__lte', 100)), name='ol_loan_system_pct_rng'),
        ),
        migrations.AddConstraint(
            model_name='olloansystemsetup',
            constraint=models.CheckConstraint(check=models.Q(('min_loan_amount__isnull', True), ('min_loan_amount__gt', 0), _connector='OR'), name='ol_loan_system_min_pos'),
        ),
        migrations.AddConstraint(
            model_name='olloansystemsetup',
            constraint=models.CheckConstraint(check=models.Q(('max_loan_amount__isnull', True), ('max_loan_amount__gt', 0), _connector='OR'), name='ol_loan_system_max_pos'),
        ),
        migrations.AddConstraint(
            model_name='olloansystemsetup',
            constraint=models.CheckConstraint(check=models.Q(('max_loan_amount__isnull', True), ('min_loan_amount__isnull', True), ('max_loan_amount__gte', models.F('min_loan_amount')), _connector='OR'), name='ol_loan_system_min_max_ck'),
        ),
    ]
