# Generated by Django 5.0.14 on 2026-08-18 17:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0015_olloansystemsetup_olloaninterestcontrol_and_more'),
        ('ordinary_life', '0007_oldocumentrecord_idempotency_key_and_more'),
        ('partners', '0011_partner_created_by_partner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLMedicalCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_category', models.CharField(db_index=True, max_length=80)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['medical_category', 'name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLMedicalFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('facility_type', models.CharField(max_length=60)),
                ('registration_number', models.CharField(blank=True, default='', max_length=120)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='TZ', max_length=100)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_medical_facilities', to='partners.partner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'facility_code'],
            },
        ),
        migrations.CreateModel(
            name='OLMedicalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition_category', models.CharField(db_index=True, max_length=80)),
                ('severity', models.CharField(db_index=True, max_length=30)),
                ('waiting_period_days', models.PositiveIntegerField(default=0)),
                ('exclusion_flag', models.BooleanField(default=False)),
                ('loading_flag', models.BooleanField(default=False)),
                ('underwriting_note', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['condition_category', 'severity', 'name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLMedicalLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_from', models.PositiveSmallIntegerField(default=0)),
                ('age_to', models.PositiveSmallIntegerField(default=150)),
                ('sum_assured_from', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sum_assured_to', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('limit_type', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MEDICAL', 'Medical'), ('FINANCIAL', 'Financial'), ('UNDERWRITING', 'Underwriting'), ('OTHER', 'Other')], default='MEDICAL', max_length=30)),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('required_frequency', models.CharField(choices=[('ONE_OFF', 'One-off'), ('ANNUAL', 'Annual'), ('BIENNIAL', 'Biennial'), ('EVERY_TWO_YEARS', 'Every two years'), ('AS_REQUIRED', 'As required'), ('OTHER', 'Other')], default='ANNUAL', max_length=30)),
                ('mandatory_flag', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medical_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='limits', to='ol_parameters.olmedicalcode')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_parameter_medical_limits', to='ordinary_life.olplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_limits', to='ol_parameters.olproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['medical_code', 'product', 'plan', 'age_from', 'sum_assured_from', '-effective_from', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLMedicalPractitioner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practitioner_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medical_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='practitioners', to='ol_parameters.olmedicalfacility')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ol_medical_practitioners', to='partners.partner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'practitioner_code'],
            },
        ),
        migrations.CreateModel(
            name='OLPersonalHabit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit_category', models.CharField(choices=[('SMOKING', 'Smoking'), ('ALCOHOL', 'Alcohol'), ('DRUG', 'Drug'), ('OCCUPATION_HAZARD', 'Occupation hazard'), ('LIFESTYLE', 'Lifestyle'), ('OTHER', 'Other')], max_length=40)),
                ('question_text', models.TextField()),
                ('underwriting_impact', models.CharField(choices=[('NONE', 'None'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NONE', max_length=20)),
                ('requires_evidence', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['habit_category', 'name', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='olmedicalcode',
            index=models.Index(fields=['medical_category', 'is_active'], name='ol_med_code_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='olmedicalcode',
            index=models.Index(fields=['is_active', 'effective_from'], name='ol_med_code_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='olmedicalcode',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_medical_code_code_uq'),
        ),
        migrations.AddIndex(
            model_name='olmedicalfacility',
            index=models.Index(fields=['facility_type', 'approval_status', 'is_active'], name='ol_med_facility_type_idx'),
        ),
        migrations.AddIndex(
            model_name='olmedicalfacility',
            index=models.Index(fields=['city', 'country', 'is_active'], name='ol_med_facility_loc_idx'),
        ),
        migrations.AddIndex(
            model_name='olmedicalfacility',
            index=models.Index(fields=['partner', 'is_active'], name='ol_med_facility_partner_idx'),
        ),
        migrations.AddConstraint(
            model_name='olmedicalfacility',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_med_facility_code_uq'),
        ),
        migrations.AddIndex(
            model_name='olmedicalhistory',
            index=models.Index(fields=['condition_category', 'is_active'], name='ol_med_hist_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='olmedicalhistory',
            index=models.Index(fields=['severity', 'is_active'], name='ol_med_hist_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='olmedicalhistory',
            index=models.Index(fields=['exclusion_flag', 'loading_flag', 'is_active'], name='ol_med_hist_rules_idx'),
        ),
        migrations.AddConstraint(
            model_name='olmedicalhistory',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_med_history_code_uq'),
        ),
        migrations.AddIndex(
            model_name='olmedicallimit',
            index=models.Index(fields=['medical_code', 'product', 'plan', 'is_active'], name='ol_med_limit_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='olmedicallimit',
            index=models.Index(fields=['limit_type', 'required_frequency', 'is_active'], name='ol_med_limit_type_idx'),
        ),
        migrations.AddIndex(
            model_name='olmedicallimit',
            index=models.Index(fields=['age_from', 'age_to', 'sum_assured_from'], name='ol_med_limit_dim_idx'),
        ),
        migrations.AddIndex(
            model_name='olmedicallimit',
            index=models.Index(fields=['effective_from', 'effective_to'], name='ol_med_limit_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='olmedicallimit',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_medical_limit_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olmedicallimit',
            constraint=models.CheckConstraint(check=models.Q(('age_from__gte', 0), ('age_to__lte', 150), ('age_to__gte', models.F('age_from'))), name='ol_med_limit_age_rng'),
        ),
        migrations.AddConstraint(
            model_name='olmedicallimit',
            constraint=models.CheckConstraint(check=models.Q(('sum_assured_from__isnull', True), ('sum_assured_from__gte', 0), _connector='OR'), name='ol_med_limit_sa_from_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='olmedicallimit',
            constraint=models.CheckConstraint(check=models.Q(('sum_assured_to__isnull', True), ('sum_assured_to__gte', 0), _connector='OR'), name='ol_med_limit_sa_to_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='olmedicallimit',
            constraint=models.CheckConstraint(check=models.Q(('sum_assured_to__isnull', True), ('sum_assured_from__isnull', True), ('sum_assured_to__gte', models.F('sum_assured_from')), _connector='OR'), name='ol_med_limit_sa_order'),
        ),
        migrations.AddConstraint(
            model_name='olmedicallimit',
            constraint=models.CheckConstraint(check=models.Q(('limit_amount__gt', 0)), name='ol_med_limit_amount_pos'),
        ),
        migrations.AddIndex(
            model_name='olmedicalpractitioner',
            index=models.Index(fields=['specialty', 'approval_status', 'is_active'], name='ol_med_practitioner_spec_idx'),
        ),
        migrations.AddIndex(
            model_name='olmedicalpractitioner',
            index=models.Index(fields=['medical_facility', 'is_active'], name='ol_med_practitioner_fac_idx'),
        ),
        migrations.AddIndex(
            model_name='olmedicalpractitioner',
            index=models.Index(fields=['partner', 'is_active'], name='ol_med_pract_partner_idx'),
        ),
        migrations.AddConstraint(
            model_name='olmedicalpractitioner',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_med_practitioner_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olmedicalpractitioner',
            constraint=models.UniqueConstraint(fields=('license_number',), name='ol_med_practitioner_license_uq'),
        ),
        migrations.AddIndex(
            model_name='olpersonalhabit',
            index=models.Index(fields=['habit_category', 'is_active'], name='ol_habit_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='olpersonalhabit',
            index=models.Index(fields=['underwriting_impact', 'is_active'], name='ol_habit_impact_idx'),
        ),
        migrations.AddIndex(
            model_name='olpersonalhabit',
            index=models.Index(fields=['requires_evidence', 'is_active'], name='ol_habit_evidence_idx'),
        ),
        migrations.AddConstraint(
            model_name='olpersonalhabit',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_personal_habit_code_uq'),
        ),
    ]
