# Generated by Django 5.0.14 on 2026-08-18 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0016_olmedicalcode_olmedicalfacility_olmedicalhistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLClaimType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_category', models.CharField(choices=[('DEATH', 'Death'), ('CRITICAL_ILLNESS', 'Critical illness'), ('DISABILITY', 'Disability'), ('SURRENDER', 'Surrender'), ('MATURITY', 'Maturity'), ('MEDICAL', 'Medical'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('calculation_basis', models.CharField(choices=[('SUM_ASSURED', 'Sum assured'), ('CASH_VALUE', 'Cash value'), ('BENEFIT_AMOUNT', 'Benefit amount'), ('FIXED_AMOUNT', 'Fixed amount'), ('PERCENTAGE', 'Percentage'), ('CUSTOM', 'Custom')], default='SUM_ASSURED', max_length=30)),
                ('duplicate_check_rule', models.CharField(choices=[('POLICY_AND_TYPE', 'Policy and claim type'), ('POLICY_AND_REASON', 'Policy and claim reason'), ('POLICY_AND_EVENT_DATE', 'Policy and event date'), ('NONE', 'No duplicate check'), ('CUSTOM', 'Custom')], default='POLICY_AND_TYPE', max_length=35)),
                ('waiting_period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('payable_to_rules', models.JSONField(blank=True, default=dict)),
                ('allow_waiver_of_premium', models.BooleanField(default=False)),
                ('require_documents', models.JSONField(blank=True, default=list)),
                ('require_approval', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['claim_category', 'name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLClaimReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason_category', models.CharField(choices=[('EVENT', 'Insured event'), ('MEDICAL', 'Medical condition'), ('ADMINISTRATIVE', 'Administrative'), ('FINANCIAL', 'Financial'), ('DOCUMENTARY', 'Documentary'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('claim_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claim_reasons', to='ol_parameters.olclaimtype')),
            ],
            options={
                'ordering': ['reason_category', 'name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLCorrespondentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correspondence_category', models.CharField(choices=[('CLAIM_ACKNOWLEDGEMENT', 'Claim acknowledgement'), ('DOCUMENT_REQUEST', 'Document request'), ('ASSESSMENT', 'Assessment'), ('DECISION', 'Decision'), ('PAYMENT', 'Payment'), ('DISCHARGE', 'Discharge'), ('OTHER', 'Other')], db_index=True, max_length=35)),
                ('communication_channel', models.CharField(choices=[('LETTER', 'Letter'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PORTAL', 'Portal'), ('WHATSAPP', 'WhatsApp'), ('SYSTEM', 'System'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('purpose', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['correspondence_category', 'name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLDischargeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discharge_category', models.CharField(choices=[('FULL_AND_FINAL', 'Full and final'), ('PARTIAL', 'Partial'), ('RELEASE', 'Release'), ('ASSIGNMENT', 'Assignment'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('template_code', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['discharge_category', 'name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OLClaimStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('badge_type', models.CharField(choices=[('NEUTRAL', 'Neutral'), ('INFO', 'Information'), ('WARNING', 'Warning'), ('SUCCESS', 'Success'), ('DANGER', 'Danger'), ('PRIMARY', 'Primary')], default='NEUTRAL', max_length=20)),
                ('is_terminal', models.BooleanField(default=False)),
                ('is_payable', models.BooleanField(default=False)),
                ('allowed_transitions', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'name', 'code'],
                'indexes': [models.Index(fields=['display_order', 'is_active'], name='ol_claim_status_order_idx'), models.Index(fields=['is_terminal', 'is_active'], name='ol_claim_status_term_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='olclaimstatus',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_claim_status_code_uq'),
        ),
        migrations.AddIndex(
            model_name='olclaimtype',
            index=models.Index(fields=['claim_category', 'is_active'], name='ol_claim_type_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='olclaimtype',
            index=models.Index(fields=['require_approval', 'is_active'], name='ol_claim_type_appr_idx'),
        ),
        migrations.AddConstraint(
            model_name='olclaimtype',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_claim_type_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='olclaimtype',
            constraint=models.CheckConstraint(check=models.Q(('waiting_period_days__isnull', True), ('waiting_period_days__gte', 0), _connector='OR'), name='ol_claim_type_wait_ck'),
        ),
        migrations.AddIndex(
            model_name='olclaimreason',
            index=models.Index(fields=['claim_type', 'is_active'], name='ol_claim_reason_type_idx'),
        ),
        migrations.AddIndex(
            model_name='olclaimreason',
            index=models.Index(fields=['reason_category', 'is_active'], name='ol_claim_reason_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='olclaimreason',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_claim_reason_code_uq'),
        ),
        migrations.AddIndex(
            model_name='olcorrespondenttype',
            index=models.Index(fields=['correspondence_category', 'is_active'], name='ol_corr_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='olcorrespondenttype',
            index=models.Index(fields=['communication_channel', 'is_active'], name='ol_corr_chan_idx'),
        ),
        migrations.AddConstraint(
            model_name='olcorrespondenttype',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_correspondent_type_code_uq'),
        ),
        migrations.AddIndex(
            model_name='oldischargetype',
            index=models.Index(fields=['discharge_category', 'is_active'], name='ol_discharge_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='oldischargetype',
            index=models.Index(fields=['template_code', 'is_active'], name='ol_discharge_tpl_idx'),
        ),
        migrations.AddConstraint(
            model_name='oldischargetype',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_discharge_type_code_uq'),
        ),
    ]
