# Generated by Django 5.0.14 on 2026-08-23 05:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0017_olclaimtype_olclaimreason_olcorrespondenttype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLProposalStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('applies_to', models.CharField(db_index=True, default='PROPOSAL', max_length=40)),
                ('is_terminal', models.BooleanField(default=False)),
                ('allowed_transitions', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['applies_to', 'display_order', 'name', 'code'],
                'indexes': [models.Index(fields=['applies_to', 'is_active', 'display_order'], name='ol_proposal_status_idx'), models.Index(fields=['is_terminal', 'is_active'], name='ol_prop_status_terminal_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='olproposalstatus',
            constraint=models.UniqueConstraint(fields=('code',), name='ol_proposal_status_code_uq'),
        ),
    ]
