# Generated by Django 5.0.14 on 2026-08-26 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0019_olproposaldocumentrequirement_and_more'),
        ('ordinary_life', '0007_oldocumentrecord_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='olloansystemsetup',
            name='auto_approve_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddConstraint(
            model_name='olloansystemsetup',
            constraint=models.CheckConstraint(check=models.Q(('auto_approve_limit__isnull', True), ('auto_approve_limit__gt', 0), _connector='OR'), name='ol_loan_system_auto_approve_pos'),
        ),
    ]
