# Generated by Django 5.0.14 on 2026-08-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol_parameters', '0020_olloansystemsetup_auto_approve_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olloaninterestcontrol',
            name='penalty_period_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
