# Generated by Django 5.0.14 on 2026-06-20 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner_onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner Type',
                'verbose_name_plural': 'Partner Types',
                'db_table': 'partner_partner_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('partner_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CORPORATE', 'Corporate'), ('AGENT', 'Agent'), ('BROKER', 'Broker')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('identification_type', models.CharField(blank=True, choices=[('NIN', 'National Identification Number'), ('ZAN_ID', 'Zanzibar ID'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('TIN', 'Tax Identification Number'), ('VOTER_ID', 'Voter ID'), ('RESIDENT_PERMIT', 'Resident Permit'), ('MILITARY_ID', 'Military ID')], max_length=30)),
                ('identification_number', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Hon', 'Hon'), ('Eng', 'Eng'), ('Rev', 'Rev')], max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('other_name', models.CharField(blank=True, max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Separated')], max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('nationality', models.CharField(blank=True, choices=[('Tanzanian', 'Tanzanian'), ('Kenyan', 'Kenyan'), ('Ugandan', 'Ugandan'), ('Rwandan', 'Rwandan'), ('Burundian', 'Burundian'), ('Congolese', 'Congolese'), ('South African', 'South African'), ('Nigerian', 'Nigerian'), ('Ghanaian', 'Ghanaian'), ('Ethiopian', 'Ethiopian'), ('Somali', 'Somali'), ('Mozambican', 'Mozambican'), ('Malawian', 'Malawian'), ('Zambian', 'Zambian'), ('Zimbabwean', 'Zimbabwean'), ('Indian', 'Indian'), ('Chinese', 'Chinese'), ('British', 'British'), ('American', 'American'), ('Other', 'Other')], max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('tin_number', models.CharField(blank=True, max_length=50)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, choices=[('TECHNOLOGY', 'Technology'), ('HEALTHCARE', 'Healthcare & Pharmaceuticals'), ('FINANCIAL_SERVICES', 'Financial Services & Banking'), ('CONSUMER_GOODS', 'Consumer Goods & Retail'), ('ENERGY', 'Energy & Utilities'), ('MANUFACTURING', 'Manufacturing & Industrial'), ('TELECOMMUNICATIONS', 'Telecommunications'), ('TRANSPORTATION', 'Transportation & Logistics'), ('REAL_ESTATE', 'Real Estate & Construction'), ('MEDIA', 'Media & Entertainment'), ('AEROSPACE', 'Aerospace & Defense'), ('AUTOMOTIVE', 'Automotive'), ('AGRICULTURE', 'Agriculture & Food Production'), ('HOSPITALITY', 'Hospitality & Tourism'), ('EDUCATION', 'Education & Training'), ('PROFESSIONAL_SERVICES', 'Professional Services & Consulting'), ('INSURANCE', 'Insurance'), ('MINING', 'Mining & Metals'), ('CHEMICALS', 'Chemicals'), ('TEXTILES', 'Textiles & Apparel'), ('ENVIRONMENTAL', 'Environmental Services'), ('BIOTECHNOLOGY', 'Biotechnology'), ('E_COMMERCE', 'E-commerce'), ('RENEWABLE_ENERGY', 'Renewable Energy'), ('CYBERSECURITY', 'Cybersecurity'), ('AI_ML', 'AI & Machine Learning'), ('FINTECH', 'Fintech'), ('LIFE_SCIENCES', 'Life Sciences'), ('OIL_GAS', 'Oil & Gas'), ('CONSUMER_ELECTRONICS', 'Consumer Electronics')], max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_person_phone', models.CharField(blank=True, max_length=20)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254)),
                ('physical_address', models.TextField(blank=True)),
                ('postal_address', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone_number', models.CharField(blank=True, max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('political_risk', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('PEP', 'Politically Exposed Person')], default='LOW', max_length=20)),
                ('aml_risk', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_from_application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_partner', to='partner_onboarding.partnerapplication')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'db_table': 'partner_partner',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(blank=True, max_length=200)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='partners.partner')),
            ],
            options={
                'verbose_name': 'Partner Bank Account',
                'verbose_name_plural': 'Partner Bank Accounts',
                'db_table': 'partner_partner_bank_account',
                'ordering': ['-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='PartnerContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('BILLING', 'Billing'), ('TECHNICAL', 'Technical'), ('OTHER', 'Other')], default='SECONDARY', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='partners.partner')),
            ],
            options={
                'verbose_name': 'Partner Contact',
                'verbose_name_plural': 'Partner Contacts',
                'db_table': 'partner_partner_contact',
                'ordering': ['-is_primary', 'last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['partner_number'], name='partner_par_partner_d28005_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['email'], name='partner_par_email_761118_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['partner_type', 'status'], name='partner_par_partner_60e061_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['status'], name='partner_par_status_2d95e0_idx'),
        ),
    ]
