# Generated by Django 5.0.14 on 2026-06-21 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_onboarding', '0003_seed_partner_types_and_branches'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnertype',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner_onboarding.branch'),
        ),
        migrations.AddField(
            model_name='partnertype',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner_onboarding.location'),
        ),
    ]
