# Generated by Django 5.0.14 on 2026-06-22 04:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partnertype_branch_partnertype_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerTypeDocumentRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_requirements', to=settings.AUTH_USER_MODEL)),
                ('partner_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='partners.partnertype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_document_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Type Document Requirement',
                'verbose_name_plural': 'Partner Type Document Requirements',
                'db_table': 'partner_partner_type_document_requirement',
                'ordering': ['partner_type', 'sort_order', 'code'],
                'unique_together': {('partner_type', 'code')},
            },
        ),
    ]
