# Generated by Django 5.0.14 on 2026-06-22 12:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_onboarding', '0003_seed_partner_types_and_branches'),
        ('partners', '0003_partnertypedocumentrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_category',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('CORPORATE', 'Corporate')], default='', help_text='Classification: INDIVIDUAL or CORPORATE. Preferred over partner_type.', max_length=20),
        ),
        migrations.CreateModel(
            name='CorporateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('tin_number', models.CharField(blank=True, max_length=50)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, choices=[('TECHNOLOGY', 'Technology'), ('HEALTHCARE', 'Healthcare & Pharmaceuticals'), ('FINANCIAL_SERVICES', 'Financial Services & Banking'), ('CONSUMER_GOODS', 'Consumer Goods & Retail'), ('ENERGY', 'Energy & Utilities'), ('MANUFACTURING', 'Manufacturing & Industrial'), ('TELECOMMUNICATIONS', 'Telecommunications'), ('TRANSPORTATION', 'Transportation & Logistics'), ('REAL_ESTATE', 'Real Estate & Construction'), ('MEDIA', 'Media & Entertainment'), ('AEROSPACE', 'Aerospace & Defense'), ('AUTOMOTIVE', 'Automotive'), ('AGRICULTURE', 'Agriculture & Food Production'), ('HOSPITALITY', 'Hospitality & Tourism'), ('EDUCATION', 'Education & Training'), ('PROFESSIONAL_SERVICES', 'Professional Services & Consulting'), ('INSURANCE', 'Insurance'), ('MINING', 'Mining & Metals'), ('CHEMICALS', 'Chemicals'), ('TEXTILES', 'Textiles & Apparel'), ('ENVIRONMENTAL', 'Environmental Services'), ('BIOTECHNOLOGY', 'Biotechnology'), ('E_COMMERCE', 'E-commerce'), ('RENEWABLE_ENERGY', 'Renewable Energy'), ('CYBERSECURITY', 'Cybersecurity'), ('AI_ML', 'AI & Machine Learning'), ('FINTECH', 'Fintech'), ('LIFE_SCIENCES', 'Life Sciences'), ('OIL_GAS', 'Oil & Gas'), ('CONSUMER_ELECTRONICS', 'Consumer Electronics')], max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_person_phone', models.CharField(blank=True, max_length=20)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_profile', to='partners.partner')),
            ],
            options={
                'verbose_name': 'Corporate Profile',
                'verbose_name_plural': 'Corporate Profiles',
                'db_table': 'partner_corporate_profile',
            },
        ),
        migrations.CreateModel(
            name='IndividualProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identification_type', models.CharField(blank=True, choices=[('NIN', 'National Identification Number'), ('ZAN_ID', 'Zanzibar ID'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('TIN', 'Tax Identification Number'), ('VOTER_ID', 'Voter ID'), ('RESIDENT_PERMIT', 'Resident Permit'), ('MILITARY_ID', 'Military ID')], max_length=30)),
                ('identification_number', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Hon', 'Hon'), ('Eng', 'Eng'), ('Rev', 'Rev')], max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('other_name', models.CharField(blank=True, max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Separated')], max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('nationality', models.CharField(blank=True, choices=[('Tanzanian', 'Tanzanian'), ('Kenyan', 'Kenyan'), ('Ugandan', 'Ugandan'), ('Rwandan', 'Rwandan'), ('Burundian', 'Burundian'), ('Congolese', 'Congolese'), ('South African', 'South African'), ('Nigerian', 'Nigerian'), ('Ghanaian', 'Ghanaian'), ('Ethiopian', 'Ethiopian'), ('Somali', 'Somali'), ('Mozambican', 'Mozambican'), ('Malawian', 'Malawian'), ('Zambian', 'Zambian'), ('Zimbabwean', 'Zimbabwean'), ('Indian', 'Indian'), ('Chinese', 'Chinese'), ('British', 'British'), ('American', 'American'), ('Other', 'Other')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_profile', to='partners.partner')),
            ],
            options={
                'verbose_name': 'Individual Profile',
                'verbose_name_plural': 'Individual Profiles',
                'db_table': 'partner_individual_profile',
            },
        ),
        migrations.CreateModel(
            name='PartnerTypeAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_data_externally', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner_onboarding.branch')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner_onboarding.location')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_assignments', to='partners.partner')),
                ('partner_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='partners.partnertype')),
            ],
            options={
                'verbose_name': 'Partner Type Assignment',
                'verbose_name_plural': 'Partner Type Assignments',
                'db_table': 'partner_type_assignment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['partner', 'status'], name='partner_typ_partner_13718d_idx'), models.Index(fields=['partner_type'], name='partner_typ_partner_ffd833_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='partnertypeassignment',
            constraint=models.UniqueConstraint(fields=('partner', 'partner_type'), name='unique_partner_type_per_partner'),
        ),
    ]
