# Generated by Django 5.0.14 on 2026-06-22 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_migrate_partner_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerAssignmentBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_type', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(blank=True, max_length=200)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assignment Bank Account',
                'verbose_name_plural': 'Assignment Bank Accounts',
                'db_table': 'partner_assignment_bank_account',
                'ordering': ['-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='PartnerAssignmentContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_type', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assignment Contact',
                'verbose_name_plural': 'Assignment Contacts',
                'db_table': 'partner_assignment_contact',
                'ordering': ['-is_primary', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, upload_to='partner_documents/%Y/%m/')),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('UPLOADED', 'Uploaded'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='NOT_SUBMITTED', max_length=30)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner Document',
                'verbose_name_plural': 'Partner Documents',
                'db_table': 'partner_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerDynamicFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner Dynamic Field Value',
                'verbose_name_plural': 'Partner Dynamic Field Values',
                'db_table': 'partner_dynamic_field_value',
            },
        ),
        migrations.CreateModel(
            name='PartnerKYCProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kyc_status', models.CharField(choices=[('NOT_SET', 'Not Set'), ('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='NOT_SET', max_length=30)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=30)),
                ('last_review_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner KYC Profile',
                'verbose_name_plural': 'Partner KYC Profiles',
                'db_table': 'partner_kyc_profile',
            },
        ),
        migrations.CreateModel(
            name='PartnerTypeBankRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_type', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('multiple_allowed', models.BooleanField(default=False)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner Type Bank Requirement',
                'verbose_name_plural': 'Partner Type Bank Requirements',
                'db_table': 'partner_type_bank_requirement',
                'ordering': ['partner_type', 'display_order', 'bank_type'],
            },
        ),
        migrations.CreateModel(
            name='PartnerTypeContactRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_type', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('multiple_allowed', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner Type Contact Requirement',
                'verbose_name_plural': 'Partner Type Contact Requirements',
                'db_table': 'partner_type_contact_requirement',
                'ordering': ['partner_type', 'display_order', 'contact_type'],
            },
        ),
        migrations.CreateModel(
            name='PartnerTypeFieldConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=200)),
                ('field_code', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean'), ('DROPDOWN', 'Dropdown'), ('MULTI_SELECT', 'Multi Select'), ('FILE', 'File'), ('CURRENCY', 'Currency'), ('PERCENTAGE', 'Percentage')], max_length=20)),
                ('default_value', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('visibility_rules', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner Type Field Configuration',
                'verbose_name_plural': 'Partner Type Field Configurations',
                'db_table': 'partner_type_field_config',
                'ordering': ['partner_type', 'display_order', 'field_name'],
            },
        ),
        migrations.AddField(
            model_name='partnertypedocumentrequirement',
            name='allow_multiple_uploads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='partnertypedocumentrequirement',
            index=models.Index(fields=['partner_type', 'is_active'], name='partner_par_partner_991821_idx'),
        ),
        migrations.AddField(
            model_name='partnerassignmentbankaccount',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_bank_accounts', to='partners.partnertypeassignment'),
        ),
        migrations.AddField(
            model_name='partnerassignmentcontact',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_contacts', to='partners.partnertypeassignment'),
        ),
        migrations.AddField(
            model_name='partnerdocument',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='partners.partnertypeassignment'),
        ),
        migrations.AddField(
            model_name='partnerdocument',
            name='document_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_documents', to='partners.partnertypedocumentrequirement'),
        ),
        migrations.AddField(
            model_name='partnerdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_partner_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerdynamicfieldvalue',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='partners.partnertypeassignment'),
        ),
        migrations.AddField(
            model_name='partnerkycprofile',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profiles', to='partners.partnertypeassignment'),
        ),
        migrations.AddField(
            model_name='partnerkycprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnertypebankrequirement',
            name='partner_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_requirements', to='partners.partnertype'),
        ),
        migrations.AddField(
            model_name='partnerassignmentbankaccount',
            name='bank_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_bank_accounts', to='partners.partnertypebankrequirement'),
        ),
        migrations.AddField(
            model_name='partnertypecontactrequirement',
            name='partner_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requirements', to='partners.partnertype'),
        ),
        migrations.AddField(
            model_name='partnerassignmentcontact',
            name='contact_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_contacts', to='partners.partnertypecontactrequirement'),
        ),
        migrations.AddField(
            model_name='partnertypefieldconfiguration',
            name='partner_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_configurations', to='partners.partnertype'),
        ),
        migrations.AddField(
            model_name='partnerdynamicfieldvalue',
            name='field_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='partners.partnertypefieldconfiguration'),
        ),
        migrations.AlterUniqueTogether(
            name='partnerkycprofile',
            unique_together={('assignment',)},
        ),
        migrations.AlterUniqueTogether(
            name='partnertypebankrequirement',
            unique_together={('partner_type', 'bank_type')},
        ),
        migrations.AlterUniqueTogether(
            name='partnertypecontactrequirement',
            unique_together={('partner_type', 'contact_type')},
        ),
        migrations.AlterUniqueTogether(
            name='partnertypefieldconfiguration',
            unique_together={('partner_type', 'field_code')},
        ),
        migrations.AlterUniqueTogether(
            name='partnerdynamicfieldvalue',
            unique_together={('assignment', 'field_config')},
        ),
    ]
