# Generated by Django 5.0.14 on 2026-06-22 12:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_onboarding', '0003_seed_partner_types_and_branches'),
        ('partners', '0006_add_partner_setup_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(blank=True, upload_to='partner_document_versions/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='UPLOADED', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(blank=True, max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
                'db_table': 'partner_document_version',
                'ordering': ['document', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='KYCReviewHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_type', models.CharField(choices=[('INITIAL', 'Initial Verification'), ('PERIODIC', 'Periodic Review'), ('ENHANCED_DUE_DILIGENCE', 'Enhanced Due Diligence'), ('HIGH_RISK_ESCALATION', 'High Risk Escalation'), ('REVIEW', 'Manual Review')], default='REVIEW', max_length=30)),
                ('previous_kyc_status', models.CharField(blank=True, max_length=30)),
                ('new_kyc_status', models.CharField(blank=True, max_length=30)),
                ('previous_risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('new_risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('previous_risk_level', models.CharField(blank=True, max_length=30)),
                ('new_risk_level', models.CharField(blank=True, max_length=30)),
                ('decision_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'KYC Review History',
                'verbose_name_plural': 'KYC Review Histories',
                'db_table': 'partner_kyc_review_history',
                'ordering': ['-decision_date'],
            },
        ),
        migrations.CreateModel(
            name='PartnerTypeAssignmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Partner Type Assignment History',
                'verbose_name_plural': 'Partner Type Assignment Histories',
                'db_table': 'partner_type_assignment_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='partner',
            name='partner_par_partner_d28005_idx',
        ),
        migrations.RemoveIndex(
            model_name='partner',
            name='partner_par_partner_60e061_idx',
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['partner_type'], name='partner_par_partner_592c86_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['mobile_number'], name='partner_par_mobile__cf1fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['identification_number'], name='partner_par_identif_b92fc2_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['tin_number'], name='partner_par_tin_num_c2c1cd_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['-created_at'], name='partner_par_created_d9bc69_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerassignmentbankaccount',
            index=models.Index(fields=['assignment'], name='partner_ass_assignm_6df916_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerassignmentcontact',
            index=models.Index(fields=['assignment'], name='partner_ass_assignm_241e87_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerdocument',
            index=models.Index(fields=['assignment'], name='partner_doc_assignm_07d941_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerdocument',
            index=models.Index(fields=['status'], name='partner_doc_status_446f2e_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerdocument',
            index=models.Index(fields=['expiry_date'], name='partner_doc_expiry__b21523_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerdocument',
            index=models.Index(fields=['assignment', 'status'], name='partner_doc_assignm_23186f_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerdynamicfieldvalue',
            index=models.Index(fields=['assignment'], name='partner_dyn_assignm_3d5907_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerdynamicfieldvalue',
            index=models.Index(fields=['field_config'], name='partner_dyn_field_c_6ad9ab_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerkycprofile',
            index=models.Index(fields=['assignment'], name='partner_kyc_assignm_54fc7d_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerkycprofile',
            index=models.Index(fields=['kyc_status'], name='partner_kyc_kyc_sta_c7380a_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerkycprofile',
            index=models.Index(fields=['kyc_status', 'risk_level'], name='partner_kyc_kyc_sta_57ad9f_idx'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='partners.partnerdocument'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_document_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycreviewhistory',
            name='kyc_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='partners.partnerkycprofile'),
        ),
        migrations.AddField(
            model_name='kycreviewhistory',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnertypeassignmenthistory',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='partners.partnertypeassignment'),
        ),
        migrations.AddField(
            model_name='partnertypeassignmenthistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='kycreviewhistory',
            index=models.Index(fields=['kyc_profile', '-decision_date'], name='partner_kyc_kyc_pro_868766_idx'),
        ),
        migrations.AddIndex(
            model_name='kycreviewhistory',
            index=models.Index(fields=['review_type'], name='partner_kyc_review__6687b2_idx'),
        ),
        migrations.AddIndex(
            model_name='partnertypeassignmenthistory',
            index=models.Index(fields=['assignment', '-changed_at'], name='partner_typ_assignm_5675b1_idx'),
        ),
    ]
