# Generated by Django 5.0.14 on 2026-06-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_seed_zanzibar_life_insurance_config'),
    ]

    operations = [
    ]
