# Generated by Django 5.0.14 on 2026-06-25 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_merge_20260624_0943'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partnertypedocumentrequirement',
            name='allow_multiple_uploads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='partnertypedocumentrequirement',
            index=models.Index(fields=['partner_type', 'is_active'], name='partner_par_partner_991821_idx'),
        ),
    ]
