# Generated by Django 5.0.14 on 2026-08-14 17:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


PARTNER_VIEW_SQL = """
CREATE VIEW onboarding_unified_record AS
SELECT
    a.id as id,
    'APPLICATION' as record_type,
    a.id as application_id,
    p.id as partner_id,
    a.application_number as reference_number,
    COALESCE(NULLIF(TRIM(a.company_name), ''), NULLIF(TRIM(a.first_name || ' ' || COALESCE(a.surname, '')), ''), a.email) as display_name,
    a.partner_type as partner_type,
    a.email as email,
    a.mobile_number as mobile_number,
    a.status as application_status,
    k.kyc_status as kyc_status,
    a.created_at as created_at
FROM onboarding_partner_application a
LEFT JOIN partner_partner p ON p.created_from_application_id = a.id
LEFT JOIN (
    SELECT partner_id, kyc_status
    FROM (
        SELECT ta.partner_id, kp.kyc_status,
               ROW_NUMBER() OVER(PARTITION BY ta.partner_id ORDER BY kp.created_at DESC) as rn
        FROM partner_kyc_profile kp
        JOIN partner_type_assignment ta ON kp.assignment_id = ta.id
    ) sub
    WHERE rn = 1
) k ON k.partner_id = p.id
WHERE a.status != 'CONVERTED'
UNION ALL
SELECT
    p.id as id,
    'PARTNER' as record_type,
    p.created_from_application_id as application_id,
    p.id as partner_id,
    p.partner_number as reference_number,
    CASE
        WHEN COALESCE(NULLIF(TRIM(p.partner_category), ''), p.partner_type) = 'INDIVIDUAL'
        THEN TRIM(COALESCE(p.title || ' ', '') || COALESCE(p.first_name || ' ', '') || COALESCE(p.other_name || ' ', '') || COALESCE(p.surname, ''))
        ELSE p.company_name
    END as display_name,
    p.partner_type as partner_type,
    p.email as email,
    p.mobile_number as mobile_number,
    'CONVERTED' as application_status,
    k.kyc_status as kyc_status,
    p.created_at as created_at
FROM partner_partner p
LEFT JOIN (
    SELECT partner_id, kyc_status
    FROM (
        SELECT ta.partner_id, kp.kyc_status,
               ROW_NUMBER() OVER(PARTITION BY ta.partner_id ORDER BY kp.created_at DESC) as rn
        FROM partner_kyc_profile kp
        JOIN partner_type_assignment ta ON kp.assignment_id = ta.id
    ) sub
    WHERE rn = 1
) k ON k.partner_id = p.id;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_partnertypedocumentrequirement_allow_multiple_uploads_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP VIEW IF EXISTS onboarding_unified_record;",
            reverse_sql=PARTNER_VIEW_SQL,
        ),
        migrations.AddField(
            model_name='partner',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='partner',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partner',
            name='party_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CORPORATE', 'Corporate')], db_index=True, default='CORPORATE', max_length=20),
        ),
        migrations.AddField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='partner',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partner',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_partners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_category',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('CORPORATE', 'Corporate')], default='', help_text='Legacy classification: INDIVIDUAL or CORPORATE.', max_length=20),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('INTERMEDIARY', 'Intermediary'), ('SERVICE_PROVIDER', 'Service provider'), ('MEDICAL_PRACTITIONER', 'Medical practitioner'), ('INSURER', 'Insurer'), ('BANK', 'Bank'), ('CORPORATE', 'Corporate'), ('OTHER', 'Other'), ('INDIVIDUAL', 'Individual'), ('AGENT', 'Agent'), ('BROKER', 'Broker')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserPartnerLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partner_links', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_links', to='partners.partner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Partner Link',
                'verbose_name_plural': 'User Partner Links',
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['user', 'link_status'], name='partners_us_user_id_b71d84_idx'), models.Index(fields=['partner', 'link_status'], name='partners_us_partner_7de273_idx'), models.Index(fields=['valid_from', 'valid_to'], name='partners_us_valid_f_8c3d8e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='userpartnerlink',
            constraint=models.UniqueConstraint(condition=models.Q(('link_status', 'ACTIVE')), fields=('user', 'partner'), name='partners_active_user_partner_unique'),
        ),
        migrations.AddConstraint(
            model_name='userpartnerlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('link_status', 'ACTIVE')), fields=('user',), name='partners_active_primary_user_unique'),
        ),
        migrations.RunSQL(
            sql=PARTNER_VIEW_SQL,
            reverse_sql="DROP VIEW IF EXISTS onboarding_unified_record;",
        ),
    ]
