# Generated by Django 5.0.14 on 2026-08-23 18:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(db_index=True, max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('layout_template_path', models.CharField(max_length=255)),
                ('variables_schema', models.JSONField(blank=True, default=dict)),
                ('branding_config_reference', models.CharField(blank=True, default='COMPANY_BRANDING', max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_document_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_type', 'code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='DocumentInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(db_index=True, max_length=120)),
                ('source_app_label', models.CharField(db_index=True, max_length=100)),
                ('source_model', models.CharField(db_index=True, max_length=120)),
                ('source_object_id', models.CharField(db_index=True, max_length=120)),
                ('template_version', models.PositiveIntegerField()),
                ('file_reference', models.CharField(max_length=500)),
                ('preview_reference', models.CharField(blank=True, default='', max_length=500)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('page_count', models.PositiveIntegerField(default=1)),
                ('checksum', models.CharField(max_length=64)),
                ('mime_type', models.CharField(default='application/pdf', max_length=120)),
                ('status', models.CharField(db_index=True, default='GENERATED', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_document_instances', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='documents.documenttemplate')),
            ],
            options={
                'ordering': ['-generated_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['document_type', 'is_active', 'version'], name='documents_d_documen_78756f_idx'),
        ),
        migrations.AddConstraint(
            model_name='documenttemplate',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='documents_template_code_version_uq'),
        ),
        migrations.AddIndex(
            model_name='documentinstance',
            index=models.Index(fields=['source_app_label', 'source_model', 'source_object_id'], name='documents_d_source__990e30_idx'),
        ),
        migrations.AddIndex(
            model_name='documentinstance',
            index=models.Index(fields=['document_type', 'generated_at'], name='documents_d_documen_eb99bf_idx'),
        ),
    ]
