# Generated by Django 5.0.14 on 2026-08-23 19:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_seed_prompt4_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, default='COMPANY_BRANDING', max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('logo_file', models.FileField(blank=True, null=True, upload_to='documents/branding/')),
                ('company_name', models.CharField(default='Zanzibar Insurance Corporation', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=80)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('registration_number', models.CharField(blank=True, default='', max_length=120)),
                ('footer_legal_text', models.TextField(blank=True, default='This document is system generated.')),
                ('accent_colors', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_branding_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code', '-version'],
                'indexes': [models.Index(fields=['code', 'is_active', 'version'], name='documents_branding_active_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='brandingconfiguration',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='documents_branding_code_version_uq'),
        ),
    ]
