import { Download, Printer } from "lucide-react"
import { ErrorCoach } from "../../components/commitments/ErrorCoach"
import { useGeneratedDocuments } from "../../lib/proposalsHooks"
import type { ProposalDetail } from "../../lib/proposals"

/**
 * Generated Documents tab: the durable register of every printout produced
 * for this proposal — template version, source quotation version, who
 * generated it and when.
 */
export function OLGeneratedDocuments({ detail }: { detail: ProposalDetail }) {
  const documentsQuery = useGeneratedDocuments(detail.id)
  const rows = documentsQuery.data ?? []

  return (
    <div className="space-y-4" data-testid="tab-generated">
      <section className="surface-card p-4">
        <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
          <h2 className="flex items-center gap-2 font-bold">
            <Printer size={16} aria-hidden="true" />
            Generated documents
          </h2>
          <span className="text-xs font-bold uppercase tracking-[0.08em] text-[var(--muted-foreground)]" data-testid="generated-counts">
            {rows.length} {rows.length === 1 ? "printout" : "printouts"}
          </span>
        </div>

        {documentsQuery.isLoading ? (
          <div className="h-20 animate-pulse rounded-[10px] bg-[var(--muted)]" aria-busy="true" />
        ) : rows.length === 0 ? (
          <p className="text-sm text-[var(--muted-foreground)]">
            No printouts yet. Use “Print” in the action bar to generate the proposal summary PDF.
          </p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm" data-testid="generated-documents-table">
              <thead>
                <tr className="border-b text-xs font-bold uppercase tracking-wide text-[var(--muted-foreground)]">
                  <th className="py-2 pr-3">Document</th>
                  <th className="py-2 pr-3">Template</th>
                  <th className="py-2 pr-3">Source ver.</th>
                  <th className="py-2 pr-3">Generated by</th>
                  <th className="py-2 pr-3">Generated at</th>
                  <th className="py-2">File</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((row) => (
                  <tr key={row.id || row.documentType} className="border-b border-[var(--border)] last:border-0" data-testid={`generated-row-${row.id}`}>
                    <td className="py-2 pr-3 font-semibold">{row.documentType}</td>
                    <td className="py-2 pr-3 text-xs">
                      {row.templateCode ? (
                        <>
                          {row.templateCode} <span className="font-bold">v{row.templateVersion ?? "?"}</span>
                        </>
                      ) : (
                        "—"
                      )}
                    </td>
                    <td className="py-2 pr-3 text-xs">{row.sourceVersion != null ? `v${row.sourceVersion}` : "—"}</td>
                    <td className="py-2 pr-3 text-xs">{row.generatedByName || "—"}</td>
                    <td className="py-2 pr-3 text-xs">{row.generatedAt ? row.generatedAt.slice(0, 16).replace("T", " ") : "—"}</td>
                    <td className="py-2">
                      {row.pdfUrl ? (
                        <a href={row.pdfUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs font-bold underline-offset-2 hover:underline">
                          <Download size={12} aria-hidden="true" />
                          PDF
                        </a>
                      ) : (
                        "—"
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
        {documentsQuery.isError && (
          <ErrorCoach error={documentsQuery.error} title="The generated documents could not be loaded" compact onRetry={() => void documentsQuery.refetch()} />
        )}
      </section>
    </div>
  )
}

export default OLGeneratedDocuments
