import { useCallback, useEffect, useMemo, useState, type ChangeEvent } from "react"
import { ClipboardCheck, HeartPulse, Plus, ShieldCheck } from "lucide-react"
import { request, buildTableQuery, type TableQuery } from "../../lib/apiClient"
import { useAccess } from "../../lib/access"
import { DataTable, normalizeTableResponse } from "../../components/ui/DataTable"
import { FilterBar, type FilterValues } from "../../components/ui/FilterBar"
import { ConfirmModal, FormModal, InfoBanner } from "../../components/ui/Overlays"
import { DateInput, DecimalInput, FormGrid, SelectInput, TextInput, TextareaInput, Toggle } from "../../components/ui"
import { StatusBadge, type StatusTone } from "../../components/ui/StatusBadge"
import { useToast } from "../../components/ui/Toast"
import type { FilterDefinition, FilterOption, RowAction, TableColumn, TableMetadata } from "../../components/ui/types"
import { optionLabel, useRemoteChoices } from "./OLParameterOptions"

const API_PREFIX = "/api/v1/ol-parameters"
type Section = "medical" | "claims"
type ScreenKey = "medical-codes" | "medical-limits" | "personal-habits" | "medical-history" | "medical-facilities" | "medical-practitioners" | "claim-types" | "claim-reasons" | "claim-statuses" | "discharge-types" | "correspondent-types"
type Primitive = string | number | boolean | null | string[] | Record<string, unknown>
type Editor = Record<string, Primitive | undefined>
type AnyRecord = Editor & { id: string; code: string; name: string; is_active: boolean; effective_from?: string | null; effective_to?: string | null; allowed_transitions?: string[]; partner?: string | null; partner_name?: string | null; partner_number?: string | null }
type ScreenConfig = { key: ScreenKey; title: string; description: string; endpoint: string; section: Section; choiceFields: string[]; filters: FilterDefinition[]; columns: TableColumn<AnyRecord>[] }

const today = () => new Date().toISOString().slice(0, 10)
const text = (value: unknown) => value === null || value === undefined ? "" : String(value)
const numberValue = (value: unknown, fallback = 0) => value === "" || value === null || value === undefined ? fallback : Number(value)
const labelize = (value: unknown) => text(value).replace(/_/g, " ").replace(/(^|\s)\S/g, (character) => character.toUpperCase()) || "—"
const activeStatus = (row: AnyRecord) => !row.is_active ? "Inactive" : row.effective_to && row.effective_to < today() ? "Expired" : row.effective_from && row.effective_from > today() ? "Scheduled" : "Active"
const tone = (value: string): StatusTone => ["ACTIVE", "APPROVED", "SUCCESS", "POSITIVE"].includes(value.toUpperCase()) ? "success" : ["PENDING", "WARNING", "SCHEDULED", "INFO"].includes(value.toUpperCase()) ? "warning" : ["REJECTED", "SUSPENDED", "EXPIRED", "DANGER"].includes(value.toUpperCase()) ? "danger" : "neutral"
const dateCell = (value: unknown) => value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(new Date(`${String(value)}T00:00:00`)) : "Open ended"
const jsonText = (value: unknown, fallback: object | unknown[] = {}) => JSON.stringify(value ?? fallback, null, 2)

function commonColumns(extra: TableColumn<AnyRecord>[]): TableColumn<AnyRecord>[] { return [
  { key: "code", label: "Code", field: "code", sortable: true },
  { key: "name", label: "Name", field: "name", sortable: true },
  ...extra,
  { key: "effective_from", label: "Effective from", field: "effective_from", sortable: true, render: (value) => dateCell(value) },
  { key: "effective_to", label: "Effective to", field: "effective_to", render: (value) => dateCell(value) },
  { key: "status", label: "Status", render: (_value, row) => <StatusBadge value={activeStatus(row)} tone={tone(activeStatus(row))} /> },
] }

const badge = (value: unknown) => <StatusBadge value={labelize(value)} tone={tone(text(value))} />
const range = (from: unknown, to: unknown, suffix = "") => `${text(from) || "—"}–${text(to) || "—"}${suffix}`

const configs: Record<ScreenKey, ScreenConfig> = {
  "medical-codes": { key: "medical-codes", section: "medical", title: "OL Medical Codes", description: "Reusable medical evidence, examination, and underwriting code catalog.", endpoint: `${API_PREFIX}/medical-codes/`, choiceFields: [], filters: [{ key: "medical_category", label: "Category", type: "text" }, { key: "is_active", label: "Status", type: "select" }], columns: commonColumns([{ key: "medical_category", label: "Category", field: "medical_category", sortable: true }]) },
  "medical-limits": { key: "medical-limits", section: "medical", title: "OL Medical Limit", description: "Effective medical evidence limits by code, age, sum assured, product, plan, and frequency.", endpoint: `${API_PREFIX}/medical-limits/`, choiceFields: ["medical_code", "product", "plan", "limit_type", "required_frequency"], filters: [{ key: "medical_code", label: "Medical code", type: "select" }, { key: "product", label: "Product", type: "select" }, { key: "plan", label: "Plan", type: "select" }, { key: "limit_type", label: "Limit type", type: "select" }, { key: "required_frequency", label: "Frequency", type: "select" }, { key: "mandatory_flag", label: "Mandatory", type: "select" }, { key: "is_active", label: "Status", type: "select" }], columns: commonColumns([{ key: "medical_code", label: "Medical code", field: "medical_code", sortable: true }, { key: "age", label: "Age band", render: (_v, row) => range(row.age_from, row.age_to) }, { key: "sum_assured", label: "Sum assured band", render: (_v, row) => range(row.sum_assured_from, row.sum_assured_to) }, { key: "limit_type", label: "Limit type", field: "limit_type", render: badge }, { key: "limit_amount", label: "Limit amount", field: "limit_amount", align: "right" }, { key: "mandatory_flag", label: "Mandatory", field: "mandatory_flag", render: (value) => <StatusBadge value={value ? "Yes" : "No"} tone={value ? "warning" : "neutral"} /> }]) },
  "personal-habits": { key: "personal-habits", section: "medical", title: "OL Personal Habit", description: "Underwriting habit questions and evidence requirements.", endpoint: `${API_PREFIX}/personal-habits/`, choiceFields: ["habit_category", "underwriting_impact"], filters: [{ key: "habit_category", label: "Habit category", type: "select" }, { key: "underwriting_impact", label: "Underwriting impact", type: "select" }, { key: "is_active", label: "Status", type: "select" }], columns: commonColumns([{ key: "habit_category", label: "Category", field: "habit_category", render: badge }, { key: "question_text", label: "Question", field: "question_text" }, { key: "underwriting_impact", label: "Impact", field: "underwriting_impact", render: badge }, { key: "requires_evidence", label: "Evidence", field: "requires_evidence", render: (value) => value ? "Required" : "Not required" }]) },
  "medical-history": { key: "medical-history", section: "medical", title: "OL Medical History", description: "Medical condition history with severity, waiting periods, exclusions, and loadings.", endpoint: `${API_PREFIX}/medical-history/`, choiceFields: [], filters: [{ key: "condition_category", label: "Condition category", type: "text" }, { key: "severity", label: "Severity", type: "text" }, { key: "exclusion_flag", label: "Exclusion", type: "select" }, { key: "loading_flag", label: "Loading", type: "select" }, { key: "is_active", label: "Status", type: "select" }], columns: commonColumns([{ key: "condition_category", label: "Category", field: "condition_category", sortable: true }, { key: "severity", label: "Severity", field: "severity", render: badge }, { key: "waiting_period_days", label: "Waiting days", field: "waiting_period_days", align: "right" }, { key: "rules", label: "Rules", render: (_v, row) => `${row.exclusion_flag ? "Exclusion" : "No exclusion"} · ${row.loading_flag ? "Loading" : "No loading"}` }]) },
  "medical-facilities": { key: "medical-facilities", section: "medical", title: "OL Medical Facility", description: "Approved medical facility catalog with optional partner master linkage.", endpoint: `${API_PREFIX}/medical-facilities/`, choiceFields: ["partner", "approval_status"], filters: [{ key: "facility_type", label: "Facility type", type: "text" }, { key: "approval_status", label: "Approval", type: "select" }, { key: "city", label: "City", type: "text" }, { key: "is_active", label: "Status", type: "select" }], columns: commonColumns([{ key: "facility_code", label: "Facility code", field: "facility_code", sortable: true }, { key: "facility_type", label: "Type", field: "facility_type", render: badge }, { key: "registration_number", label: "Registration", field: "registration_number" }, { key: "location", label: "Location", render: (_v, row) => `${text(row.city) || "—"}, ${text(row.country) || "—"}` }, { key: "approval_status", label: "Approval", field: "approval_status", render: badge }, { key: "partner", label: "Partner linkage", render: (_v, row) => text(row.partner_name || row.partner_number || row.partner) || "Not linked" }]) },
  "medical-practitioners": { key: "medical-practitioners", section: "medical", title: "OL Medical Practitioners", description: "Practitioner catalog with specialty, license, facility, approval, and partner linkage.", endpoint: `${API_PREFIX}/medical-practitioners/`, choiceFields: ["medical_facility", "partner", "approval_status"], filters: [{ key: "specialty", label: "Specialty", type: "text" }, { key: "medical_facility", label: "Facility", type: "select" }, { key: "approval_status", label: "Approval", type: "select" }, { key: "is_active", label: "Status", type: "select" }], columns: commonColumns([{ key: "practitioner_code", label: "Practitioner code", field: "practitioner_code", sortable: true }, { key: "practitioner", label: "Practitioner", render: (_v, row) => `${text(row.first_name)} ${text(row.last_name)}` }, { key: "specialty", label: "Specialty", field: "specialty", render: badge }, { key: "license_number", label: "License", field: "license_number" }, { key: "medical_facility", label: "Facility", field: "medical_facility" }, { key: "approval_status", label: "Approval", field: "approval_status", render: badge }, { key: "partner", label: "Partner linkage", render: (_v, row) => text(row.partner_name || row.partner_number || row.partner) || "Not linked" }]) },
  "claim-types": { key: "claim-types", section: "claims", title: "OL Claim Types", description: "Claim categories, calculation rules, duplicate protection, documents, and approvals.", endpoint: `${API_PREFIX}/claim-types/`, choiceFields: ["claim_category", "calculation_basis", "duplicate_check_rule"], filters: [{ key: "claim_category", label: "Category", type: "select" }, { key: "calculation_basis", label: "Calculation basis", type: "select" }, { key: "duplicate_check_rule", label: "Duplicate rule", type: "select" }, { key: "require_approval", label: "Approval", type: "select" }, { key: "is_active", label: "Status", type: "select" }], columns: commonColumns([{ key: "claim_category", label: "Category", field: "claim_category", render: badge }, { key: "calculation_basis", label: "Basis", field: "calculation_basis" }, { key: "waiting_period_days", label: "Waiting days", field: "waiting_period_days", align: "right" }, { key: "require_documents", label: "Documents", render: (value) => Array.isArray(value) ? `${value.length} configured` : "—" }, { key: "require_approval", label: "Approval", field: "require_approval", render: (value) => value ? "Required" : "Not required" }]) },
  "claim-reasons": { key: "claim-reasons", section: "claims", title: "OL Claim Reasons", description: "Claim reason catalog optionally linked to an active claim type.", endpoint: `${API_PREFIX}/claim-reasons/`, choiceFields: ["claim_type", "reason_category"], filters: [{ key: "claim_type", label: "Claim type", type: "select" }, { key: "reason_category", label: "Category", type: "select" }, { key: "is_active", label: "Status", type: "select" }], columns: commonColumns([{ key: "claim_type", label: "Claim type", field: "claim_type" }, { key: "reason_category", label: "Category", field: "reason_category", render: badge }]) },
  "claim-statuses": { key: "claim-statuses", section: "claims", title: "OL Claim Status", description: "Ordered claim status catalog with badge configuration, terminal flags, and transition graph.", endpoint: `${API_PREFIX}/claim-statuses/`, choiceFields: ["badge_type"], filters: [{ key: "badge_type", label: "Badge", type: "select" }, { key: "is_terminal", label: "Terminal", type: "select" }, { key: "is_payable", label: "Payable", type: "select" }, { key: "is_active", label: "Status", type: "select" }], columns: commonColumns([{ key: "display_order", label: "Order", field: "display_order", sortable: true, align: "right" }, { key: "badge_type", label: "Badge", field: "badge_type", render: badge }, { key: "is_terminal", label: "Terminal", field: "is_terminal", render: (value) => value ? <StatusBadge value="Terminal" tone="danger" /> : <StatusBadge value="Non-terminal" tone="neutral" /> }, { key: "is_payable", label: "Payable", field: "is_payable", render: (value) => value ? "Yes" : "No" }, { key: "allowed_transitions", label: "Allowed transitions", field: "allowed_transitions", render: (value) => Array.isArray(value) ? value.join(", ") || "None" : "None" }]) },
  "discharge-types": { key: "discharge-types", section: "claims", title: "OL Discharge Types", description: "Claim settlement discharge/release types with templates and JSON variables.", endpoint: `${API_PREFIX}/discharge-types/`, choiceFields: ["discharge_category"], filters: [{ key: "discharge_category", label: "Category", type: "select" }, { key: "template_code", label: "Template code", type: "text" }, { key: "is_active", label: "Status", type: "select" }], columns: commonColumns([{ key: "discharge_category", label: "Category", field: "discharge_category", render: badge }, { key: "template_code", label: "Template", field: "template_code" }, { key: "variables", label: "Variables", render: (value) => value && typeof value === "object" ? `${Object.keys(value as Record<string, unknown>).length} configured` : "0 configured" }]) },
  "correspondent-types": { key: "correspondent-types", section: "claims", title: "OL Correspondent Types", description: "Claim correspondence purpose and channel catalog.", endpoint: `${API_PREFIX}/correspondent-types/`, choiceFields: ["correspondence_category", "communication_channel"], filters: [{ key: "correspondence_category", label: "Category", type: "select" }, { key: "communication_channel", label: "Channel", type: "select" }, { key: "is_active", label: "Status", type: "select" }], columns: commonColumns([{ key: "correspondence_category", label: "Category", field: "correspondence_category", render: badge }, { key: "communication_channel", label: "Channel", field: "communication_channel", render: badge }, { key: "purpose", label: "Purpose", field: "purpose" }]) },
}

const medicalKeys: ScreenKey[] = ["medical-codes", "medical-limits", "personal-habits", "medical-history", "medical-facilities", "medical-practitioners"]
const claimKeys: ScreenKey[] = ["claim-types", "claim-reasons", "claim-statuses", "discharge-types", "correspondent-types"]
const statusOptions = [{ label: "Active", value: "true" }, { label: "Inactive", value: "false" }]

function defaults(screen: ScreenKey): Editor {
  const base: Editor = { code: "", name: "", description: "", effective_from: today(), effective_to: null, is_active: true }
  if (screen === "medical-codes") return { ...base, medical_category: "" }
  if (screen === "medical-limits") return { ...base, medical_code: "", product: null, plan: null, age_from: 0, age_to: 150, sum_assured_from: null, sum_assured_to: null, limit_type: "", limit_amount: "", required_frequency: "", mandatory_flag: true }
  if (screen === "personal-habits") return { ...base, habit_category: "", question_text: "", underwriting_impact: "", requires_evidence: false }
  if (screen === "medical-history") return { ...base, condition_category: "", severity: "", waiting_period_days: 0, exclusion_flag: false, loading_flag: false, underwriting_note: "" }
  if (screen === "medical-facilities") return { ...base, partner: null, facility_code: "", facility_type: "", registration_number: "", address: "", city: "", country: "TZ", contact_email: "", contact_phone: "", approval_status: "" }
  if (screen === "medical-practitioners") return { ...base, partner: null, practitioner_code: "", first_name: "", last_name: "", specialty: "", license_number: "", medical_facility: null, email: "", phone: "", approval_status: "" }
  if (screen === "claim-types") return { ...base, claim_category: "", calculation_basis: "", duplicate_check_rule: "", waiting_period_days: null, payable_to_rules: {}, allow_waiver_of_premium: false, require_documents: [], require_approval: true }
  if (screen === "claim-reasons") return { ...base, claim_type: null, reason_category: "" }
  if (screen === "claim-statuses") return { ...base, display_order: 0, badge_type: "", is_terminal: false, is_payable: false, allowed_transitions: [] }
  if (screen === "discharge-types") return { ...base, discharge_category: "", template_code: "", variables: {} }
  return { ...base, correspondence_category: "", communication_channel: "", purpose: "" }
}

function validate(screen: ScreenKey, draft: Editor): Record<string, string> {
  const errors: Record<string, string> = {}
  if (!text(draft.code).trim()) errors.code = "Code is required."
  if (!text(draft.name).trim()) errors.name = "Name is required."
  if (text(draft.effective_from) && text(draft.effective_to) && text(draft.effective_to) < text(draft.effective_from)) errors.effective_to = "Effective-to cannot be before effective-from."
  if (screen === "medical-codes" && !text(draft.medical_category).trim()) errors.medical_category = "Medical category is required."
  if (screen === "medical-limits") {
    if (!text(draft.medical_code).trim()) errors.medical_code = "Medical code is required."
    if (!text(draft.limit_type).trim()) errors.limit_type = "Limit type is required."
    if (!text(draft.required_frequency).trim()) errors.required_frequency = "Required frequency is required."
    if (numberValue(draft.age_from) < 0 || numberValue(draft.age_to) > 150 || numberValue(draft.age_to) < numberValue(draft.age_from)) errors.age_to = "Age range must be ordered between 0 and 150."
    if (draft.sum_assured_from !== null && draft.sum_assured_from !== "" && numberValue(draft.sum_assured_from) < 0) errors.sum_assured_from = "Minimum sum assured cannot be negative."
    if (draft.sum_assured_to !== null && draft.sum_assured_to !== "" && numberValue(draft.sum_assured_to) < numberValue(draft.sum_assured_from)) errors.sum_assured_to = "Maximum sum assured cannot be below minimum."
    if (draft.limit_amount === "" || numberValue(draft.limit_amount) <= 0) errors.limit_amount = "Limit amount must be positive."
  }
  if (screen === "personal-habits") { if (!text(draft.habit_category)) errors.habit_category = "Habit category is required."; if (!text(draft.question_text).trim()) errors.question_text = "Question text is required."; if (!text(draft.underwriting_impact)) errors.underwriting_impact = "Underwriting impact is required." }
  if (screen === "medical-history") { if (!text(draft.condition_category).trim()) errors.condition_category = "Condition category is required."; if (!text(draft.severity).trim()) errors.severity = "Severity is required."; if (numberValue(draft.waiting_period_days) < 0) errors.waiting_period_days = "Waiting period cannot be negative." }
  if (screen === "medical-facilities") { if (!text(draft.facility_code).trim()) errors.facility_code = "Facility code is required."; if (!text(draft.facility_type).trim()) errors.facility_type = "Facility type is required."; if (!text(draft.approval_status)) errors.approval_status = "Approval status is required." }
  if (screen === "medical-practitioners") { for (const field of ["practitioner_code", "first_name", "last_name", "specialty", "license_number"]) if (!text(draft[field]).trim()) errors[field] = `${labelize(field)} is required.`; if (!text(draft.approval_status)) errors.approval_status = "Approval status is required." }
  if (screen === "claim-types") { for (const field of ["claim_category", "calculation_basis", "duplicate_check_rule"]) if (!text(draft[field])) errors[field] = `${labelize(field)} is required.`; if (draft.waiting_period_days !== null && numberValue(draft.waiting_period_days) < 0) errors.waiting_period_days = "Waiting period cannot be negative." }
  if (screen === "claim-reasons") { if (!text(draft.reason_category)) errors.reason_category = "Reason category is required." }
  if (screen === "claim-statuses") { if (!text(draft.badge_type)) errors.badge_type = "Badge type is required."; if (draft.is_terminal && Array.isArray(draft.allowed_transitions) && draft.allowed_transitions.length) errors.allowed_transitions = "Terminal statuses cannot have outgoing transitions."; if (Array.isArray(draft.allowed_transitions) && draft.allowed_transitions.includes(text(draft.code).toUpperCase())) errors.allowed_transitions = "A status cannot transition to itself." }
  if (screen === "discharge-types") { if (!text(draft.discharge_category)) errors.discharge_category = "Discharge category is required."; try { if (text(draft.variables).trim()) JSON.parse(text(draft.variables)) } catch { errors.variables = "Variables must be valid JSON object text." } }
  if (screen === "correspondent-types") { if (!text(draft.correspondence_category)) errors.correspondence_category = "Correspondence category is required."; if (!text(draft.communication_channel)) errors.communication_channel = "Communication channel is required." }
  return errors
}

function Choice({ label, value, onChange, options, required, error }: { label: string; value: unknown; onChange: (value: string) => void; options: FilterOption[]; required?: boolean; error?: string }) {
  return <SelectInput label={label} required={required} error={error} value={text(value)} onChange={(event) => onChange(event.target.value)}><option value="">Select an option</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</SelectInput>
}

function fieldValue(editor: Editor | null, key: string): string | number | readonly string[] | undefined { const value = editor?.[key]; return value === null || value === undefined ? "" : value as string | number | readonly string[] | undefined }
function textAreaValue(editor: Editor | null, key: string, fallback: object | unknown[] = {}) { const value = editor?.[key]; return typeof value === "string" ? value : jsonText(value, fallback) }

function EditorBody({ screen, editor, update, errors, choices, transitionOptions }: { screen: ScreenKey; editor: Editor; update: (key: string, value: Primitive) => void; errors: Record<string, string>; choices: Record<string, FilterOption[]>; transitionOptions: FilterOption[] }) {
  const input = (key: string, numeric = false) => ({ value: fieldValue(editor, key), onChange: (event: ChangeEvent<HTMLInputElement>) => update(key, numeric ? event.target.value : event.target.value) })
  const toggle = (key: string) => <Toggle label={labelize(key)} checked={Boolean(editor[key])} onChange={(value) => update(key, value)} />
  const scope = <><DateInput label="Effective from" required error={errors.effective_from} {...input("effective_from")} /><DateInput label="Effective to" error={errors.effective_to} {...input("effective_to")} /></>
  if (screen === "medical-codes") return <FormGrid columns={2}><TextInput label="Code" required error={errors.code} {...input("code")} /><TextInput label="Name" required error={errors.name} {...input("name")} /><TextInput label="Medical category" required error={errors.medical_category} {...input("medical_category")} />{scope}<TextareaInput label="Description" value={text(editor.description)} onChange={(event) => update("description", event.target.value)} /></FormGrid>
  if (screen === "medical-limits") return <div className="space-y-5"><InfoBanner title="Medical limit dimensions">The backend rejects overlapping active rows in the same medical-code scope, age, sum-assured, limit-type, frequency, and effective-date dimensions.</InfoBanner><FormGrid columns={2}><TextInput label="Code" required error={errors.code} {...input("code")} /><TextInput label="Name" required error={errors.name} {...input("name")} /><Choice label="Medical code" required error={errors.medical_code} value={editor.medical_code} onChange={(value) => update("medical_code", value)} options={choices.medical_code ?? []} /><Choice label="Product" value={editor.product} onChange={(value) => update("product", value)} options={choices.product ?? []} /><Choice label="Plan" value={editor.plan} onChange={(value) => update("plan", value)} options={choices.plan ?? []} /><Choice label="Limit type" required error={errors.limit_type} value={editor.limit_type} onChange={(value) => update("limit_type", value)} options={choices.limit_type ?? []} /><DecimalInput label="Age from" min={0} max={150} {...input("age_from", true)} /><DecimalInput label="Age to" min={0} max={150} error={errors.age_to} {...input("age_to", true)} /><DecimalInput label="Sum assured from" min={0} error={errors.sum_assured_from} {...input("sum_assured_from", true)} /><DecimalInput label="Sum assured to" min={0} error={errors.sum_assured_to} {...input("sum_assured_to", true)} /><DecimalInput label="Limit amount" required min={0} error={errors.limit_amount} {...input("limit_amount", true)} /><Choice label="Required frequency" required error={errors.required_frequency} value={editor.required_frequency} onChange={(value) => update("required_frequency", value)} options={choices.required_frequency ?? []} />{scope}</FormGrid><div className="flex gap-6">{toggle("mandatory_flag")}</div></div>
  if (screen === "personal-habits") return <FormGrid columns={2}><TextInput label="Code" required error={errors.code} {...input("code")} /><TextInput label="Name" required error={errors.name} {...input("name")} /><Choice label="Habit category" required error={errors.habit_category} value={editor.habit_category} onChange={(value) => update("habit_category", value)} options={choices.habit_category ?? []} /><Choice label="Underwriting impact" required error={errors.underwriting_impact} value={editor.underwriting_impact} onChange={(value) => update("underwriting_impact", value)} options={choices.underwriting_impact ?? []} /><TextareaInput label="Question text" required error={errors.question_text} value={text(editor.question_text)} onChange={(event) => update("question_text", event.target.value)} />{scope}<div className="flex gap-6">{toggle("requires_evidence")}</div><TextareaInput label="Description" value={text(editor.description)} onChange={(event) => update("description", event.target.value)} /></FormGrid>
  if (screen === "medical-history") return <FormGrid columns={2}><TextInput label="Code" required error={errors.code} {...input("code")} /><TextInput label="Name" required error={errors.name} {...input("name")} /><TextInput label="Condition category" required error={errors.condition_category} {...input("condition_category")} /><TextInput label="Severity" required error={errors.severity} {...input("severity")} /><DecimalInput label="Waiting period (days)" min={0} error={errors.waiting_period_days} {...input("waiting_period_days", true)} />{scope}<div className="flex gap-6">{toggle("exclusion_flag")}{toggle("loading_flag")}</div><TextareaInput label="Underwriting note" value={text(editor.underwriting_note)} onChange={(event) => update("underwriting_note", event.target.value)} /></FormGrid>
  if (screen === "medical-facilities") return <FormGrid columns={2}><TextInput label="Code" required error={errors.code} {...input("code")} /><TextInput label="Name" required error={errors.name} {...input("name")} /><TextInput label="Facility code" required error={errors.facility_code} {...input("facility_code")} /><TextInput label="Facility type" required error={errors.facility_type} {...input("facility_type")} /><TextInput label="Registration number" {...input("registration_number")} /><Choice label="Partner" value={editor.partner} onChange={(value) => update("partner", value)} options={choices.partner ?? []} /><TextInput label="Address" {...input("address")} /><TextInput label="City" {...input("city")} /><TextInput label="Country" {...input("country")} /><TextInput label="Contact email" {...input("contact_email")} /><TextInput label="Contact phone" {...input("contact_phone")} /><Choice label="Approval status" required error={errors.approval_status} value={editor.approval_status} onChange={(value) => update("approval_status", value)} options={choices.approval_status ?? []} />{scope}<TextareaInput label="Description" value={text(editor.description)} onChange={(event) => update("description", event.target.value)} /></FormGrid>
  if (screen === "medical-practitioners") return <FormGrid columns={2}><TextInput label="Code" required error={errors.code} {...input("code")} /><TextInput label="Name" required error={errors.name} {...input("name")} /><TextInput label="Practitioner code" required error={errors.practitioner_code} {...input("practitioner_code")} /><TextInput label="First name" required error={errors.first_name} {...input("first_name")} /><TextInput label="Last name" required error={errors.last_name} {...input("last_name")} /><TextInput label="Specialty" required error={errors.specialty} {...input("specialty")} /><TextInput label="License number" required error={errors.license_number} {...input("license_number")} /><Choice label="Medical facility" value={editor.medical_facility} onChange={(value) => update("medical_facility", value)} options={choices.medical_facility ?? []} /><Choice label="Partner" value={editor.partner} onChange={(value) => update("partner", value)} options={choices.partner ?? []} /><TextInput label="Email" {...input("email")} /><TextInput label="Phone" {...input("phone")} /><Choice label="Approval status" required error={errors.approval_status} value={editor.approval_status} onChange={(value) => update("approval_status", value)} options={choices.approval_status ?? []} />{scope}<TextareaInput label="Description" value={text(editor.description)} onChange={(event) => update("description", event.target.value)} /></FormGrid>
  if (screen === "claim-types") return <div className="space-y-5"><FormGrid columns={2}><TextInput label="Code" required error={errors.code} {...input("code")} /><TextInput label="Name" required error={errors.name} {...input("name")} /><Choice label="Claim category" required error={errors.claim_category} value={editor.claim_category} onChange={(value) => update("claim_category", value)} options={choices.claim_category ?? []} /><Choice label="Calculation basis" required error={errors.calculation_basis} value={editor.calculation_basis} onChange={(value) => update("calculation_basis", value)} options={choices.calculation_basis ?? []} /><Choice label="Duplicate check rule" required error={errors.duplicate_check_rule} value={editor.duplicate_check_rule} onChange={(value) => update("duplicate_check_rule", value)} options={choices.duplicate_check_rule ?? []} /><DecimalInput label="Waiting period (days)" min={0} error={errors.waiting_period_days} {...input("waiting_period_days", true)} />{scope}</FormGrid><TextareaInput label="Payable-to rules JSON" error={errors.payable_to_rules} value={textAreaValue(editor, "payable_to_rules", {})} onChange={(event) => update("payable_to_rules", event.target.value)} /><TextareaInput label="Required documents JSON array" error={errors.require_documents} value={textAreaValue(editor, "require_documents", [])} onChange={(event) => update("require_documents", event.target.value)} /><div className="flex gap-6">{toggle("allow_waiver_of_premium")}{toggle("require_approval")}</div></div>
  if (screen === "claim-reasons") return <FormGrid columns={2}><TextInput label="Code" required error={errors.code} {...input("code")} /><TextInput label="Name" required error={errors.name} {...input("name")} /><Choice label="Claim type" value={editor.claim_type} onChange={(value) => update("claim_type", value)} options={choices.claim_type ?? []} /><Choice label="Reason category" required error={errors.reason_category} value={editor.reason_category} onChange={(value) => update("reason_category", value)} options={choices.reason_category ?? []} />{scope}<TextareaInput label="Description" value={text(editor.description)} onChange={(event) => update("description", event.target.value)} /></FormGrid>
  if (screen === "claim-statuses") return <div className="space-y-5"><InfoBanner title="Transition editor">Select active target statuses. Terminal statuses cannot have outgoing transitions and a status cannot transition to itself.</InfoBanner><FormGrid columns={2}><TextInput label="Code" required error={errors.code} {...input("code")} /><TextInput label="Name" required error={errors.name} {...input("name")} /><DecimalInput label="Display order" min={0} {...input("display_order", true)} /><Choice label="Badge type" required error={errors.badge_type} value={editor.badge_type} onChange={(value) => update("badge_type", value)} options={choices.badge_type ?? []} />{scope}</FormGrid><div className="flex gap-6">{toggle("is_terminal")}{toggle("is_payable")}</div><fieldset className="rounded-lg border p-4"><legend className="px-2 text-sm font-bold">Allowed transitions</legend><div className="grid gap-2 sm:grid-cols-2">{transitionOptions.filter((option) => option.value !== text(editor.code)).map((option) => <label key={option.value} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Array.isArray(editor.allowed_transitions) && editor.allowed_transitions.includes(option.value)} disabled={Boolean(editor.is_terminal)} onChange={(event) => { const current = Array.isArray(editor.allowed_transitions) ? editor.allowed_transitions : []; update("allowed_transitions", event.target.checked ? [...current, option.value] : current.filter((value) => value !== option.value)) }} />{option.label}</label>)}</div>{errors.allowed_transitions && <p className="mt-2 text-xs text-[var(--destructive)]">{errors.allowed_transitions}</p>}</fieldset><TextareaInput label="Description" value={text(editor.description)} onChange={(event) => update("description", event.target.value)} /></div>
  if (screen === "discharge-types") return <div className="space-y-5"><FormGrid columns={2}><TextInput label="Code" required error={errors.code} {...input("code")} /><TextInput label="Name" required error={errors.name} {...input("name")} /><Choice label="Discharge category" required error={errors.discharge_category} value={editor.discharge_category} onChange={(value) => update("discharge_category", value)} options={choices.discharge_category ?? []} /><TextInput label="Template code" {...input("template_code")} />{scope}</FormGrid><TextareaInput label="Variables JSON object" error={errors.variables} value={textAreaValue(editor, "variables", {})} onChange={(event) => update("variables", event.target.value)} /><TextareaInput label="Description" value={text(editor.description)} onChange={(event) => update("description", event.target.value)} /></div>
  return <FormGrid columns={2}><TextInput label="Code" required error={errors.code} {...input("code")} /><TextInput label="Name" required error={errors.name} {...input("name")} /><Choice label="Correspondence category" required error={errors.correspondence_category} value={editor.correspondence_category} onChange={(value) => update("correspondence_category", value)} options={choices.correspondence_category ?? []} /><Choice label="Communication channel" required error={errors.communication_channel} value={editor.communication_channel} onChange={(value) => update("communication_channel", value)} options={choices.communication_channel ?? []} /><TextInput label="Purpose" {...input("purpose")} />{scope}<TextareaInput label="Description" value={text(editor.description)} onChange={(event) => update("description", event.target.value)} /></FormGrid>
}

export default function OLMOrbClaimSetup({ section = "medical" }: { section?: Section }) {
  const [screen, setScreen] = useState<ScreenKey>(section === "claims" ? "claim-types" : "medical-codes")
  const [filters, setFilters] = useState<FilterValues>({})
  const [rows, setRows] = useState<AnyRecord[]>([])
  const [editor, setEditor] = useState<Editor | null>(null)
  const [errors, setErrors] = useState<Record<string, string>>({})
  const [confirm, setConfirm] = useState<AnyRecord | null>(null)
  const [saving, setSaving] = useState(false)
  const [refreshKey, setRefreshKey] = useState(0)
  const [transitionRows, setTransitionRows] = useState<AnyRecord[]>([])
  const config = configs[screen]
  const { access, canAccess, isSuperAdmin } = useAccess()
  const { toast } = useToast()
  const permissions = isSuperAdmin ? ["ol_parameters.view", "ol_parameters.create", "ol_parameters.update", "ol_parameters.deactivate"] : access.permissions.map((permission) => `${permission.module}.${permission.action}`)
  const writable = isSuperAdmin || (canAccess("ol_parameters") && (permissions.length === 0 || permissions.some((permission) => /\.(create|update|write)$/.test(permission))))
  const { choices } = useRemoteChoices(config.endpoint, config.choiceFields, rows)
  const choiceMap = useMemo(() => Object.fromEntries(config.filters.map((filter) => [filter.key, filter.key === "is_active" ? statusOptions : choices[filter.key] ?? []])), [choices, config.filters])
  const definitions = useMemo(() => config.filters.map((filter) => ({ ...filter, options: choiceMap[filter.key] })), [choiceMap, config.filters])

  useEffect(() => { setFilters({}); setEditor(null); setErrors({}) }, [screen])
  useEffect(() => { let active = true; request<unknown>(`${configs["claim-statuses"].endpoint}?page_size=100`).then((payload) => { if (active) setTransitionRows(normalizeTableResponse<AnyRecord>(payload).results) }).catch(() => { if (active) setTransitionRows([]) }); return () => { active = false } }, [refreshKey])
  const transitionOptions = useMemo(() => transitionRows.filter((row) => row.is_active).map((row) => ({ value: row.code, label: `${row.code} — ${row.name}` })), [transitionRows])
  const fetcher = useCallback(async (query: TableQuery) => { const result = normalizeTableResponse<AnyRecord>(await request<unknown>(`${config.endpoint}${buildTableQuery(query)}`)); setRows(result.results); return result }, [config.endpoint])
  const update = (key: string, value: Primitive) => setEditor((current) => current ? { ...current, [key]: value } : current)
  const openNew = () => { setErrors({}); setEditor(defaults(screen)) }
  const openEdit = (row: AnyRecord) => { setErrors({}); setEditor({ ...row, allowed_transitions: Array.isArray(row.allowed_transitions) ? row.allowed_transitions : [] }) }
  const serialize = (draft: Editor) => { const body = { ...draft }; delete body.id; for (const key of ["payable_to_rules", "require_documents", "variables"]) { if (typeof body[key] === "string") { try { body[key] = JSON.parse(body[key] as string) as Primitive } catch { /* client validation handles malformed JSON */ } } } return body }
  const save = async () => { if (!editor) return; const nextErrors = validate(screen, editor); setErrors(nextErrors); if (Object.keys(nextErrors).length) { toast({ tone: "danger", title: "Review the highlighted fields" }); return }; setSaving(true); try { await request(`${config.endpoint}${editor.id ? `${editor.id}/` : ""}`, { method: editor.id ? "PATCH" : "POST", body: JSON.stringify(serialize(editor)) }); toast({ tone: "success", title: `${config.title} ${editor.id ? "updated" : "created"}` }); setEditor(null); setRefreshKey((value) => value + 1) } catch (error) { toast({ tone: "danger", title: `Unable to save ${config.title}`, message: error instanceof Error ? error.message : "The backend rejected this configuration." }) } finally { setSaving(false) } }
  const deactivate = async () => { if (!confirm) return; try { await request(`${config.endpoint}${confirm.id}/deactivate/`, { method: "POST" }); toast({ tone: "success", title: `${config.title} deactivated` }); setConfirm(null); setRefreshKey((value) => value + 1) } catch (error) { toast({ tone: "danger", title: "Unable to deactivate", message: error instanceof Error ? error.message : "The backend rejected the action." }) } }
  const actions: RowAction<AnyRecord>[] = [{ key: "edit", label: "Edit", permission: "ol_parameters.update", onSelect: openEdit }, { key: "deactivate", label: "Deactivate", permission: "ol_parameters.deactivate", tone: "danger", isVisible: (row) => row.is_active, onSelect: setConfirm }]
  const activeKeys = section === "claims" ? claimKeys : medicalKeys
  const sectionTitle = section === "claims" ? "OL Claim Setup" : "OL Medical Underwriting"
  const sectionDescription = section === "claims" ? "Configure claim types, reasons, statuses, discharge documents, and correspondence channels." : "Configure medical evidence, underwriting limits, habits, histories, facilities, and practitioners."
  return <div className="space-y-5 p-4 md:p-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-[var(--muted-foreground)]">{section === "claims" ? <ClipboardCheck size={15} aria-hidden="true" /> : <HeartPulse size={15} aria-hidden="true" />} Ordinary Life Parameters</div><h1 className="text-2xl font-black tracking-tight">{sectionTitle}</h1><p className="mt-1 max-w-3xl text-sm text-[var(--muted-foreground)]">{sectionDescription}</p></div><button type="button" className="button-primary" disabled={!writable} onClick={openNew}><Plus size={16} aria-hidden="true" />New setup</button></header><div className="flex flex-wrap gap-2" role="tablist" aria-label={sectionTitle}>{activeKeys.map((key) => <button key={key} type="button" role="tab" aria-selected={screen === key} className={screen === key ? "button-primary" : "button-secondary"} onClick={() => setScreen(key)}>{configs[key].title}</button>)}</div><FilterBar definitions={definitions} value={filters} onChange={(key, value) => setFilters((current) => ({ ...current, [key]: value }))} onReset={() => setFilters({})} /><DataTable metadata={{ totalLabel: config.title, defaultOrdering: "code", columns: config.columns } satisfies TableMetadata<AnyRecord>} fetcher={fetcher} filters={filters} refreshKey={refreshKey} actions={writable ? actions : []} permissions={permissions} exportFileName={`ol-${screen}.csv`} /><FormModal open={Boolean(editor)} title={editor?.id ? `Edit ${config.title}` : `Create ${config.title}`} description="Options are loaded from backend serializer metadata and current active records." onClose={() => setEditor(null)} onSave={() => void save()} saving={saving} saveLabel="Save setup">{editor && <EditorBody screen={screen} editor={editor} update={update} errors={errors} choices={choices} transitionOptions={transitionOptions} />}</FormModal><ConfirmModal open={Boolean(confirm)} title={`Deactivate ${config.title}`} description="This setup will no longer be selected for new underwriting or claim workflows." confirmLabel="Deactivate" onClose={() => setConfirm(null)} onConfirm={() => void deactivate()} /></div>
}
