import { Plus, Trash2 } from "lucide-react"
import { useMemo } from "react"
import type { ReactNode } from "react"

export type EditableGridColumn<T> = { key: string; label: string; width?: string; render: (row: T, index: number, update: (patch: Partial<T>) => void) => ReactNode }

export type EditableGridProps<T> = { rows: T[]; columns: EditableGridColumn<T>[]; getRowId: (row: T, index: number) => string; createRow: () => T; onChange: (rows: T[]) => void; validateRow?: (row: T, index: number) => Record<string, string>; total?: { label: string; getValue: (row: T) => number; target?: number; format?: (value: number) => string } }

export function EditableGrid<T>({ rows, columns, getRowId, createRow, onChange, validateRow, total }: EditableGridProps<T>) {
  const errors = useMemo(() => rows.map((row, index) => validateRow?.(row, index) ?? {}), [rows, validateRow])
  const totalValue = total ? rows.reduce((sum, row) => sum + (Number(total.getValue(row)) || 0), 0) : 0
  const totalValid = total?.target === undefined || Math.abs(totalValue - total.target) < 0.000001
  const updateRow = (index: number, patch: Partial<T>) => onChange(rows.map((row, rowIndex) => rowIndex === index ? { ...row, ...patch } : row))
  return <div className="overflow-hidden rounded-[10px] border"><div className="flex items-center justify-between border-b bg-[var(--muted)]/45 px-4 py-3"><div><p className="text-sm font-bold">Rate rows</p><p className="text-xs text-[var(--muted-foreground)]">Edit values inline; validation is shown per row.</p></div><button type="button" className="button-secondary !min-h-9 !px-3" onClick={() => onChange([...rows, createRow()])}><Plus size={15} aria-hidden="true" />Add row</button></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-[var(--muted)]/30 text-xs uppercase tracking-[0.08em] text-[var(--muted-foreground)]"><tr>{columns.map((column) => <th key={column.key} scope="col" style={{ width: column.width }} className="px-3 py-2.5 font-bold">{column.label}</th>)}<th scope="col" className="w-12 px-3 py-2.5"><span className="sr-only">Remove</span></th></tr></thead><tbody className="divide-y divide-[var(--border)]">{rows.map((row, index) => { const rowErrors = errors[index]; return <tr key={getRowId(row, index)} className={Object.keys(rowErrors).length ? "bg-[var(--destructive)]/5" : ""}>{columns.map((column) => <td key={column.key} className="px-3 py-2 align-top"><div>{column.render(row, index, (patch) => updateRow(index, patch))}</div>{rowErrors[column.key] && <p className="mt-1 text-[11px] font-semibold text-[var(--destructive)]" role="alert">{rowErrors[column.key]}</p>}</td>)}<td className="px-3 py-2 align-top"><button type="button" className="rounded-md p-2 text-[var(--destructive)] hover:bg-[var(--destructive)]/10" aria-label={`Remove row ${index + 1}`} onClick={() => onChange(rows.filter((_, rowIndex) => rowIndex !== index))}><Trash2 size={16} aria-hidden="true" /></button></td></tr>})}</tbody>{total && <tfoot className="border-t bg-[var(--muted)]/35"><tr><th colSpan={Math.max(1, columns.length)} className="px-3 py-3 text-right text-sm font-bold">{total.label}</th><td className={`px-3 py-3 text-right text-sm font-extrabold ${totalValid ? "text-[var(--success)]" : "text-[var(--destructive)]"}`}>{total.format ? total.format(totalValue) : totalValue.toFixed(2)}{total.target !== undefined && <span className="ml-1 text-xs font-medium text-[var(--muted-foreground)]">/ {total.format ? total.format(total.target) : total.target.toFixed(2)}</span>}</td></tr></tfoot>}</table></div></div>
}
