import { ArrowDownRight, ArrowUpRight, BarChart3, Minus, MoreHorizontal } from "lucide-react"
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import type { ReactNode } from "react"
import { StatusBadge, type StatusTone } from "./StatusBadge"

export function KPIStat({ label, value, helper, trend, tone = "neutral", icon }: { label: string; value: ReactNode; helper?: string; trend?: { value: string; direction: "up" | "down" | "flat" }; tone?: StatusTone; icon?: ReactNode }) {
  const trendIcon = trend?.direction === "up" ? <ArrowUpRight size={13} /> : trend?.direction === "down" ? <ArrowDownRight size={13} /> : <Minus size={13} />
  return <article className="surface-card p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.1em] text-[var(--muted-foreground)]">{label}</p><p className="mt-2 text-2xl font-extrabold tracking-tight">{value}</p></div><div className="flex h-10 w-10 items-center justify-center rounded-[10px] bg-[var(--primary)]/10 text-[var(--primary)]">{icon ?? <BarChart3 size={18} aria-hidden="true" />}</div></div>{(helper || trend) && <div className="mt-3 flex items-center justify-between gap-2 text-xs"><span className="text-[var(--muted-foreground)]">{helper}</span>{trend && <span className={`inline-flex items-center gap-0.5 font-bold ${tone === "danger" ? "text-[var(--destructive)]" : "text-[var(--success)]"}`}>{trendIcon}{trend.value}</span>}</div>}</article>
}

export function SimpleAreaChart({ data, dataKey, xKey = "name", color = "var(--primary)", title, height = 240 }: { data: Array<Record<string, string | number>>; dataKey: string; xKey?: string; color?: string; title: string; height?: number }) {
  return <article className="surface-card p-4" aria-label={title}><div className="mb-4 flex items-center justify-between"><div><p className="text-sm font-bold">{title}</p><p className="text-xs text-[var(--muted-foreground)]">Backend-driven trend</p></div><MoreHorizontal size={18} className="text-[var(--muted-foreground)]" aria-hidden="true" /></div><div style={{ height }}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{ top: 4, right: 4, left: -24, bottom: 0 }}><defs><linearGradient id={`area-${dataKey}`} x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={color} stopOpacity={0.28} /><stop offset="95%" stopColor={color} stopOpacity={0.02} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="var(--border)" vertical={false} /><XAxis dataKey={xKey} tick={{ fontSize: 11, fill: "var(--muted-foreground)" }} axisLine={false} tickLine={false} /><YAxis tick={{ fontSize: 11, fill: "var(--muted-foreground)" }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ borderRadius: 10, borderColor: "var(--border)", background: "var(--popover)", color: "var(--foreground)" }} /><Area type="monotone" dataKey={dataKey} stroke={color} fill={`url(#area-${dataKey})`} strokeWidth={2.5} /></AreaChart></ResponsiveContainer></div></article>
}

export function MasterDetailPage({ eyebrow, title, description, status, stats, tabs, activeTab, onTabChange, children, actions }: { eyebrow?: string; title: string; description?: string; status?: { value: string; tone?: StatusTone }; stats?: Array<{ label: string; value: ReactNode; helper?: string }>; tabs?: Array<{ id: string; label: string }>; activeTab?: string; onTabChange?: (id: string) => void; children: ReactNode; actions?: ReactNode }) {
  return <div className="space-y-5"><header className="section-header p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-white/70">{eyebrow ?? "Workspace"}</p><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="text-2xl font-extrabold tracking-tight">{title}</h1>{status && <StatusBadge value={status.value} tone={status.tone} className="bg-white/15 text-white" />}</div>{description && <p className="mt-2 max-w-2xl text-sm leading-6 text-white/80">{description}</p>}</div>{actions && <div className="flex flex-wrap gap-2">{actions}</div>}</div></header>{stats && stats.length > 0 && <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat) => <KPIStat key={stat.label} label={stat.label} value={stat.value} helper={stat.helper} />)}</div>}{tabs && <nav className="surface-card flex gap-1 overflow-x-auto p-1" aria-label="Detail tabs">{tabs.map((tab) => <button type="button" key={tab.id} onClick={() => onTabChange?.(tab.id)} className={`whitespace-nowrap rounded-[9px] px-4 py-2.5 text-sm font-bold transition ${activeTab === tab.id ? "bg-[var(--primary)] text-[var(--primary-foreground)]" : "text-[var(--muted-foreground)] hover:bg-[var(--secondary)] hover:text-[var(--foreground)]"}`} aria-current={activeTab === tab.id ? "page" : undefined}>{tab.label}</button>)}</nav>}{children}</div>
}
