from django.urls import path

from apps.ol_proposals.views import (
    PartnerPortalProposalDetailView,
    PartnerPortalProposalListView,
    ProposalBeneficiaryCollectionView,
    ProposalBeneficiaryItemView,
    ProposalCancelView,
    ProposalCompletenessView,
    ProposalConvertToPolicyView,
    ProposalDashboardKpisView,
    ProposalDetailView,
    ProposalDocumentCollectionView,
    ProposalEnrichmentOptionsView,
    ProposalEnrichView,
    ProposalExportView,
    ProposalFirstPremiumStatusView,
    ProposalHealthAnswersView,
    ProposalHealthQuestionsView,
    ProposalKpisView,
    ProposalListView,
    ProposalMarkPaymentReadyView,
    ProposalPaymentReadinessView,
    ProposalPrintView,
    ProposalReactivateView,
    ProposalReportingDatasetView,
    ProposalUnderwritingDecisionView,
)

urlpatterns = [
    path("proposals/", ProposalListView.as_view(), name="ol-proposals-list"),
    path("proposals/kpis/", ProposalKpisView.as_view(), name="ol-proposals-kpis"),
    path("proposals/dashboard-kpis/", ProposalDashboardKpisView.as_view(), name="ol-proposals-dashboard-kpis"),
    path("proposals/reporting/dataset/", ProposalReportingDatasetView.as_view(), name="ol-proposals-reporting-dataset"),
    path("proposals/export/", ProposalExportView.as_view(), name="ol-proposals-export"),
    path("proposals/portal/", PartnerPortalProposalListView.as_view(), name="ol-proposals-portal-list"),
    path("proposals/portal/<uuid:proposal_id>/", PartnerPortalProposalDetailView.as_view(), name="ol-proposals-portal-detail"),
    path("proposals/options/<str:kind>/", ProposalEnrichmentOptionsView.as_view(), name="ol-proposals-enrichment-options"),
    path("proposals/<uuid:proposal_id>/", ProposalDetailView.as_view(), name="ol-proposals-detail"),
    path("proposals/<uuid:proposal_id>/enrich/", ProposalEnrichView.as_view(), name="ol-proposals-enrich"),
    path("proposals/<uuid:proposal_id>/cancel/", ProposalCancelView.as_view(), name="ol-proposals-cancel"),
    path("proposals/<uuid:proposal_id>/convert/", ProposalConvertToPolicyView.as_view(), name="ol-proposals-convert"),
    path("proposals/<uuid:proposal_id>/reactivate/", ProposalReactivateView.as_view(), name="ol-proposals-reactivate"),
    path("proposals/<uuid:proposal_id>/print/", ProposalPrintView.as_view(), name="ol-proposals-print"),
    path("proposals/<uuid:proposal_id>/completeness/", ProposalCompletenessView.as_view(), name="ol-proposals-completeness"),
    path("proposals/<uuid:proposal_id>/documents/", ProposalDocumentCollectionView.as_view(), name="ol-proposals-documents"),
    path("proposals/<uuid:proposal_id>/health-questions/", ProposalHealthQuestionsView.as_view(), name="ol-proposals-health-questions"),
    path("proposals/<uuid:proposal_id>/health-answers/", ProposalHealthAnswersView.as_view(), name="ol-proposals-health-answers"),
    path("proposals/<uuid:proposal_id>/underwriting-decision/", ProposalUnderwritingDecisionView.as_view(), name="ol-proposals-underwriting-decision"),
    path("proposals/<uuid:proposal_id>/payment-readiness/", ProposalPaymentReadinessView.as_view(), name="ol-proposals-payment-readiness"),
    path("proposals/<uuid:proposal_id>/mark-payment-ready/", ProposalMarkPaymentReadyView.as_view(), name="ol-proposals-mark-payment-ready"),
    path("proposals/<uuid:proposal_id>/first-premium/", ProposalFirstPremiumStatusView.as_view(), name="ol-proposals-first-premium"),
    path("proposals/<uuid:proposal_id>/beneficiaries/", ProposalBeneficiaryCollectionView.as_view(), name="ol-proposals-beneficiaries"),
    path("proposals/<uuid:proposal_id>/beneficiaries/<uuid:beneficiary_id>/", ProposalBeneficiaryItemView.as_view(), name="ol-proposals-beneficiary-item"),
]